// @ts-nocheck
// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: boot.d,v 1.6 2006/03/18 02:42:09 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.boot;

// D_IMPORT: private import std.string;
// D_IMPORT: private import std.stream;
// D_IMPORT: private import std.math;
// D_IMPORT: private import std.c.stdlib;
// D_IMPORT: private import abagames.util.logger;
// D_IMPORT: private import abagames.util.tokenizer;
// D_IMPORT: private import abagames.util.sdl.mainloop;
// D_IMPORT: private import abagames.util.sdl.input;
// D_IMPORT: private import abagames.util.sdl.pad;
// D_IMPORT: private import abagames.util.sdl.twinstick;
// D_IMPORT: private import abagames.util.sdl.recordableinput;
// D_IMPORT: private import abagames.util.sdl.sound;
// D_IMPORT: private import abagames.gr.screen;
// D_IMPORT: private import abagames.gr.gamemanager;
// D_IMPORT: private import abagames.gr.prefmanager;
// D_IMPORT: private import abagames.gr.ship;
// D_IMPORT: private import abagames.gr.mouse;

/**
 * Boot the game.
 */
// PORT_NOTE[D2TS:visibility-block]:
// reason: D visibility block syntax is unsupported in TS.
// original: private:
let screen: Screen;
let input: MultipleInputDevice;
let pad: RecordablePad;
let twinStick: RecordableTwinStick;
let mouse: RecordableMouse;
let gameManager: GameManager;
let prefManager: PrefManager;
let mainLoop: MainLoop;

// PORT_NOTE[D2TS:conditional-compilation]:
// reason: D conditional compilation is not auto-converted.
// original: version (Win32_release) {
  // Boot as the Windows executable.
  // D_IMPORT: private import std.c.windows.windows;
  // D_IMPORT: private import std.string;

  // PORT_NOTE[D2TS:extern]:
  // reason: ABI declaration requires manual rewrite.
  // original: extern (C) void gc_init();
  // PORT_NOTE[D2TS:extern]:
  // reason: ABI declaration requires manual rewrite.
  // original: extern (C) void gc_term();
  // PORT_NOTE[D2TS:extern]:
  // reason: ABI declaration requires manual rewrite.
  // original: extern (C) void _minit();
  // PORT_NOTE[D2TS:extern]:
  // reason: ABI declaration requires manual rewrite.
  // original: extern (C) void _moduleCtor();

  // PORT_NOTE[D2TS:extern]:
  // reason: ABI declaration requires manual rewrite.
  // original: extern (Windows)
  export function WinMain(hInstance: HINSTANCE, hPrevInstance: HINSTANCE, lpCmdLine: LPSTR, nCmdShow: number): number {
    let result: number;
    gc_init();
    _minit();
    try {
      _moduleCtor();
      let exe: string[] = new Array(4096);
      GetModuleFileNameA(null, exe, 4096);
      let prog: string[][1];
      prog[0] = std.string.toString(exe);
      result = boot(prog + std.string.split(std.string.toString(lpCmdLine)));
    } catch (o) /* PORT_NOTE[D2TS:catch-type] D catch type was removed */ {
      Logger.error("Exception: " + o.toString());
      result = EXIT_FAILURE;
    }
    gc_term();
    return result;
  }
// Boot as the general executable.
export function main(args: string[][]): number {
  return boot(args);
}

export function boot(args: string[][]): number {
  screen = new Screen();
  input = new MultipleInputDevice();
  pad = new RecordablePad();
  twinStick = new RecordableTwinStick();
  mouse = new RecordableMouse(screen);
  input.inputs.push(pad); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
  input.inputs.push(twinStick); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
  input.inputs.push(mouse); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
  gameManager = new GameManager();
  prefManager = new PrefManager();
  mainLoop = new MainLoop(screen, input, gameManager, prefManager);
  try {
    parseArgs(args);
  } catch (e) /* PORT_NOTE[D2TS:catch-type] D catch type was removed */ {
    return EXIT_FAILURE;
  }
  try {
    mainLoop.loop();
  } catch (o) /* PORT_NOTE[D2TS:catch-type] D catch type was removed */ {
    Logger.info(o.toString());
    try {
      gameManager.saveErrorReplay();
    } catch (o1) /* PORT_NOTE[D2TS:catch-type] D catch type was removed */ {}
    throw o;
  }
  return EXIT_SUCCESS;
}

function parseArgs(commandArgs: string[][]): void {
  let args: string[][] = readOptionsIniFile();
  for (let i = 1; i < commandArgs.length; i++)
    args.push(commandArgs[i]); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
  let progName: string[] = commandArgs[0];
  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
    case "-brightness":
      if (i >= args.length - 1) {
        usage(progName);
        throw new Exception("Invalid options");
      }
      i++;
      let b: number = /* D_CAST(float) */ std.string.atoi(args[i]) / 100;
      if (b < 0 || b > 1) {
        usage(args[0]);
        throw new Exception("Invalid options");
      }
      Screen.brightness = b;
      break;
    case "-luminosity":
    case "-luminous":
      if (i >= args.length - 1) {
        usage(progName);
        throw new Exception("Invalid options");
      }
      i++;
      let l: number = /* D_CAST(float) */ std.string.atoi(args[i]) / 100;
      if (l < 0 || l > 1) {
        usage(progName);
        throw new Exception("Invalid options");
      }
      screen.luminosity = l;
      break;
    case "-window":
      screen.windowMode = true;
      break;
    case "-res":
      if (i >= args.length - 2) {
        usage(progName);
        throw new Exception("Invalid options");
      }
      i++;
      let w: number = std.string.atoi(args[i]);
      i++;
      let h: number = std.string.atoi(args[i]);
      screen.width = w;
      screen.height = h;
      break;
    case "-nosound":
      SoundManager.noSound = true;
      break;
    case "-exchange":
      pad.buttonReversed = true;
      break;
    case "-nowait":
      mainLoop.nowait = true;
      break;
    case "-accframe":
      mainLoop.accframe = 1;
      break;
    case "-turnspeed":
      if (i >= args.length - 1) {
        usage(progName);
        throw new Exception("Invalid options");
      }
      i++;
      let s: number = /* D_CAST(float) */ std.string.atoi(args[i]) / 100;
      if (s < 0 || s > 5) {
        usage(progName);
        throw new Exception("Invalid options");
      }
      GameManager.shipTurnSpeed = s;
      break;
    case "-firerear":
      GameManager.shipReverseFire = true;
      break;
    case "-rotatestick2":
    case "-rotaterightstick":
      if (i >= args.length - 1) {
        usage(progName);
        throw new Exception("Invalid options");
      }
      i++;
      twinStick.rotate = /* D_CAST(float) */ std.string.atoi(args[i]) * PI / 180.0;
      break;
    case "-reversestick2":
    case "-reverserightstick":
      twinStick.reverse = -1;
      break;
    case "-enableaxis5":
      twinStick.enableAxis5 = true;
      break;
    // PORT_NOTE[D2TS:commented-option]:
    // original D source had a disabled "-mouseaccel" option block.
    default:
      usage(progName);
      throw new Exception("Invalid options");
    }
  }
}

const OPTIONS_INI_FILE: string = "options.ini";

function readOptionsIniFile(): string[][] {
  try {
    return Tokenizer.readFile(OPTIONS_INI_FILE, " ");
  } catch (e) /* PORT_NOTE[D2TS:catch-type] D catch type was removed */ {
    return null;
  }
}

function usage(progName: string[]): void {
  Logger.error
    ("Usage: " + progName + " [-window] [-res x y] [-brightness [0-100]] [-luminosity [0-100]] [-nosound] [-exchange] [-turnspeed [0-500]] [-firerear] [-rotatestick2 deg] [-reversestick2] [-enableaxis5] [-nowait]");
}
