// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: bullet.d,v 1.1.1.1 2005/06/18 00:46:00 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.bullet;

// D_IMPORT: private import std.math;
// D_IMPORT: private import std.c.stdarg;
// D_IMPORT: private import opengl;
// D_IMPORT: private import abagames.util.actor;
// D_IMPORT: private import abagames.util.vector;
// D_IMPORT: private import abagames.util.math;
// D_IMPORT: private import abagames.util.sdl.shape;
// D_IMPORT: private import abagames.gr.gamemanager;
// D_IMPORT: private import abagames.gr.field;
// D_IMPORT: private import abagames.gr.ship;
// D_IMPORT: private import abagames.gr.screen;
// D_IMPORT: private import abagames.gr.enemy;
// D_IMPORT: private import abagames.gr.shot;
// D_IMPORT: private import abagames.gr.particle;
// D_IMPORT: private import abagames.gr.crystal;
// D_IMPORT: private import abagames.gr.shape;

/**
 * Enemy's bullets.
 */
export class Bullet extends Actor {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  gameManager: GameManager;
  field: Field;
  ship: Ship;
  smokes: SmokePool;
  wakes: WakePool;
  crystals: CrystalPool;
  pos: Vector;
  ppos: Vector;
  deg: number;
  speed: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float deg, speed;
  trgDeg: number;
  trgSpeed: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float trgDeg, trgSpeed;
  size: number;
  cnt: number;
  range: number;
  _destructive: boolean;
  shape: BulletShape;
  _enemyIdx: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor() {
    this.pos = new Vector();
    this.ppos = new Vector();
    this.shape = new BulletShape();
    this.deg = this.trgDeg = 0;
    this.speed = this.trgSpeed = 1;
    this.size = 1;
    this.range = 1;
  }

  public override init(args: unknown[]): void {
    this.gameManager = /* D_CAST(GameManager) */ args[0];
    this.field = /* D_CAST(Field) */ args[1];
    this.ship = /* D_CAST(Ship) */ args[2];
    this.smokes = /* D_CAST(SmokePool) */ args[3];
    this.wakes = /* D_CAST(WakePool) */ args[4];
    this.crystals = /* D_CAST(CrystalPool) */ args[5];
  }

  public set(enemyIdx: number, p: Vector, deg: number, speed: number, size: number, shapeType: number, range: number, startSpeed: number = 0, startDeg: number = -99999, destructive: boolean = false): void {
    if (!this.field.checkInOuterFieldExceptTop(p))
      return;
    this._enemyIdx = enemyIdx;
    this.ppos.x = this.pos.x = p.x;
    this.ppos.y = this.pos.y = p.y;
    this.speed = startSpeed;
    if (startDeg == -99999)
      this.deg = deg;
    else
      this.deg = startDeg;
    this.trgDeg = deg;
    this.trgSpeed = speed;
    this.size = size;
    this.range = range;
    this._destructive = destructive;
    this.shape.set(shapeType);
    this.shape.size = size;
    this.cnt = 0;
    exists = true;
  }

  public override move(): void {
    this.ppos.x = this.pos.x;
    this.ppos.y = this.pos.y;
    if (this.cnt < 30) {
      this.speed += (this.trgSpeed - this.speed) * 0.066;
      let md: number = this.trgDeg - this.deg;
      Math.normalizeDeg(md);
      this.deg += md * 0.066;
      if (this.cnt == 29) {
        this.speed = this.trgSpeed;
        this.deg = this.trgDeg;
      }
    }
    if (this.field.checkInOuterField(this.pos))
      this.gameManager.addSlowdownRatio(this.speed * 0.24);
    let mx: number = sin(this.deg) * this.speed;
    let my: number = cos(this.deg) * this.speed;
    this.pos.x += mx;
    this.pos.y += my;
    this.pos.y -= this.field.lastScrollY;
    if (this.ship.checkBulletHit(this.pos, this.ppos) || !this.field.checkInOuterFieldExceptTop(this.pos)) {
      remove();
      return;
    }
    this.cnt++;
    this.range -= this.speed;
    if (this.range <= 0)
      startDisappear();
    if (this.field.getBlock(this.pos) >= Field.ON_BLOCK_THRESHOLD)
      startDisappear();
  }

  public startDisappear(): void {
    if (this.field.getBlock(this.pos) >= 0) {
      let s: Smoke = this.smokes.getInstanceForced();
      s.set(this.pos, sin(this.deg) * this.speed * 0.2, cos(this.deg) * this.speed * 0.2, 0,
            Smoke.SmokeType.SAND, 30, this.size * 0.5);
    } else {
      let w: Wake = this.wakes.getInstanceForced();
      w.set(this.pos, this.deg, this.speed, 60, this.size * 3, true);
    }
    remove();
  }

  public changeToCrystal(): void {
    let c: Crystal = this.crystals.getInstance();
    if (c)
      c.set(this.pos);
    remove();
  }

  public remove(): void {
    exists = false;
  }

  public override draw(): void {
    if (!this.field.checkInOuterField(this.pos))
      return;
    glPushMatrix();
    Screen.glTranslate(this.pos);
    if (this._destructive) {
      glRotatef(this.cnt * 13, 0, 0, 1);
    } else {
      glRotatef(-this.deg * 180 / PI, 0, 0, 1);
      glRotatef(this.cnt * 13, 0, 1, 0);
    }
    this.shape.draw();
    glPopMatrix();
  }

  public checkShotHit(p: Vector, s: Collidable, shot: Shot): void {
    let ox: number = fabs(this.pos.x - p.x), oy = fabs(this.pos.y - p.y);
    if (ox + oy < 0.5) {
    //if (shape.checkCollision(ox, oy, s)) {
      shot.removeHitToBullet();
      let s: Smoke = this.smokes.getInstance();
      if (s)
        s.set(this.pos, sin(this.deg) * this.speed, cos(this.deg) * this.speed, 0,
              Smoke.SmokeType.SPARK, 30, this.size * 0.5);
      this.remove();
    }
  }

  public destructive(): boolean {
    return this._destructive;
  }

  public enemyIdx(): number {
    return this._enemyIdx;
  }
}

export class BulletPool extends ActorPool<Bullet> {
  public constructor(n: number, args: unknown[]) {
    super(n, args);
  }

  public removeIndexedBullets(idx: number): number {
    let n: number = 0;
    for (const b of actor) {
      if (b.exists && b.enemyIdx == idx) {
        b.changeToCrystal();
        n++;
      }
    }
    return n;
  }

  public checkShotHit(pos: Vector, shape: Collidable, shot: Shot): void {
    for (const b of actor)
      if (b.exists && b.destructive)
        b.checkShotHit(pos, shape, shot);
  }
}
