// @ts-nocheck
// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: crystal.d,v 1.2 2005/07/17 11:02:45 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.crystal;

// D_IMPORT: private import std.math;
// D_IMPORT: private import opengl;
// D_IMPORT: private import abagames.util.actor;
// D_IMPORT: private import abagames.util.vector;
// D_IMPORT: private import abagames.gr.ship;
// D_IMPORT: private import abagames.gr.screen;
// D_IMPORT: private import abagames.gr.shape;

/**
 * Bonus crystals.
 */
export class Crystal extends Actor {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly COUNT: number = 60;
  static readonly PULLIN_COUNT: number = /* D_CAST(int) */ (COUNT * 0.8);
  static _shape: CrystalShape;
  ship: Ship;
  pos: Vector;
  vel: Vector;
  cnt: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public static init(): void {
    Crystal._shape = new CrystalShape();
  }

  public static close(): void {
    Crystal._shape.close();
  }

  public constructor() {
    this.pos = new Vector();
    this.vel = new Vector();
  }

  public override init(args: unknown[]): void {
    this.ship = /* D_CAST(Ship) */ args[0];
  }

  public set(p: Vector): void {
    this.pos.x = p.x;
    this.pos.y = p.y;
    this.cnt = Crystal.COUNT;
    this.vel.x = 0;
    this.vel.y = 0.1;
    exists = true;
  }

  public override move(): void {
    this.cnt--;
    let dist: number = this.pos.dist(this.ship.midstPos);
    if (dist < 0.1)
      dist = 0.1;
    if (this.cnt < Crystal.PULLIN_COUNT) {
      this.vel.x += (this.ship.midstPos.x - this.pos.x) / dist * 0.07;
      this.vel.y += (this.ship.midstPos.y - this.pos.y) / dist * 0.07;
      if (this.cnt < 0 || dist < 2) {
        exists = false;
        return;
      }
    }
    this.vel *= 0.95;
    this.pos += this.vel;
  }

  public override draw(): void {
    let r: number = 0.25;
    let d: number = this.cnt * 0.1;
    if (this.cnt > Crystal.PULLIN_COUNT)
      r *= (/* D_CAST(float) */ (Crystal.COUNT - this.cnt)) / (Crystal.COUNT - Crystal.PULLIN_COUNT);
    for (let i = 0; i < 4; i++) {
      glPushMatrix();
      glTranslatef(this.pos.x + sin(d) * r, this.pos.y + cos(d) * r, 0);
      Crystal._shape.draw();
      glPopMatrix();
      d += PI / 2;
    }
  }
}

export class CrystalPool extends ActorPool<Crystal> {
  public constructor(n: number, args: unknown[]) {
    super(n, args);
  }
}
