// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: enemy.d,v 1.2 2005/07/17 11:02:45 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.enemy;

// D_IMPORT: private import std.math;
// D_IMPORT: private import opengl;
// D_IMPORT: private import abagames.util.vector;
// D_IMPORT: private import abagames.util.actor;
// D_IMPORT: private import abagames.util.rand;
// D_IMPORT: private import abagames.util.math;
// D_IMPORT: private import abagames.util.sdl.shape;
// D_IMPORT: private import abagames.gr.field;
// D_IMPORT: private import abagames.gr.bullet;
// D_IMPORT: private import abagames.gr.ship;
// D_IMPORT: private import abagames.gr.stagemanager;
// D_IMPORT: private import abagames.gr.screen;
// D_IMPORT: private import abagames.gr.particle;
// D_IMPORT: private import abagames.gr.shot;
// D_IMPORT: private import abagames.gr.shape;
// D_IMPORT: private import abagames.gr.soundmanager;
// D_IMPORT: private import abagames.gr.gamemanager;
// D_IMPORT: private import abagames.gr.turret;
// D_IMPORT: private import abagames.gr.letter;
// D_IMPORT: private import abagames.gr.reel;

/**
 * Enemy ships.
 */
export class Enemy extends Actor {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  spec: EnemySpec;
  _state: EnemyState;

  public override init(args: unknown[]): void {
    this._state = new EnemyState
      (/* D_CAST(Field) */ args[0], /* D_CAST(Screen) */ args[1],
       /* D_CAST(BulletPool) */ args[2], /* D_CAST(Ship) */ args[3],
       /* D_CAST(SparkPool) */ args[4], /* D_CAST(SmokePool) */ args[5],
       /* D_CAST(FragmentPool) */ args[6], /* D_CAST(SparkFragmentPool) */ args[7],
       /* D_CAST(NumIndicatorPool) */ args[8], /* D_CAST(ScoreReel) */ args[9]);
  }

  public setEnemyPool(enemies: EnemyPool): void {
    this._state.setEnemyAndPool(this, enemies);
  }

  public setStageManager(stageManager: StageManager): void {
    this._state.setStageManager(stageManager);
  }

  public set(spec: EnemySpec): void {
    this.spec = spec;
    exists = true;
  }

  public override move(): void {
    if (!this.spec.move(state))
      this.remove();
  }

  public checkShotHit(p: Vector, shape: Collidable, shot: Shot): void {
    if (this._state.destroyedCnt >= 0)
      return;
    if (this.spec.checkCollision(this._state, p.x, p.y, shape, shot)) {
      if (shot)
        shot.removeHitToEnemy(this.spec.isSmallEnemy);
    }
  }

  public checkHitShip(x: number, y: number, largeOnly: boolean = false): boolean {
    return this.spec.checkShipCollision(this._state, x, y, largeOnly);
  }

  public addDamage(n: number): void {
    this._state.addDamage(n);
  }

  public increaseMultiplier(m: number): void {
    this._state.increaseMultiplier(m);
  }

  public addScore(s: number): void {
    this._state.addScore(s);
  }

  public remove(): void {
    this._state.removeTurrets();
    exists = false;
  }

  public override draw(): void {
    this.spec.draw(this._state);
  }

  public state(): EnemyState {
    return this._state;
  }

  public pos(): Vector {
    return this._state.pos;
  }

  public size(): number {
    return this.spec.size;
  }

  public index(): number {
    return this._state.idx;
  }

  public isBoss(): boolean {
    return this.spec.isBoss;
  }
}

/**
 * Enemy status (position, direction, velocity, turrets, etc).
 */
export class EnemyState {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly AppearanceType = {
    TOP: 0,
    SIDE: 1,
    CENTER: 2
  } as const;
  static readonly TURRET_GROUP_MAX: number = 10;
  static readonly MOVING_TURRET_GROUP_MAX: number = 4;
  static readonly MULTIPLIER_DECREASE_RATIO: number = 0.005;
  appType: number;
  pos: Vector;
  ppos: Vector;
  shield: number;
  deg: number;
  velDeg: number;
  speed: number;
  turnWay: number;
  trgDeg: number;
  turnCnt: number;
  state: number;
  cnt: number;
  vel: Vector;
  turretGroup: TurretGroup[];
  movingTurretGroup: MovingTurretGroup[];
  damaged: boolean;
  damagedCnt: number;
  destroyedCnt: number;
  explodeCnt: number;
  explodeItv: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: int explodeCnt, explodeItv;
  idx: number;
  multiplier: number;
  spec: EnemySpec;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static rand: Rand;
  static edgePos: Vector;
  static explodeVel: Vector;
  static damagedPos: Vector;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: static Vector edgePos, explodeVel, damagedPos;
  static idxCount: number = 0;
  field: Field;
  screen: Screen;
  bullets: BulletPool;
  ship: Ship;
  sparks: SparkPool;
  smokes: SmokePool;
  fragments: FragmentPool;
  sparkFragments: SparkFragmentPool;
  numIndicators: NumIndicatorPool;
  enemy: Enemy;
  enemies: EnemyPool;
  stageManager: StageManager;
  scoreReel: ScoreReel;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  static {
    rand = new Rand();
    edgePos = new Vector();
    explodeVel = new Vector();
    damagedPos = new Vector();
  }

  public static setRandSeed(seed: number): void {
    EnemyState.rand.setSeed(seed);
  }

  public constructor(field: Field, screen: Screen, bullets: BulletPool, ship: Ship, sparks: SparkPool, smokes: SmokePool, fragments: FragmentPool, sparkFragments: SparkFragmentPool, numIndicators: NumIndicatorPool, scoreReel: ScoreReel) {
    this.idx = EnemyState.idxCount;
    EnemyState.idxCount++;
    this.field = field;
    this.screen = screen;
    this.bullets = bullets;
    this.ship = ship;
    this.sparks = sparks;
    this.smokes = smokes;
    this.fragments = fragments;
    this.sparkFragments = sparkFragments;
    this.numIndicators = numIndicators;
    this.scoreReel = scoreReel;
    this.pos = new Vector();
    this.ppos = new Vector();
    this.vel = new Vector();
    this.deg = this.velDeg = this.speed = 0;
    this.turnWay = 1;
    this.explodeItv = 1;
    this.multiplier = 1;
    this.trgDeg = 0;
    this.turnCnt = 0;
  }

  public setEnemyAndPool(enemy: Enemy, enemies: EnemyPool): void {
    this.enemy = enemy;
    this.enemies = enemies;
    for (const tg of this.turretGroup)
      tg = new TurretGroup(this.field, this.bullets, this.ship, this.sparks, this.smokes, this.fragments, enemy);
    for (const tg of this.movingTurretGroup)
      tg = new MovingTurretGroup(this.field, this.bullets, this.ship, this.sparks, this.smokes, this.fragments, enemy);
  }

  public setStageManager(stageManager: StageManager): void {
    this.stageManager = stageManager;
  }

  public setSpec(spec: EnemySpec): void {
    this.spec = spec;
    this.shield = spec.shield;
    for (let i = 0; i < spec.turretGroupNum; i++)
      this.turretGroup[i].set(spec.turretGroupSpec[i]);
    for (let i = 0; i < spec.movingTurretGroupNum; i++)
      this.movingTurretGroup[i].set(spec.movingTurretGroupSpec[i]);
    this.cnt = 0;
    this.damaged = false;
    this.damagedCnt = 0;
    this.destroyedCnt = -1;
    this.explodeCnt = 0;
    this.explodeItv = 1;
    this.multiplier = 1;
  }

  public setAppearancePos(field: Field, ship: Ship, rand: Rand, appType: number = AppearanceType.TOP): boolean {
    this.appType = appType;
    for (let i = 0 ; i < 8 ; i++) {
      switch (appType) {
      case AppearanceType.TOP:
        this.pos.x = rand.nextSignedFloat(field.size.x);
        this.pos.y = field.outerSize.y * 0.99 + this.spec.size;
        if (this.pos.x < 0)
          this.velDeg = this.deg = PI - rand.nextFloat(0.5);
        else
          this.velDeg = this.deg = PI + rand.nextFloat(0.5);
        break;
      case AppearanceType.SIDE:
        if (rand.nextInt(2) == 0) {
          this.pos.x = -field.outerSize.x * 0.99;
          this.velDeg = this.deg = PI / 2 + rand.nextFloat(0.66);
        } else {
          this.pos.x = field.outerSize.x * 0.99;
          this.velDeg = this.deg = -PI / 2 - rand.nextFloat(0.66);
        }
        this.pos.y = field.size.y + rand.nextFloat(field.size.y) + this.spec.size;
        break;
      case AppearanceType.CENTER:
        this.pos.x = 0;
        this.pos.y = field.outerSize.y * 0.99 + this.spec.size;
        this.velDeg = this.deg = 0;
        break;
      }
      this.ppos.x = this.pos.x;
      this.ppos.y = this.pos.y;
      this.vel.x = this.vel.y = 0;
      this.speed = 0;
      if (appType == AppearanceType.CENTER || this.checkFrontClear(true))
        return true;
    }
    return false;
  }

  public checkFrontClear(checkCurrentPos: boolean = false): boolean {
    let si: number = 1;
    if (checkCurrentPos)
      si = 0;
    for (let i = si; i < 5; i++) {
      let cx: number = this.pos.x + sin(this.deg) * i * this.spec.size;
      let cy: number = this.pos.y + cos(this.deg) * i * this.spec.size;
      if (this.field.getBlock(cx, cy) >= 0)
        return false;
      if (this.enemies.checkHitShip(cx, cy, this.enemy, true))
        return false;
    }
    return true;
  }

  public move(): boolean {
    this.ppos.x = this.pos.x;
    this.ppos.y = this.pos.y;
    this.multiplier -= EnemyState.MULTIPLIER_DECREASE_RATIO;
    if (this.multiplier < 1)
      this.multiplier = 1;
    if (this.destroyedCnt >= 0) {
      this.destroyedCnt++;
      this.explodeCnt--;
      if (this.explodeCnt < 0) {
        this.explodeItv += 2;
        this.explodeItv = /* D_CAST(int) */ (/* D_CAST(float) */ this.explodeItv * (1.2 + EnemyState.rand.nextFloat(1)));
        this.explodeCnt = this.explodeItv;
        this.destroyedEdge(/* D_CAST(int) */ (sqrt(this.spec.size) * 27.0 / (this.explodeItv * 0.1 + 1)));
      }
    }
    this.damaged = false;
    if (this.damagedCnt > 0)
      this.damagedCnt--;
    let alive: boolean = false;
    for (let i = 0; i < this.spec.turretGroupNum; i++)
      alive |= this.turretGroup[i].move(this.pos, this.deg);
    for (let i = 0; i < this.spec.movingTurretGroupNum; i++)
      this.movingTurretGroup[i].move(this.pos, this.deg);
    if (this.destroyedCnt < 0 && !alive)
      return this.destroyed();
    return true;
  }

  public checkCollision(x: number, y: number, c: Collidable, shot: Shot): boolean {
    let ox: number = fabs(this.pos.x - x), oy = fabs(this.pos.y - y);
    if (ox + oy > this.spec.size * 2)
      return false;
    for (let i = 0; i < this.spec.turretGroupNum; i++)
      if (this.turretGroup[i].checkCollision(x, y, c, shot))
        return true;
    if (this.spec.bridgeShape.checkCollision(ox, oy, c)) {
      this.addDamage(shot.damage, shot);
      return true;
    }
    return false;
  }

  public increaseMultiplier(m: number): void {
    this.multiplier += m;
  }

  public addScore(s: number): void {
    this.setScoreIndicator(s, 1);
  }

  public addDamage(n: number, shot: Shot = null): void {
    this.shield -= n;
    if (this.shield <= 0) {
      this.destroyed(shot);
    } else {
      this.damaged = true;
      this.damagedCnt = 7;
    }
  }

  public destroyed(shot: Shot = null): boolean {
    let vz: number;
    if (shot) {
      EnemyState.explodeVel.x = Shot.SPEED * sin(shot.deg) / 2;
      EnemyState.explodeVel.y = Shot.SPEED * cos(shot.deg) / 2;
      vz = 0;
    } else {
      EnemyState.explodeVel.x = EnemyState.explodeVel.y = 0;
      vz = 0.05;
    }
    let ss: number = this.spec.size * 1.5;
    if (ss > 2)
      ss = 2;
    let sn: number;
    if (this.spec.size < 1)
      sn = this.spec.size;
    else
      sn = sqrt(this.spec.size);
    assert(!Number.isNaN(sn) && !Number.isNaN(0));
    if (sn > 3)
      sn = 3;
    for (let i = 0; i < sn * 8; i++) {
      let s: Smoke = this.smokes.getInstanceForced();
      s.set(this.pos, EnemyState.rand.nextSignedFloat(0.1) + EnemyState.explodeVel.x, EnemyState.rand.nextSignedFloat(0.1) + EnemyState.explodeVel.y,
            EnemyState.rand.nextFloat(vz),
            Smoke.SmokeType.EXPLOSION, 32 + EnemyState.rand.nextInt(30), ss);
    }
    for (let i = 0; i < sn * 36; i++) {
      let sp: Spark = this.sparks.getInstanceForced();
      sp.set(this.pos, EnemyState.rand.nextSignedFloat(0.8) + EnemyState.explodeVel.x, EnemyState.rand.nextSignedFloat(0.8) + EnemyState.explodeVel.y,
             0.5 + EnemyState.rand.nextFloat(0.5), 0.5 + EnemyState.rand.nextFloat(0.5), 0, 30 + EnemyState.rand.nextInt(30));
    }
    for (let i = 0; i < sn * 12; i++) {
      let f: Fragment = this.fragments.getInstanceForced();
      f.set(this.pos, EnemyState.rand.nextSignedFloat(0.33) + EnemyState.explodeVel.x, EnemyState.rand.nextSignedFloat(0.33) + EnemyState.explodeVel.y,
            0.05 + EnemyState.rand.nextFloat(0.1),
            0.2 + EnemyState.rand.nextFloat(0.33));
    }
    this.removeTurrets();
    let sc: number = this.spec.score;
    let r: boolean;
    if (this.spec.type == EnemySpec.EnemyType.SMALL) {
      SoundManager.playSe("small_destroyed.wav");
      r = false;
    } else {
      SoundManager.playSe("destroyed.wav");
      let bn: number = this.bullets.removeIndexedBullets(this.idx);
      this.destroyedCnt = 0;
      this.explodeCnt = 1;
      this.explodeItv = 3;
      sc += bn * 10;
      r = true;
      if (this.spec.isBoss)
        this.screen.setScreenShake(45, 0.04);
    }
    this.setScoreIndicator(sc, this.multiplier);
    return r;
  }

  private setScoreIndicator(sc: number, mp: number): void {
    let ty: number = NumIndicator.getTargetY();
    if (mp > 1) {
      let ni: NumIndicator = this.numIndicators.getInstanceForced();
      ni.set(sc, NumIndicator.IndicatorType.SCORE, 0.5, this.pos);
      ni.addTarget(8, ty, NumIndicator.FlyingToType.RIGHT, 1, 0.5, sc, 40);
      ni.addTarget(11, ty, NumIndicator.FlyingToType.RIGHT, 0.5, 0.75,
                   /* D_CAST(int) */ (sc * mp), 30);
      ni.addTarget(13, ty, NumIndicator.FlyingToType.RIGHT, 0.25, 1,
                   /* D_CAST(int) */ (sc * mp * stageManager.rankMultiplier), 20);
      ni.addTarget(12, -8, NumIndicator.FlyingToType.BOTTOM, 0.5, 0.1,
                   /* D_CAST(int) */ (sc * mp * stageManager.rankMultiplier), 40);
      ni.gotoNextTarget();
      ni = this.numIndicators.getInstanceForced();
      let mn: number = /* D_CAST(int) */ (mp * 1000);
      ni.set(mn, NumIndicator.IndicatorType.MULTIPLIER, 0.7, this.pos);
      ni.addTarget(10.5, ty, NumIndicator.FlyingToType.RIGHT, 0.5, 0.2, mn, 70);
      ni.gotoNextTarget();
      ni = this.numIndicators.getInstanceForced();
      let rn: number = /* D_CAST(int) */ (this.stageManager.rankMultiplier * 1000);
      ni.set(rn, NumIndicator.IndicatorType.MULTIPLIER, 0.4, 11, 8);
      ni.addTarget(13, ty, NumIndicator.FlyingToType.RIGHT, 0.5, 0.2, rn, 40);
      ni.gotoNextTarget();
      this.scoreReel.addActualScore(/* D_CAST(int) */ (sc * mp * this.stageManager.rankMultiplier));
    } else {
      let ni: NumIndicator = this.numIndicators.getInstanceForced();
      ni.set(sc, NumIndicator.IndicatorType.SCORE, 0.3, this.pos);
      ni.addTarget(11, ty, NumIndicator.FlyingToType.RIGHT, 1.5, 0.2, sc, 40);
      ni.addTarget(13, ty, NumIndicator.FlyingToType.RIGHT, 0.25, 0.25,
                   /* D_CAST(int) */ (sc * stageManager.rankMultiplier), 20);
      ni.addTarget(12, -8, NumIndicator.FlyingToType.BOTTOM, 0.5, 0.1,
                   /* D_CAST(int) */ (sc * stageManager.rankMultiplier), 40);
      ni.gotoNextTarget();
      ni = this.numIndicators.getInstanceForced();
      let rn: number = /* D_CAST(int) */ (this.stageManager.rankMultiplier * 1000);
      ni.set(rn, NumIndicator.IndicatorType.MULTIPLIER, 0.4, 11, 8);
      ni.addTarget(13, ty, NumIndicator.FlyingToType.RIGHT, 0.5, 0.2, rn, 40);
      ni.gotoNextTarget();
      this.scoreReel.addActualScore(/* D_CAST(int) */ (sc * this.stageManager.rankMultiplier));
    }
  }

  public destroyedEdge(n: number): void {
    SoundManager.playSe("explode.wav");
    let sn: number = n;
    if (sn > 48)
      sn = 48;
    let spp: Vector[] = (/* D_CAST(BaseShape) */ this.spec.shape.shape).pointPos;
    let spd: number[] = (/* D_CAST(BaseShape) */this.spec.shape.shape).pointDeg;
    let si: number = EnemyState.rand.nextInt(spp.length);
    EnemyState.edgePos.x = spp[si].x * this.spec.size + this.pos.x;
    EnemyState.edgePos.y = spp[si].y * this.spec.size + this.pos.y;
    let ss: number = this.spec.size * 0.5;
    if (ss > 1)
      ss = 1;
    for (let i = 0; i < sn; i++) {
      let s: Smoke = this.smokes.getInstanceForced();
      let sr: number = EnemyState.rand.nextFloat(0.5);
      let sd: number = spd[si] + EnemyState.rand.nextSignedFloat(0.2);
      assert(!Number.isNaN(sd) && !Number.isNaN(0));
      s.set(EnemyState.edgePos, sin(sd) * sr, cos(sd) * sr, -0.004,
            Smoke.SmokeType.EXPLOSION, 75 + EnemyState.rand.nextInt(25), ss);
      for (let j = 0; j < 2; j++) {
        let sp: Spark = this.sparks.getInstanceForced();
        sp.set(EnemyState.edgePos, sin(sd) * sr * 2, cos(sd) * sr * 2,
               0.5 + EnemyState.rand.nextFloat(0.5), 0.5 + EnemyState.rand.nextFloat(0.5), 0, 30 + EnemyState.rand.nextInt(30));
      }
      if (i % 2 == 0) {
        let sf: SparkFragment = this.sparkFragments.getInstanceForced();
        sf.set(EnemyState.edgePos, sin(sd) * sr * 0.5, cos(sd) * sr * 0.5, 0.06 + EnemyState.rand.nextFloat(0.07),
               (0.2 + EnemyState.rand.nextFloat(0.1)));
      }
    }
  }

  public removeTurrets(): void {
    for (let i = 0; i < this.spec.turretGroupNum; i++)
      this.turretGroup[i].remove();
    for (let i = 0; i < this.spec.movingTurretGroupNum; i++)
      this.movingTurretGroup[i].remove();
  }

  public draw(): void {
    glPushMatrix();
    if (this.destroyedCnt < 0 && this.damagedCnt > 0) {
      EnemyState.damagedPos.x = this.pos.x + EnemyState.rand.nextSignedFloat(this.damagedCnt * 0.01);
      EnemyState.damagedPos.y = this.pos.y + EnemyState.rand.nextSignedFloat(this.damagedCnt * 0.01);
      Screen.glTranslate(EnemyState.damagedPos);
    } else {
      Screen.glTranslate(this.pos);
    }
    glRotatef(-this.deg * 180 / PI, 0, 0, 1);
    if (this.destroyedCnt >= 0)
      this.spec.destroyedShape.draw();
    else if (!this.damaged)
      this.spec.shape.draw();
    else
      this.spec.damagedShape.draw();
    if (this.destroyedCnt < 0)
      this.spec.bridgeShape.draw();
    glPopMatrix();
    if (this.destroyedCnt >= 0)
      return;
    for (let i = 0; i < this.spec.turretGroupNum; i++)
      this.turretGroup[i].draw();
    if (this.multiplier > 1) {
      let ox: number;
      let oy: number;
      // PORT_NOTE[D2TS:multi-decl]:
      // reason: Split D multi-variable declaration into one-per-line.
      // original: float ox, oy;
      if (this.multiplier < 10)
        ox = 2.1;
      else
        ox = 1.4;
      oy = 1.25;
      if(this.spec.isBoss) {
        ox += 4;
        oy -= 1.25;
      }
      Letter.drawNumSign(/* D_CAST(int) */ (this.multiplier * 1000),
                         this.pos.x + ox, this.pos.y + oy, 0.33, 1, 33, 3);
    }
  }
}

/**
 * Base class for a specification of an enemy.
 */
export class EnemySpec {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly EnemyType = {
    SMALL: 0,
    LARGE: 1,
    PLATFORM: 2
  } as const;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: protected:
  static rand: Rand;
  field: Field;
  ship: Ship;
  sparks: SparkPool;
  smokes: SmokePool;
  fragments: FragmentPool;
  wakes: WakePool;
  shield: number;
  _size: number;
  distRatio: number;
  turretGroupSpec: TurretGroupSpec[];
  turretGroupNum: number;
  movingTurretGroupSpec: MovingTurretGroupSpec[];
  movingTurretGroupNum: number;
  shape: EnemyShape;
  damagedShape: EnemyShape;
  destroyedShape: EnemyShape;
  bridgeShape: EnemyShape;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: EnemyShape shape, damagedShape, destroyedShape, bridgeShape;
  type: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  static {
    rand = new Rand();
  }

  public static setRandSeed(seed: number): void {
    EnemySpec.rand.setSeed(seed);
  }

  public constructor(field: Field, ship: Ship, sparks: SparkPool, smokes: SmokePool, fragments: FragmentPool, wakes: WakePool) {
    this.field = field;
    this.ship = ship;
    this.sparks = sparks;
    this.smokes = smokes;
    this.fragments = fragments;
    this.wakes = wakes;
    for (const tgs of this.turretGroupSpec)
      tgs = new TurretGroupSpec();
    for (const tgs of this.movingTurretGroupSpec)
      tgs = new MovingTurretGroupSpec();
    this.distRatio = 0;
    this.shield = 1;
    this._size = 1;
  }

  public set(type: number): void {
    this.type = type;
    this._size = 1;
    this.distRatio = 0;
    this.turretGroupNum = this.movingTurretGroupNum = 0;
  }

  public getTurretGroupSpec(): TurretGroupSpec {
    this.turretGroupNum++;
    this.turretGroupSpec[this.turretGroupNum - 1].init();
    return this.turretGroupSpec[this.turretGroupNum - 1];
  }

  public getMovingTurretGroupSpec(): MovingTurretGroupSpec {
    this.movingTurretGroupNum++;
    this.movingTurretGroupSpec[this.movingTurretGroupNum - 1].init();
    return this.movingTurretGroupSpec[this.movingTurretGroupNum - 1];
  }

  protected addMovingTurret(rank: number, bossMode: boolean = false): void {
    let mtn: number = /* D_CAST(int) */ (rank * 0.2);
    if (mtn > EnemyState.MOVING_TURRET_GROUP_MAX)
      mtn = EnemyState.MOVING_TURRET_GROUP_MAX;
    if (mtn >= 2)
      mtn = 1 + EnemySpec.rand.nextInt(mtn - 1);
    else
      mtn = 1;
    let br: number = rank / mtn;
    let type: number;
    if (!bossMode) {
      switch (EnemySpec.rand.nextInt(4)) {
      case 0:
      case 1:
        type = MovingTurretGroupSpec.MoveType.ROLL;
        break;
      case 2:
        type = MovingTurretGroupSpec.MoveType.SWING_FIX;
        break;
      case 3:
        type = MovingTurretGroupSpec.MoveType.SWING_AIM;
        break;
      }
    } else {
      type = MovingTurretGroupSpec.MoveType.ROLL;
    }
    let rad: number = 0.9 + EnemySpec.rand.nextFloat(0.4) - mtn * 0.1;
    let radInc: number = 0.5 + EnemySpec.rand.nextFloat(0.25);
    let ad: number = PI * 2;
    let a: number;
    let av: number;
    let dv: number;
    let s: number;
    let sv: number;
    // PORT_NOTE[D2TS:multi-decl]:
    // reason: Split D multi-variable declaration into one-per-line.
    // original: float a, av, dv, s, sv;
    switch (type) {
    case MovingTurretGroupSpec.MoveType.ROLL:
      a = 0.01 + EnemySpec.rand.nextFloat(0.04);
      av = 0.01 + EnemySpec.rand.nextFloat(0.03);
      dv = 0.01 + EnemySpec.rand.nextFloat(0.04);
      break;
    case MovingTurretGroupSpec.MoveType.SWING_FIX:
      ad = PI / 10 + EnemySpec.rand.nextFloat(PI / 15);
      s = 0.01 + EnemySpec.rand.nextFloat(0.02);
      sv = 0.01 + EnemySpec.rand.nextFloat(0.03);
      break;
    case MovingTurretGroupSpec.MoveType.SWING_AIM:
      ad = PI / 10 + EnemySpec.rand.nextFloat(PI / 15);
      if (EnemySpec.rand.nextInt(5) == 0)
        s = 0.01 + EnemySpec.rand.nextFloat(0.01);
      else
        s = 0;
      sv = 0.01 + EnemySpec.rand.nextFloat(0.02);
      break;
    }
    for (let i = 0; i < mtn; i++) {
      let tgs: MovingTurretGroupSpec = this.getMovingTurretGroupSpec();
      tgs.moveType = type;
      tgs.radiusBase = rad;
      let sr: number;
      switch (type) {
      case MovingTurretGroupSpec.MoveType.ROLL:
        tgs.alignDeg = ad;
        tgs.num = 4 + EnemySpec.rand.nextInt(6);
        if (EnemySpec.rand.nextInt(2) == 0) {
          if (EnemySpec.rand.nextInt(2) == 0)
            tgs.setRoll(dv, 0, 0);
          else
            tgs.setRoll(-dv, 0, 0);
        } else {
          if (EnemySpec.rand.nextInt(2) == 0)
            tgs.setRoll(0, a, av);
          else
            tgs.setRoll(0, -a, av);
        }
        if (EnemySpec.rand.nextInt(3) == 0)
          tgs.setRadiusAmp(1 + EnemySpec.rand.nextFloat(1), 0.01 + EnemySpec.rand.nextFloat(0.03));
        if (EnemySpec.rand.nextInt(2) == 0)
          tgs.distRatio = 0.8 + EnemySpec.rand.nextSignedFloat(0.3);
        sr = br / tgs.num;
        break;
      case MovingTurretGroupSpec.MoveType.SWING_FIX:
        tgs.num = 3 + EnemySpec.rand.nextInt(5);
        tgs.alignDeg = ad * (tgs.num * 0.1 + 0.3);
        if (EnemySpec.rand.nextInt(2) == 0)
          tgs.setSwing(s, sv);
        else
          tgs.setSwing(-s, sv);
        if (EnemySpec.rand.nextInt(6) == 0)
          tgs.setRadiusAmp(1 + EnemySpec.rand.nextFloat(1), 0.01 + EnemySpec.rand.nextFloat(0.03));
        if (EnemySpec.rand.nextInt(4) == 0)
          tgs.setAlignAmp(0.25 + EnemySpec.rand.nextFloat(0.25), 0.01 + EnemySpec.rand.nextFloat(0.02));
        sr = br / tgs.num;
        sr *= 0.6;
        break;
      case MovingTurretGroupSpec.MoveType.SWING_AIM:
        tgs.num = 3 + EnemySpec.rand.nextInt(4);
        tgs.alignDeg = ad * (tgs.num * 0.1 + 0.3);
        if (EnemySpec.rand.nextInt(2) == 0)
          tgs.setSwing(s, sv, true);
        else
          tgs.setSwing(-s, sv, true);
        if (EnemySpec.rand.nextInt(4) == 0)
          tgs.setRadiusAmp(1 + EnemySpec.rand.nextFloat(1), 0.01 + EnemySpec.rand.nextFloat(0.03));
        if (EnemySpec.rand.nextInt(5) == 0)
          tgs.setAlignAmp(0.25 + EnemySpec.rand.nextFloat(0.25), 0.01 + EnemySpec.rand.nextFloat(0.02));
        sr = br / tgs.num;
        sr *= 0.4;
        break;
      }
      if (EnemySpec.rand.nextInt(4) == 0)
        tgs.setXReverse(-1);
      tgs.turretSpec.setParam(sr, TurretSpec.TurretType.MOVING, EnemySpec.rand);
      if (bossMode)
        tgs.turretSpec.setBossSpec();
      rad += radInc;
      ad *= 1 + EnemySpec.rand.nextSignedFloat(0.2);
    }
  }

  public checkCollision(es: EnemyState, x: number, y: number, c: Collidable, shot: Shot): boolean {
    return es.checkCollision(x, y, c, shot);
  }

  public checkShipCollision(es: EnemyState, x: number, y: number, largeOnly: boolean = false): boolean {
    if (es.destroyedCnt >= 0 || (largeOnly && this.type != EnemyType.LARGE))
      return false;
    return this.shape.checkShipCollision(x - es.pos.x, y - es.pos.y, es.deg); 
  }

  public move(es: EnemyState): boolean {
    return es.move();
  }

  public draw(es: EnemyState): void {
    es.draw();
  }

  public size(): number {
    return this._size;
  }

  public size(v: number): number {
    this._size = v;
    if (this.shape)
      this.shape.size = this._size;
    if (this.damagedShape)
      this.damagedShape.size = this._size;
    if (this.destroyedShape)
      this.destroyedShape.size = this._size;
    if (this.bridgeShape) {
      let s: number = 0.9;
      this.bridgeShape.size = s * (1 - this.distRatio);
    }
    return this._size;
  }

  public isSmallEnemy(): boolean {
    if (this.type == EnemyType.SMALL)
      return true;
    else
      return false;
  }

  public abstract score(): number;
  public abstract isBoss(): boolean;
}

export interface HasAppearType {
  setFirstState(es: EnemyState, appType: number): boolean;
}

/**
 * Specification for a small class ship.
 */
export class SmallShipEnemySpec extends EnemySpec implements HasAppearType {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly MoveType = {
    STOPANDGO: 0,
    CHASE: 1
  } as const;
  static readonly MoveState = {
    STAYING: 0,
    MOVING: 1
  } as const;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  type: number;
  accel: number;
  maxSpeed: number;
  staySpeed: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float accel, maxSpeed, staySpeed;
  moveDuration: number;
  stayDuration: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: int moveDuration, stayDuration;
  speed: number;
  turnDeg: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float speed, turnDeg;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor(field: Field, ship: Ship, sparks: SparkPool, smokes: SmokePool, fragments: FragmentPool, wakes: WakePool) {
    super(field, ship, sparks, smokes, fragments, wakes);
    type = 0;
    accel = maxSpeed = staySpeed = 0;
    moveDuration = stayDuration = 1;
    speed = turnDeg = 0;
  }

  public setParam(rank: number, rand: Rand): void {
    set(EnemyType.SMALL);
    shape = new EnemyShape(EnemyShape.EnemyShapeType.SMALL);
    damagedShape = new EnemyShape(EnemyShape.EnemyShapeType.SMALL_DAMAGED);
    bridgeShape = new EnemyShape(EnemyShape.EnemyShapeType.SMALL_BRIDGE);
    type = rand.nextInt(2);
    let sr: number = rand.nextFloat(rank * 0.8);
    if (sr > 25)
      sr = 25;
    switch (type) {
    case MoveType.STOPANDGO:
      distRatio = 0.5;
      size = 0.47 + rand.nextFloat(0.1);
      accel = 0.5 - 0.5 / (2.0 + rand.nextFloat(rank));
      maxSpeed = 0.05 * (1.0 + sr);
      staySpeed = 0.03;
      moveDuration = 32 + rand.nextSignedInt(12);
      stayDuration = 32 + rand.nextSignedInt(12);
      break;
    case MoveType.CHASE:
      distRatio = 0.5;
      size = 0.5 + rand.nextFloat(0.1);
      speed = 0.036 * (1.0 + sr);
      turnDeg = 0.02 + rand.nextSignedFloat(0.04);
      break;
    }
    shield = 1;
    let tgs: TurretGroupSpec = getTurretGroupSpec();
    tgs.turretSpec.setParam(rank - sr * 0.5, TurretSpec.TurretType.SMALL, rand);
  }

  public setFirstState(es: EnemyState, appType: number): boolean {
    es.setSpec(this);
    if (!es.setAppearancePos(field, ship, rand, appType))
      return false;
    switch (type) {
    case MoveType.STOPANDGO:
      es.speed = 0;
      es.state = MoveState.MOVING;
      es.cnt = moveDuration;
      break;
    case MoveType.CHASE:
      es.speed = speed;
      break;
    }
    return true;
  }

  public move(es: EnemyState): boolean {
    if (!super.move(es))
      return false;
    switch (type) {
    case MoveType.STOPANDGO:
      es.pos.x += sin(es.velDeg) * es.speed;
      es.pos.y += cos(es.velDeg) * es.speed;
      es.pos.y -= field.lastScrollY;
      if  (es.pos.y <= -field.outerSize.y)
        return false;
      if (field.getBlock(es.pos) >= 0 || !field.checkInOuterHeightField(es.pos)) {
        es.velDeg += PI;
        es.pos.x += sin(es.velDeg) * es.speed * 2;
        es.pos.y += cos(es.velDeg) * es.speed * 2;
      }
      switch (es.state) {
      case MoveState.MOVING:
        es.speed += (maxSpeed - es.speed) * accel;
        es.cnt--;
        if (es.cnt <= 0) {
          es.velDeg = rand.nextFloat(PI * 2);
          es.cnt = stayDuration;
          es.state = MoveState.STAYING;
        }
        break;
      case MoveState.STAYING:
        es.speed += (staySpeed - es.speed) * accel;
        es.cnt--;
        if (es.cnt <= 0) {
          es.cnt = moveDuration;
          es.state = MoveState.MOVING;
        }
        break;
      }
      break;
    case MoveType.CHASE:
      es.pos.x += sin(es.velDeg) * speed;
      es.pos.y += cos(es.velDeg) * speed;
      es.pos.y -= field.lastScrollY;
      if  (es.pos.y <= -field.outerSize.y)
        return false;
      if (field.getBlock(es.pos) >= 0 || !field.checkInOuterHeightField(es.pos)) {
        es.velDeg += PI;
        es.pos.x += sin(es.velDeg) * es.speed * 2;
        es.pos.y += cos(es.velDeg) * es.speed * 2;
      }
      let ad: number;
      let shipPos: Vector = ship.nearPos(es.pos);
      if (shipPos.dist(es.pos) < 0.1)
        ad = 0;
      else
        ad = atan2(shipPos.x - es.pos.x, shipPos.y - es.pos.y);
      assert(!Number.isNaN(ad) && !Number.isNaN(0));
      let od: number = ad - es.velDeg;
      Math.normalizeDeg(od);
      if (od <= turnDeg && od >= -turnDeg)
        es.velDeg = ad;
      else if (od < 0)
        es.velDeg -= turnDeg;
      else
        es.velDeg += turnDeg;
      Math.normalizeDeg(es.velDeg);
      es.cnt++;
    }
    let od: number = es.velDeg - es.deg;
    Math.normalizeDeg(od);
    es.deg += od * 0.05;
    Math.normalizeDeg(es.deg);
    if (es.cnt % 6 == 0 && es.speed >= 0.03)
      shape.addWake(wakes, es.pos, es.deg, es.speed);
    return true;
  }

  public score(): number {
    return 50;
  }

  public isBoss(): boolean {
    return false;
  }
}

/**
 * Specification for a large/middle class ship.
 */
export class ShipEnemySpec extends EnemySpec implements HasAppearType {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly ShipClass = {
    MIDDLE: 0,
    LARGE: 1,
    BOSS: 2
  } as const;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly SINK_INTERVAL: number = 120;
  speed: number;
  degVel: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float speed, degVel;
  shipClass: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor(field: Field, ship: Ship, sparks: SparkPool, smokes: SmokePool, fragments: FragmentPool, wakes: WakePool) {
    super(field, ship, sparks, smokes, fragments, wakes);
    speed = degVel = 0;
  }

  public setParam(rank: number, cls: number, rand: Rand): void {
    shipClass = cls;
    set(EnemyType.LARGE);
    shape = new EnemyShape(EnemyShape.EnemyShapeType.MIDDLE);
    damagedShape = new EnemyShape(EnemyShape.EnemyShapeType.MIDDLE_DAMAGED);
    destroyedShape = new EnemyShape(EnemyShape.EnemyShapeType.MIDDLE_DESTROYED);
    bridgeShape = new EnemyShape(EnemyShape.EnemyShapeType.MIDDLE_BRIDGE);
    distRatio = 0.7;
    let mainTurretNum: number = 0, subTurretNum = 0;
    let movingTurretRatio: number = 0;
    let rk: number = rank;
    switch (cls) {
    case ShipClass.MIDDLE:
      let sz: number = 1.5 + rank / 15 + rand.nextFloat(rank / 15);
      let ms: number = 2 + rand.nextFloat(0.5);
      if (sz > ms)
        sz = ms;
      size = sz;
      speed = 0.015 + rand.nextSignedFloat(0.005);
      degVel = 0.005 + rand.nextSignedFloat(0.003);
      switch (rand.nextInt(3)) {
      case 0:
        mainTurretNum = /* D_CAST(int) */ (size * (1 + rand.nextSignedFloat(0.25)) + 1);
        break;
      case 1:
        subTurretNum = /* D_CAST(int) */ (size * 1.6 * (1 + rand.nextSignedFloat(0.5)) + 2);
        break;
      case 2:
        mainTurretNum = /* D_CAST(int) */ (size * (0.5 + rand.nextSignedFloat(0.12)) + 1);
        movingTurretRatio = 0.5 + rand.nextFloat(0.25);
        rk = rank * (1 - movingTurretRatio);
        movingTurretRatio *= 2;
        break;
      }
      break;
    case ShipClass.LARGE:
      let sz: number = 2.5 + rank / 24 + rand.nextFloat(rank / 24);
      let ms: number = 3 + rand.nextFloat(1);
      if (sz > ms)
        sz = ms;
      size = sz;
      speed = 0.01 + rand.nextSignedFloat(0.005);
      degVel = 0.003 + rand.nextSignedFloat(0.002);
      mainTurretNum = /* D_CAST(int) */ (size * (0.7 + rand.nextSignedFloat(0.2)) + 1);
      subTurretNum = /* D_CAST(int) */ (size * 1.6 * (0.7 + rand.nextSignedFloat(0.33)) + 2);
      movingTurretRatio = 0.25 + rand.nextFloat(0.5);
      rk = rank * (1 - movingTurretRatio);
      movingTurretRatio *= 3;
      break;
    case ShipClass.BOSS:
      let sz: number = 5 + rank / 30 + rand.nextFloat(rank / 30);
      let ms: number = 9 + rand.nextFloat(3);
      if (sz > ms)
        sz = ms;
      size = sz;
      speed = ship.scrollSpeedBase + 0.0025 + rand.nextSignedFloat(0.001);
      degVel = 0.003 + rand.nextSignedFloat(0.002);
      mainTurretNum = /* D_CAST(int) */ (size * 0.8 * (1.5 + rand.nextSignedFloat(0.4)) + 2);
      subTurretNum = /* D_CAST(int) */ (size * 0.8 * (2.4 + rand.nextSignedFloat(0.6)) + 2);
      movingTurretRatio = 0.2 + rand.nextFloat(0.3);
      rk = rank * (1 - movingTurretRatio);
      movingTurretRatio *= 2.5;
      break;
    }
    shield = /* D_CAST(int) */ (size * 10);
    if (cls == ShipClass.BOSS)
      shield *= 2.4;
    if (mainTurretNum + subTurretNum <= 0) {
      let tgs: TurretGroupSpec = getTurretGroupSpec();
      tgs.turretSpec.setParam(0, TurretSpec.TurretType.DUMMY, rand);
    } else {
      let subTurretRank: number = rk / (mainTurretNum * 3 + subTurretNum);
      let mainTurretRank: number = subTurretRank * 2.5;
      if (cls != ShipClass.BOSS) {
        let frontMainTurretNum: number = /* D_CAST(int) */ (mainTurretNum / 2 + 0.99);
        let rearMainTurretNum: number = mainTurretNum - frontMainTurretNum;
        if (frontMainTurretNum > 0) {
          let tgs: TurretGroupSpec = getTurretGroupSpec();
          tgs.turretSpec.setParam(mainTurretRank, TurretSpec.TurretType.MAIN, rand);
          tgs.num = frontMainTurretNum;
          tgs.alignType = TurretGroupSpec.AlignType.STRAIGHT;
          tgs.offset.y = -size * (0.9 + rand.nextSignedFloat(0.05));
        }
        if (rearMainTurretNum > 0) {
          let tgs: TurretGroupSpec = getTurretGroupSpec();
          tgs.turretSpec.setParam(mainTurretRank, TurretSpec.TurretType.MAIN, rand);
          tgs.num = rearMainTurretNum;
          tgs.alignType = TurretGroupSpec.AlignType.STRAIGHT;
          tgs.offset.y = size * (0.9 + rand.nextSignedFloat(0.05));
        } 
        let pts: TurretSpec;
        if (subTurretNum > 0) {
          let frontSubTurretNum: number = (subTurretNum + 2) / 4;
          let rearSubTurretNum: number = (subTurretNum - frontSubTurretNum * 2) / 2;
          let tn: number = frontSubTurretNum;
          let ad: number = -PI / 4;
          for (let i = 0; i < 4; i++) {
            if (i == 2)
              tn = rearSubTurretNum;
            if (tn <= 0)
              continue;
            let tgs: TurretGroupSpec = getTurretGroupSpec();
            if (i == 0 || i == 2) {
              if (rand.nextInt(2) == 0)
                tgs.turretSpec.setParam(subTurretRank, TurretSpec.TurretType.SUB, rand);
              else
                tgs.turretSpec.setParam(subTurretRank, TurretSpec.TurretType.SUB_DESTRUCTIVE, rand);
              pts = tgs.turretSpec;
            } else {
              tgs.turretSpec.setParam(pts);
            }
            tgs.num = tn;
            tgs.alignType = TurretGroupSpec.AlignType.ROUND;
            tgs.alignDeg = ad;
            ad += PI / 2;
            tgs.alignWidth = PI / 6 + rand.nextFloat(PI / 8);
            tgs.radius = size * 0.75;
            tgs.distRatio = distRatio;
          }
        }
      } else {
        mainTurretRank *= 2.5;
        subTurretRank *= 2;
        let pts: TurretSpec;
        if (mainTurretNum > 0) {
          let frontMainTurretNum: number = (mainTurretNum + 2) / 4;
          let rearMainTurretNum: number = (mainTurretNum - frontMainTurretNum * 2) / 2;
          let tn: number = frontMainTurretNum;
          let ad: number = -PI / 4;
          for (let i = 0; i < 4; i++) {
            if (i == 2)
              tn = rearMainTurretNum;
            if (tn <= 0)
              continue;
            let tgs: TurretGroupSpec = getTurretGroupSpec();
            if (i == 0 || i == 2) {
              tgs.turretSpec.setParam(mainTurretRank, TurretSpec.TurretType.MAIN, rand);
              pts = tgs.turretSpec;
              pts.setBossSpec();
            } else {
              tgs.turretSpec.setParam(pts);
            }
            tgs.num = tn;
            tgs.alignType = TurretGroupSpec.AlignType.ROUND;
            tgs.alignDeg = ad;
            ad += PI / 2;
            tgs.alignWidth = PI / 6 + rand.nextFloat(PI / 8);
            tgs.radius = size * 0.45;
            tgs.distRatio = distRatio;
          }
        }
        if (subTurretNum > 0) {
          let tn: number[];
          tn[0] = (subTurretNum + 2) / 6;
          tn[1] = (subTurretNum - tn[0] * 2) / 4;
          tn[2] = (subTurretNum - tn[0] * 2 - tn[1] * 2) / 2;
          let ad: number[] = [PI / 4, -PI / 4, PI / 2, -PI / 2, PI / 4 * 3, -PI / 4 * 3];
          for (let i = 0; i < 6; i++) {
            let idx: number = i / 2;
            if (tn[idx] <= 0)
              continue;
            let tgs: TurretGroupSpec = getTurretGroupSpec();
            if (i == 0 || i == 2 || i == 4) {
              if (rand.nextInt(2) == 0)
                tgs.turretSpec.setParam(subTurretRank, TurretSpec.TurretType.SUB, rand);
              else
                tgs.turretSpec.setParam(subTurretRank, TurretSpec.TurretType.SUB_DESTRUCTIVE, rand);
              pts = tgs.turretSpec;
              pts.setBossSpec();
            } else {
              tgs.turretSpec.setParam(pts);
            }
            tgs.num = tn[idx];
            tgs.alignType = TurretGroupSpec.AlignType.ROUND;
            tgs.alignDeg = ad[i];
            tgs.alignWidth = PI / 7 + rand.nextFloat(PI / 9);
            tgs.radius = size * 0.75;
            tgs.distRatio = distRatio;
          }
        }
      }
    }
    if (movingTurretRatio > 0) {
      if (cls == ShipClass.BOSS)
        addMovingTurret(rank * movingTurretRatio, true);
      else
        addMovingTurret(rank * movingTurretRatio);
    }
  }

  public setFirstState(es: EnemyState, appType: number): boolean {
    es.setSpec(this);
    if (!es.setAppearancePos(field, ship, rand, appType))
      return false;
    es.speed = speed;
    if (es.pos.x < 0)
      es.turnWay = -1;
    else
      es.turnWay = 1;
    if (isBoss) {
      es.trgDeg = rand.nextFloat(0.1) + 0.1;
      if (rand.nextInt(2) == 0)
        es.trgDeg *= -1;
      es.turnCnt = 250 + rand.nextInt(150);
    }
    return true;
  }

  public move(es: EnemyState): boolean {
    if (es.destroyedCnt >= SINK_INTERVAL)
      return false;
    if (!super.move(es))
      return false;
    es.pos.x += sin(es.deg) * es.speed;
    es.pos.y += cos(es.deg) * es.speed;
    es.pos.y -= field.lastScrollY;
    if  (es.pos.x <= -field.outerSize.x - size || es.pos.x >= field.outerSize.x + size ||
         es.pos.y <= -field.outerSize.y - size)
      return false;
    if (es.pos.y > field.outerSize.y * 2.2 + size)
      es.pos.y = field.outerSize.y * 2.2 + size;
    if (isBoss) {
      es.turnCnt--;
      if (es.turnCnt <= 0) {
        es.turnCnt = 250 + rand.nextInt(150);
        es.trgDeg = rand.nextFloat(0.1) + 0.2;
        if (es.pos.x > 0)
          es.trgDeg *= -1;
      }
      es.deg += (es.trgDeg - es.deg) * 0.0025;
      if (ship.higherPos.y > es.pos.y)
        es.speed += (speed * 2 - es.speed) * 0.005;
      else
        es.speed += (speed - es.speed) * 0.01;
    } else {
      if (!es.checkFrontClear()) {
        es.deg += degVel * es.turnWay;
        es.speed *= 0.98;
      } else {
        if (es.destroyedCnt < 0)
          es.speed += (speed - es.speed) * 0.01;
        else
          es.speed *= 0.98;
      }
    }
    es.cnt++;
    if (es.cnt % 6 == 0 && es.speed >= 0.01 && es.destroyedCnt < SINK_INTERVAL / 2)
      shape.addWake(wakes, es.pos, es.deg, es.speed);
    return true;
  }

  public override draw(es: EnemyState): void {
    if (es.destroyedCnt >= 0)
      Screen.setColor(
        EnemyShape.MIDDLE_COLOR_R * (1 - /* D_CAST(float) */ es.destroyedCnt / SINK_INTERVAL) * 0.5,
        EnemyShape.MIDDLE_COLOR_G * (1 - /* D_CAST(float) */ es.destroyedCnt / SINK_INTERVAL) * 0.5,
        EnemyShape.MIDDLE_COLOR_B * (1 - /* D_CAST(float) */ es.destroyedCnt / SINK_INTERVAL) * 0.5);
    super.draw(es);
  }

  public score(): number {
    switch (shipClass) {
    case ShipClass.MIDDLE:
      return 100;
    case ShipClass.LARGE:
      return 300;
    case ShipClass.BOSS:
      return 1000;
    }
  }

  public isBoss(): boolean {
    if (shipClass == ShipClass.BOSS)
      return true;
    return false;
  }
}

/**
 * Specification for a sea-based platform.
 */
export class PlatformEnemySpec extends EnemySpec {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:

  public constructor(field: Field, ship: Ship, sparks: SparkPool, smokes: SmokePool, fragments: FragmentPool, wakes: WakePool) {
    super(field, ship, sparks, smokes, fragments, wakes);
  }

  public setParam(rank: number, rand: Rand): void {
    set(EnemyType.PLATFORM);
    shape = new EnemyShape(EnemyShape.EnemyShapeType.PLATFORM);
    damagedShape = new EnemyShape(EnemyShape.EnemyShapeType.PLATFORM_DAMAGED);
    destroyedShape = new EnemyShape(EnemyShape.EnemyShapeType.PLATFORM_DESTROYED);
    bridgeShape = new EnemyShape(EnemyShape.EnemyShapeType.PLATFORM_BRIDGE);
    distRatio = 0;
    size = 1 + rank / 30 + rand.nextFloat(rank / 30);
    let ms: number = 1 + rand.nextFloat(0.25);
    if (size > ms)
      size = ms;
    let mainTurretNum: number = 0, frontTurretNum = 0, sideTurretNum = 0;
    let rk: number = rank;
    let movingTurretRatio: number = 0;
    switch (rand.nextInt(3)) {
    case 0:
      frontTurretNum = /* D_CAST(int) */ (size * (2 + rand.nextSignedFloat(0.5)) + 1);
      movingTurretRatio = 0.33 + rand.nextFloat(0.46);
      rk *= (1 - movingTurretRatio);
      movingTurretRatio *= 2.5;
      break;
    case 1:
      frontTurretNum = /* D_CAST(int) */ (size * (0.5 + rand.nextSignedFloat(0.2)) + 1);
      sideTurretNum = /* D_CAST(int) */ (size * (0.5 + rand.nextSignedFloat(0.2)) + 1) * 2;
      break;
    case 2:
      mainTurretNum = /* D_CAST(int) */ (size * (1 + rand.nextSignedFloat(0.33)) + 1);
      break;
    }
    shield = /* D_CAST(int) */ (size * 20);
    let subTurretNum: number = frontTurretNum + sideTurretNum;
    let subTurretRank: number = rk / (mainTurretNum * 3 + subTurretNum);
    let mainTurretRank: number = subTurretRank * 2.5;
    if (mainTurretNum > 0) {
      let tgs: TurretGroupSpec = getTurretGroupSpec();
      tgs.turretSpec.setParam(mainTurretRank, TurretSpec.TurretType.MAIN, rand);
      tgs.num = mainTurretNum;
      tgs.alignType = TurretGroupSpec.AlignType.ROUND;
      tgs.alignDeg = 0;
      tgs.alignWidth = PI * 0.66 + rand.nextFloat(PI / 2);
      tgs.radius = size * 0.7;
      tgs.distRatio = distRatio;
    }
    if (frontTurretNum > 0) {
      let tgs: TurretGroupSpec = getTurretGroupSpec();
      tgs.turretSpec.setParam(subTurretRank, TurretSpec.TurretType.SUB, rand);
      tgs.num = frontTurretNum;
      tgs.alignType = TurretGroupSpec.AlignType.ROUND;
      tgs.alignDeg = 0;
      tgs.alignWidth = PI / 5 + rand.nextFloat(PI / 6);
      tgs.radius = size * 0.8;
      tgs.distRatio = distRatio;
    }
    sideTurretNum /= 2;
    if (sideTurretNum > 0) {
      let pts: TurretSpec;
      for (let i = 0; i < 2; i++) {
        let tgs: TurretGroupSpec = getTurretGroupSpec();
        if (i == 0) {
          tgs.turretSpec.setParam(subTurretRank, TurretSpec.TurretType.SUB, rand);
          pts = tgs.turretSpec;
        } else {
          tgs.turretSpec.setParam(pts);
        }
        tgs.num = sideTurretNum;
        tgs.alignType = TurretGroupSpec.AlignType.ROUND;
        tgs.alignDeg = PI / 2 - PI * i;
        tgs.alignWidth = PI / 5 + rand.nextFloat(PI / 6);
        tgs.radius = size * 0.75;
        tgs.distRatio = distRatio;
      }
    }
    if (movingTurretRatio > 0) {
      addMovingTurret(rank * movingTurretRatio);
    }
  }

  public setFirstState(es: EnemyState, x: number, y: number, d: number): boolean {
    es.setSpec(this);
    es.pos.x = x;
    es.pos.y = y;
    es.deg = d;
    es.speed = 0;
    if (!es.checkFrontClear(true))
      return false;
    return true;
  }

  public move(es: EnemyState): boolean {
    if (!super.move(es))
      return false;
    es.pos.y -= field.lastScrollY;
    if  (es.pos.y <= -field.outerSize.y)
      return false;
    return true;
  }

  public score(): number {
    return 100;
  }

  public isBoss(): boolean {
    return false;
  }
}

export class EnemyPool extends ActorPool<Enemy> {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:

  public constructor(n: number, args: unknown[]) {
    super(n, args);
    for (const e of actor)
      e.setEnemyPool(this);
  }

  public setStageManager(stageManager: StageManager): void {
    for (const e of actor)
      e.setStageManager(stageManager);
  }

  public checkShotHit(pos: Vector, shape: Collidable, shot: Shot = null): void {
    for (const e of actor)
      if (e.exists)
        e.checkShotHit(pos, shape, shot);
  }

  public checkHitShip(x: number, y: number, deselection: Enemy = null, largeOnly: boolean = false): Enemy {
    for (const e of actor)
      if (e.exists && e != deselection)
        if (e.checkHitShip(x, y, largeOnly))
          return e;
    return null;
  }

  public hasBoss(): boolean {
    for (const e of actor)
      if (e.exists && e.isBoss)
        return true;
    return false;
  }
}
