// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: field.d,v 1.3 2005/09/11 00:47:40 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.field;

// D_IMPORT: private import opengl;
// D_IMPORT: private import std.math;
// D_IMPORT: private import abagames.util.vector;
// D_IMPORT: private import abagames.util.rand;
// D_IMPORT: private import abagames.util.math;
// D_IMPORT: private import abagames.util.sdl.displaylist;
// D_IMPORT: private import abagames.gr.screen;
// D_IMPORT: private import abagames.gr.stagemanager;
// D_IMPORT: private import abagames.gr.ship;

// PORT_NOTE[D2TS:struct]: D struct is converted to class for now.
export class PlatformPos {
  pos: Vector;
  deg: number;
  used: boolean;
}

export class Panel {
  x: number;
  y: number;
  z: number;
  ci: number;
  or: number;
  og: number;
  ob: number;
}

/**
 * Game field.
 */
export class Field {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly BLOCK_SIZE_X: number = 20;
  static readonly BLOCK_SIZE_Y: number = 64;
  static readonly ON_BLOCK_THRESHOLD: number = 1;
  static readonly NEXT_BLOCK_AREA_SIZE: number = 16;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly SIDEWALL_X1: number = 18;
  static readonly SIDEWALL_X2: number = 9.3;
  static readonly SIDEWALL_Y: number = 15;
  static readonly TIME_COLOR_INDEX: number = 5;
  static readonly TIME_CHANGE_RATIO: number = 0.00033;
  stageManager: StageManager;
  ship: Ship;
  rand: Rand;
  _size: Vector;
  _outerSize: Vector;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: Vector _size, _outerSize;
  readonly SCREEN_BLOCK_SIZE_X: number = 20;
  readonly SCREEN_BLOCK_SIZE_Y: number = 24;
  readonly BLOCK_WIDTH: number = 1;
  block: number[][];
  static readonly PANEL_WIDTH: number = 1.8;
  static readonly PANEL_HEIGHT_BASE: number = 0.66;
  panel: Panel[][];
  nextBlockY: number;
  screenY: number;
  blockCreateCnt: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float screenY, blockCreateCnt;
  _lastScrollY: number;
  screenPos: Vector;
  platformPos: PlatformPos[];
  platformPosNum: number;
  baseColorTime: number[][][] = [
    [[0.15, 0.15, 0.3], [0.25, 0.25, 0.5], [0.35, 0.35, 0.45],
     [0.6, 0.7, 0.35], [0.45, 0.8, 0.3], [0.2, 0.6, 0.1]],
    [[0.1, 0.1, 0.3], [0.2, 0.2, 0.5], [0.3, 0.3, 0.4],
     [0.5, 0.65, 0.35], [0.4, 0.7, 0.3], [0.1, 0.5, 0.1]],
    [[0.1, 0.1, 0.3], [0.2, 0.2, 0.5], [0.3, 0.3, 0.4],
     [0.5, 0.65, 0.35], [0.4, 0.7, 0.3], [0.1, 0.5, 0.1]],
    [[0.2, 0.15, 0.25], [0.35, 0.2, 0.4], [0.5, 0.35, 0.45],
     [0.7, 0.6, 0.3], [0.6, 0.65, 0.25], [0.2, 0.45, 0.1]],
    [[0.0, 0.0, 0.1], [0.1, 0.1, 0.3], [0.2, 0.2, 0.3],
     [0.2, 0.3, 0.15], [0.2, 0.2, 0.1], [0.0, 0.15, 0.0]],
    ];
  baseColor: number[][];
  time: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor() {
    this.rand = new Rand();
    this._size = new Vector(this.SCREEN_BLOCK_SIZE_X / 2 * 0.9, this.SCREEN_BLOCK_SIZE_Y / 2 * 0.8);
    this._outerSize = new Vector(this.SCREEN_BLOCK_SIZE_X / 2, this.SCREEN_BLOCK_SIZE_Y / 2);
    this.block = Array.from({ length: Field.BLOCK_SIZE_X }, () => Array(Field.BLOCK_SIZE_Y).fill(-3));
    this.panel = Array.from({ length: Field.BLOCK_SIZE_X }, () =>
      Array.from({ length: Field.BLOCK_SIZE_Y }, () => new Panel())
    );
    this.platformPos = Array.from(
      { length: this.SCREEN_BLOCK_SIZE_X * Field.NEXT_BLOCK_AREA_SIZE },
      () => {
        const pp = new PlatformPos();
        pp.pos = new Vector();
        pp.deg = 0;
        pp.used = false;
        return pp;
      }
    );
    this.baseColor = Array.from({ length: 6 }, () => Array(3).fill(0));
    this.screenPos = new Vector();
    this._lastScrollY = 0;
    this.platformPosNum = 0;
    this.time = 0;
  }

  public setRandSeed(s: number): void {
    this.rand.setSeed(s);
  }

  public setStageManager(sm: StageManager): void {
    this.stageManager = sm;
  }

  public setShip(sp: Ship): void {
    this.ship = sp;
  }

  public start(): void {
    this._lastScrollY = 0;
    this.nextBlockY = 0;
    this.screenY = Field.NEXT_BLOCK_AREA_SIZE;
    this.blockCreateCnt = 0;
    for (let y = 0; y < Field.BLOCK_SIZE_Y; y++) {
      for (let x = 0; x < Field.BLOCK_SIZE_X; x++) {
        this.block[x][y] = -3;
        this.createPanel(x, y);
      }
    }
    this.time = this.rand.nextFloat(Field.TIME_COLOR_INDEX);
  }

  private createPanel(x: number, y: number): void {
    const p = this.panel[x][y];
    p.x = this.rand.nextFloat(1) - 0.75;
    p.y = this.rand.nextFloat(1) - 0.75;
    p.z = this.block[x][y] * Field.PANEL_HEIGHT_BASE + this.rand.nextFloat(Field.PANEL_HEIGHT_BASE);
    p.ci = this.block[x][y] + 3;
    p.or = 1 + this.rand.nextSignedFloat(0.1);
    p.og = 1 + this.rand.nextSignedFloat(0.1);
    p.ob = 1 + this.rand.nextSignedFloat(0.1);
    p.or *= 0.33;
    p.og *= 0.33;
    p.ob *= 0.33;
  }

  public scroll(my: number, isDemo: boolean = false): void {
    this._lastScrollY = my;
    this.screenY -= my;
    if (this.screenY < 0)
      this.screenY += Field.BLOCK_SIZE_Y;
    this.blockCreateCnt -= my;
    if (this.blockCreateCnt < 0) {
      this.stageManager.gotoNextBlockArea();
      let bd: number;
      if (this.stageManager.bossMode)
        bd = 0;
      else
        bd = this.stageManager.blockDensity;
      this.createBlocks(bd);
      if (!isDemo) {
        this.stageManager.addBatteries(this.platformPos, this.platformPosNum);
      }
      this.gotoNextBlockArea();
    }
  }

  private createBlocks(groundDensity: number): void {
    for (let y = this.nextBlockY; y < this.nextBlockY + Field.NEXT_BLOCK_AREA_SIZE; y++) {
      let by: number = y % Field.BLOCK_SIZE_Y;
      for (let bx = 0; bx < Field.BLOCK_SIZE_X; bx++)
        this.block[bx][by] = -3;
    }
    this.platformPosNum = 0;
    let type: number = this.rand.nextInt(3);
    for (let i = 0; i < groundDensity; i++)
      this.addGround(type);
    for (let y = this.nextBlockY; y < this.nextBlockY + Field.NEXT_BLOCK_AREA_SIZE; y++) {
      let by: number = y % Field.BLOCK_SIZE_Y;
      for (let bx = 0; bx < Field.BLOCK_SIZE_X; bx++) {
        if (y == this.nextBlockY || y == this.nextBlockY + Field.NEXT_BLOCK_AREA_SIZE - 1)
          this.block[bx][by] = -3;
      }
    }
    for (let y = this.nextBlockY; y < this.nextBlockY + Field.NEXT_BLOCK_AREA_SIZE; y++) {
      let by: number = y % Field.BLOCK_SIZE_Y;
      for (let bx = 0; bx < Field.BLOCK_SIZE_X - 1; bx++) {
        if (this.block[bx][by] == 0)
          if (this.countAroundBlock(bx, by) <= 1)
            this.block[bx][by] = -2;
      }
      for (let bx = Field.BLOCK_SIZE_X - 1; bx >= 0; bx--) {
        if (this.block[bx][by] == 0)
          if (this.countAroundBlock(bx, by) <= 1)
            this.block[bx][by] = -2;
      }
      for (let bx = 0; bx < Field.BLOCK_SIZE_X; bx++) {
        let b: number;
        let c: number = this.countAroundBlock(bx, by);
        if (this.block[bx][by] >= 0) {
          switch (c) {
          case 0:
            b = -2;
            break;
          case 1:
          case 2:
          case 3:
            b = 0;
            break;
          case 4:
            b = 2;
            break;
          }
        } else {
          switch (c) {
          case 0:
            b = -3;
            break;
          case 1:
          case 2:
          case 3:
          case 4:
            b = -1;
            break;
          }
        }
        this.block[bx][by] = b;
        if (b == -1 && bx >= 2 && bx < Field.BLOCK_SIZE_X - 2) {
          let pd: number = this.calcPlatformDeg(bx, by);
          if (pd >= -PI * 2) {
            this.platformPos[this.platformPosNum].pos.x = bx;
            this.platformPos[this.platformPosNum].pos.y = by;
            this.platformPos[this.platformPosNum].deg = pd;
            this.platformPos[this.platformPosNum].used = false;
            this.platformPosNum++;
          }
        }
      }
    }
    for (let y = this.nextBlockY; y < this.nextBlockY + Field.NEXT_BLOCK_AREA_SIZE; y++) {
      let by: number = y % Field.BLOCK_SIZE_Y;
      for (let bx = 0; bx < Field.BLOCK_SIZE_X; bx++) {
        if (this.block[bx][by] == -3) {
          if (this.countAroundBlock(bx, by, -1) > 0)
            this.block[bx][by] = -2;
        } else if (this.block[bx][by] == 2) {
          if (this.countAroundBlock(bx, by, 1) < 4)
            this.block[bx][by] = 1;
        }
        this.createPanel(bx, by);
      }
    }
  }

  private addGround(type: number): void {
    let cx: number;
    switch (type) {
    case 0:
      cx = this.rand.nextInt(/* D_CAST(int) */ (Field.BLOCK_SIZE_X * 0.4)) + /* D_CAST(int) */ (Field.BLOCK_SIZE_X * 0.1);
      break;
    case 1:
      cx = this.rand.nextInt(/* D_CAST(int) */ (Field.BLOCK_SIZE_X * 0.4)) + /* D_CAST(int) */ (Field.BLOCK_SIZE_X * 0.5);
      break;
    case 2:
      if (this.rand.nextInt(2) == 0)
        cx = this.rand.nextInt(/* D_CAST(int) */ (Field.BLOCK_SIZE_X * 0.4)) - /* D_CAST(int) */ (Field.BLOCK_SIZE_X * 0.2);
      else
        cx = this.rand.nextInt(/* D_CAST(int) */ (Field.BLOCK_SIZE_X * 0.4)) + /* D_CAST(int) */ (Field.BLOCK_SIZE_X * 0.8);
      break;
    }
    let cy: number = this.rand.nextInt(/* D_CAST(int) */ (Field.NEXT_BLOCK_AREA_SIZE * 0.6)) + /* D_CAST(int) */ (Field.NEXT_BLOCK_AREA_SIZE * 0.2);
    cy += this.nextBlockY;
    let w: number = this.rand.nextInt(/* D_CAST(int) */ (Field.BLOCK_SIZE_X * 0.33)) + /* D_CAST(int) */ (Field.BLOCK_SIZE_X * 0.33);
    let h: number = this.rand.nextInt(/* D_CAST(int) */ (Field.NEXT_BLOCK_AREA_SIZE * 0.24)) + /* D_CAST(int) */ (Field.NEXT_BLOCK_AREA_SIZE * 0.33);
    cx -= w / 2;
    cy -= h / 2;
    let wr: number;
    let hr: number;
    // PORT_NOTE[D2TS:multi-decl]:
    // reason: Split D multi-variable declaration into one-per-line.
    // original: float wr, hr;
    for (let y = this.nextBlockY; y < this.nextBlockY + Field.NEXT_BLOCK_AREA_SIZE; y++) {
      let by: number = y % Field.BLOCK_SIZE_Y;
      for (let bx = 0; bx < Field.BLOCK_SIZE_X; bx++) {
        if (bx >= cx && bx < cx + w && y >= cy && y < cy + h) {
          let o: number;
          let to: number;
          // PORT_NOTE[D2TS:multi-decl]:
          // reason: Split D multi-variable declaration into one-per-line.
          // original: float o, to;
          wr = this.rand.nextFloat(0.2) + 0.2;
          hr = this.rand.nextFloat(0.3) + 0.4;
          o = (bx - cx) * wr + (y - cy) * hr;
          wr = this.rand.nextFloat(0.2) + 0.2;
          hr = this.rand.nextFloat(0.3) + 0.4;
          to = (cx + w - 1 - bx) * wr + (y - cy) * hr;
          if (to < o)
            o = to;
          wr = this.rand.nextFloat(0.2) + 0.2;
          hr = this.rand.nextFloat(0.3) + 0.4;
          to = (bx - cx) * wr + (cy + h - 1 - y) * hr;
          if (to < o)
            o = to;
          wr = this.rand.nextFloat(0.2) + 0.2;
          hr = this.rand.nextFloat(0.3) + 0.4;
          to = (cx + w - 1 - bx) * wr + (cy + h - 1 - y) * hr;
          if (to < o)
            o = to;
          if (o > 1)
            this.block[bx][by] = 0;
        }
      }
    }
  }

  private gotoNextBlockArea(): void {
    this.blockCreateCnt += Field.NEXT_BLOCK_AREA_SIZE;
    this.nextBlockY -= Field.NEXT_BLOCK_AREA_SIZE;
    if (this.nextBlockY < 0)
      this.nextBlockY += Field.BLOCK_SIZE_Y;
  }

  public getBlock(arg0: Vector | number, y?: number): number {
    if (arg0 instanceof Vector) {
      return this.getBlock(arg0.x, arg0.y);
    }
    const x = arg0;
    if (y == null) {
      return -1;
    }
    y -= this.screenY - /* D_CAST(int) */ this.screenY;
    let bx: number;
    let by: number;
    // PORT_NOTE[D2TS:multi-decl]:
    // reason: Split D multi-variable declaration into one-per-line.
    // original: int bx, by;
    bx = /* D_CAST(int) */ ((x + this.BLOCK_WIDTH * this.SCREEN_BLOCK_SIZE_X / 2) / this.BLOCK_WIDTH);
    by = /* D_CAST(int) */this.screenY + /* D_CAST(int) */ ((-y + this.BLOCK_WIDTH * this.SCREEN_BLOCK_SIZE_Y / 2) / this.BLOCK_WIDTH);
    if (bx < 0 || bx >= Field.BLOCK_SIZE_X)
      return -1;
    if (by < 0)
      by += Field.BLOCK_SIZE_Y;
    else if (by >= Field.BLOCK_SIZE_Y)
      by -= Field.BLOCK_SIZE_Y;
    return this.block[bx][by];
  }

  public convertToScreenPos(bx: number, y: number): Vector {
    let oy: number = this.screenY - /* D_CAST(int) */ this.screenY;
    let by: number = y - /* D_CAST(int) */ this.screenY;
    if (by <= -Field.BLOCK_SIZE_Y)
      by += Field.BLOCK_SIZE_Y;
    if (by > 0)
      by -= Field.BLOCK_SIZE_Y;
    this.screenPos.x = bx * this.BLOCK_WIDTH - this.BLOCK_WIDTH * this.SCREEN_BLOCK_SIZE_X / 2 + this.BLOCK_WIDTH / 2;
    this.screenPos.y = by * -this.BLOCK_WIDTH + this.BLOCK_WIDTH * this.SCREEN_BLOCK_SIZE_Y / 2 + oy - this.BLOCK_WIDTH / 2;
    return this.screenPos;
  }

  public move(): void {
    this.time += Field.TIME_CHANGE_RATIO;
    if (this.time >= Field.TIME_COLOR_INDEX)
      this.time -= Field.TIME_COLOR_INDEX;
  }

  public draw(): void {
    this.drawPanel();
  }

  public drawSideWalls(): void {
    glDisable(GL_BLEND);
    Screen.setColor(0, 0, 0, 1);
    glBegin(GL_TRIANGLE_FAN);
    glVertex3(Field.SIDEWALL_X1, Field.SIDEWALL_Y, 0);
    glVertex3(Field.SIDEWALL_X2, Field.SIDEWALL_Y, 0);
    glVertex3(Field.SIDEWALL_X2, -Field.SIDEWALL_Y, 0);
    glVertex3(Field.SIDEWALL_X1, -Field.SIDEWALL_Y, 0);
    glEnd();
    glBegin(GL_TRIANGLE_FAN);
    glVertex3(-Field.SIDEWALL_X1, Field.SIDEWALL_Y, 0);
    glVertex3(-Field.SIDEWALL_X2, Field.SIDEWALL_Y, 0);
    glVertex3(-Field.SIDEWALL_X2, -Field.SIDEWALL_Y, 0);
    glVertex3(-Field.SIDEWALL_X1, -Field.SIDEWALL_Y, 0);
    glEnd();
    glEnable(GL_BLEND);
  }

  private drawPanel(): void {
    let ci: number = /* D_CAST(int) */ this.time;
    let nci: number = ci + 1;
    if (nci >= Field.TIME_COLOR_INDEX)
      nci = 0;
    let co: number = this.time - ci;
    for (let i = 0; i < 6; i++)
      for (let j = 0; j < 3; j++)
        this.baseColor[i][j] = this.baseColorTime[ci][i][j] * (1 - co) + this.baseColorTime[nci][i][j] * co;
    let by: number = /* D_CAST(int) */ this.screenY;
    let oy: number = this.screenY - by;
    let sx: number;
    let sy: number = this.BLOCK_WIDTH * this.SCREEN_BLOCK_SIZE_Y / 2 + oy;
    by--;
    if (by < 0)
      by += Field.BLOCK_SIZE_Y;
    sy += this.BLOCK_WIDTH;
    glBegin(GL_QUADS);
    for (let y = -1; y < this.SCREEN_BLOCK_SIZE_Y + Field.NEXT_BLOCK_AREA_SIZE; y++) {
      if (by >= Field.BLOCK_SIZE_Y)
        by -= Field.BLOCK_SIZE_Y;
      sx = -this.BLOCK_WIDTH * this.SCREEN_BLOCK_SIZE_X / 2;
      for (let bx = 0; bx < this.SCREEN_BLOCK_SIZE_X; bx++) {
        const p = this.panel[bx][by];
        Screen.setColor(this.baseColor[p.ci][0] * p.or * 0.66,
                        this.baseColor[p.ci][1] * p.og * 0.66,
                        this.baseColor[p.ci][2] * p.ob * 0.66);
        glVertex3(sx + p.x, sy - p.y, p.z);
        glVertex3(sx + p.x + Field.PANEL_WIDTH, sy - p.y, p.z);
        glVertex3(sx + p.x + Field.PANEL_WIDTH, sy - p.y - Field.PANEL_WIDTH, p.z);
        glVertex3(sx + p.x, sy - p.y - Field.PANEL_WIDTH, p.z);
        Screen.setColor(this.baseColor[p.ci][0] * 0.33,
                        this.baseColor[p.ci][1] * 0.33,
                        this.baseColor[p.ci][2] * 0.33);
        glVertex2(sx, sy);
        glVertex2(sx + this.BLOCK_WIDTH, sy);
        glVertex2(sx + this.BLOCK_WIDTH, sy - this.BLOCK_WIDTH);
        glVertex2(sx, sy - this.BLOCK_WIDTH);
        sx += this.BLOCK_WIDTH;
      }
      sy -= this.BLOCK_WIDTH;
      by++;
    }
    glEnd();
  }

  private static degBlockOfs: number[][] = [[0, -1], [1, 0], [0, 1], [-1, 0]];

  private calcPlatformDeg(x: number, y: number): number {
    let d: number = this.rand.nextInt(4);
    for (let i = 0; i < 4; i++) {
      if (!this.checkBlock(x + Field.degBlockOfs[d][0], y + Field.degBlockOfs[d][1], -1, true)) {
        let pd: number = d * PI / 2;
        let ox: number = x + Field.degBlockOfs[d][0];
        let oy: number = y + Field.degBlockOfs[d][1];
        let td: number = d;
        td--;
        if (td < 0)
          td = 3;
        let b1: boolean = this.checkBlock(ox +  Field.degBlockOfs[td][0], oy +  Field.degBlockOfs[td][1], -1, true);
        td = d;
        td++;
        if (td >= 4)
          td = 0;
        let b2: boolean = this.checkBlock(ox +  Field.degBlockOfs[td][0], oy +  Field.degBlockOfs[td][1], -1, true);
        if (!b1 && b2)
          pd -= PI / 4;
        if (b1 && !b2)
          pd += PI / 4;
        Math.normalizeDeg(pd);
        return pd;
      }
      d++;
      if (d >= 4)
        d = 0;
    }
    return -99999;
  }

  public countAroundBlock(x: number, y: number, th: number = 0): number {
    let c: number = 0;
    if (this.checkBlock(x, y - 1, th))
      c++;
    if (this.checkBlock(x + 1, y, th))
      c++;
    if (this.checkBlock(x, y + 1, th))
      c++;
    if (this.checkBlock(x - 1, y, th))
      c++;
    return c;
  }

  private checkBlock(x: number, y: number, th: number = 0, outScreen: boolean = false): boolean {
    if (x < 0 || x >= Field.BLOCK_SIZE_X)
      return outScreen;
    let by: number = y;
    if (by < 0)
      by += Field.BLOCK_SIZE_Y;
    if (by >= Field.BLOCK_SIZE_Y)
      by -= Field.BLOCK_SIZE_Y;
    return (this.block[x][by] >= th);
  }

  public checkInField(arg0: Vector | number, y?: number): boolean {
    if (arg0 instanceof Vector) {
      return this._size.contains(arg0);
    }
    if (y == null) {
      return false;
    }
    return this._size.contains(arg0, y);
  }

  public checkInOuterField(arg0: Vector | number, y?: number): boolean {
    if (arg0 instanceof Vector) {
      return this._outerSize.contains(arg0);
    }
    if (y == null) {
      return false;
    }
    return this._outerSize.contains(arg0, y);
  }

  public checkInOuterHeightField(p: Vector): boolean {
    if (p.x >= -this._size.x && p.x <= this._size.x && p.y >= -this._outerSize.y && p.y <= this._outerSize.y)
      return true;
    else
      return false;
  }

  public checkInFieldExceptTop(p: Vector): boolean {
    if (p.x >= -this._size.x && p.x <= this._size.x && p.y >= -this._size.y)
      return true;
    else
      return false;
  }

  public checkInOuterFieldExceptTop(p: Vector): boolean {
    if (p.x >= -this._outerSize.x && p.x <= this._outerSize.x &&
        p.y >= -this._outerSize.y && p.y <= this._outerSize.y * 2)
      return true;
    else
      return false;
  }

  public size(): Vector {
    return this._size;
  }

  public outerSize(): Vector {
    return this._outerSize;
  }

  public get lastScrollY(): number {
    return this._lastScrollY;
  }
}
