// @ts-nocheck
// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: letter.d,v 1.1.1.1 2005/06/18 00:46:00 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.letter;

// D_IMPORT: private import std.math;
// D_IMPORT: private import opengl;
// D_IMPORT: private import abagames.util.sdl.displaylist;
// D_IMPORT: private import abagames.gr.screen;

/**
 * Letters.
 */
export class Letter {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static displayList: DisplayList;
  static readonly LETTER_WIDTH: number = 2.1;
  static readonly LETTER_HEIGHT: number = 3.0;
  static readonly LINE_COLOR: number = 2;
  static readonly POLY_COLOR: number = 3;
  static readonly COLOR_NUM: number = 4;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly COLOR_RGB: number[][] = [[1, 1, 1], [0.9, 0.7, 0.5]];
  static readonly LETTER_NUM: number = 44;
  static readonly DISPLAY_LIST_NUM: number = LETTER_NUM * COLOR_NUM;

  public static init(): void {
    Letter.displayList = new DisplayList(Letter.DISPLAY_LIST_NUM);
    Letter.displayList.resetList();
    for (let j = 0; j < Letter.COLOR_NUM; j++) {
      for (let i = 0; i < Letter.LETTER_NUM; i++) {
        Letter.displayList.newList();
        Letter.setLetter(i, j);
        Letter.displayList.endList();
      }
    }
  }

  public static close(): void {
    Letter.displayList.close();
  }

  public static getWidth(n: number, s: number): number {
    return n * s * Letter.LETTER_WIDTH;
  }

  public static getHeight(s: number): number {
    return s * Letter.LETTER_HEIGHT;
  }

  public static drawLetter(n: number, c: number): void {
    Letter.displayList.call(n + c * Letter.LETTER_NUM);
  }

  private static drawLetter(n: number, x: number, y: number, s: number, d: number, c: number): void {
    glPushMatrix();
    glTranslatef(x, y, 0);
    glScalef(s, s, s);
    glRotatef(d, 0, 0, 1);
    Letter.displayList.call(n + c * Letter.LETTER_NUM);
    glPopMatrix();
  }

  private static drawLetterRev(n: number, x: number, y: number, s: number, d: number, c: number): void {
    glPushMatrix();
    glTranslatef(x, y, 0);
    glScalef(s, -s, s);
    glRotatef(d, 0, 0, 1);
    Letter.displayList.call(n + c * Letter.LETTER_NUM);
    glPopMatrix();
  }

  static readonly Direction = {
    TO_RIGHT: 0,
    TO_DOWN: 1,
    TO_LEFT: 2,
    TO_UP: 3
  } as const;

  public static convertCharToInt(c: string): number {
    let idx: number;
    if (c >= '0' && c <='9') {
      idx = c - '0';
    } else if (c >= 'A' && c <= 'Z') {
      idx = c - 'A' + 10;
    } else if (c >= 'a' && c <= 'z') {
      idx = c - 'a' + 10;
    } else if (c == '.') {
      idx = 36;
    } else if (c == '-') {
      idx = 38;
    } else if (c == '+') {
      idx = 39;
    } else if (c == '_') {
      idx = 37;
    } else if (c == '!') {
      idx = 42;
    } else if (c == '/') {
      idx = 43;
    }
    return idx;
  }

  public static drawString(str: string[], lx: number, y: number, s: number, d: number = Direction.TO_RIGHT, cl: number = 0, rev: boolean = false, od: number = 0): void {
    lx += Letter.LETTER_WIDTH * s / 2;
    y += Letter.LETTER_HEIGHT * s / 2;
    let x: number = lx;
    let idx: number;
    let ld: number;
    switch (d) {
    case Direction.TO_RIGHT:
      ld = 0;
      break;
    case Direction.TO_DOWN:
      ld = 90;
      break;
    case Direction.TO_LEFT:
      ld = 180;
      break;
    case Direction.TO_UP:
      ld = 270;
      break;
    }
    ld += od;
    for (const c of str) {
      if (c != ' ') {
        idx = Letter.convertCharToInt(c);
        if (rev)
          Letter.drawLetterRev(idx, x, y, s, ld, cl);
        else
          Letter.drawLetter(idx, x, y, s, ld, cl);
      }
      if (od == 0) {
        switch(d) {
        case Direction.TO_RIGHT:
          x += s * Letter.LETTER_WIDTH;
          break;
        case Direction.TO_DOWN:
          y += s * Letter.LETTER_WIDTH;
          break;
        case Direction.TO_LEFT:
          x -= s * Letter.LETTER_WIDTH;
          break;
        case Direction.TO_UP:
          y -= s * Letter.LETTER_WIDTH;
          break;
        }
      } else {
        x += cos(ld * PI / 180) * s * Letter.LETTER_WIDTH;
        y += sin(ld * PI / 180) * s * Letter.LETTER_WIDTH;
      }
    }
  }

  public static drawNum(num: number, lx: number, y: number, s: number, cl: number = 0, dg: number = 0, headChar: number = -1, floatDigit: number = -1): void {
    lx += Letter.LETTER_WIDTH * s / 2;
    y += Letter.LETTER_HEIGHT * s / 2;
    let n: number = num;
    let x: number = lx;
    let ld: number = 0;
    let digit: number = dg;
    let fd: number = floatDigit;
    for (;;) {
      if (fd <= 0) {
        Letter.drawLetter(n % 10, x, y, s, ld, cl);
        x -= s * Letter.LETTER_WIDTH;
      } else {
        Letter.drawLetter(n % 10, x, y + s * Letter.LETTER_WIDTH * 0.25, s * 0.5, ld, cl);
        x -= s * Letter.LETTER_WIDTH * 0.5;
      }
      n /= 10;
      digit--;
      fd--;
      if (n <= 0 && digit <= 0 && fd < 0)
        break;
      if (fd == 0) {
        Letter.drawLetter(36, x, y + s * Letter.LETTER_WIDTH * 0.25, s * 0.5, ld, cl);
        x -= s * Letter.LETTER_WIDTH * 0.5;
      }
    }
    if (headChar >= 0)
      Letter.drawLetter(headChar, x + s * Letter.LETTER_WIDTH * 0.2, y + s * Letter.LETTER_WIDTH * 0.2,
                 s * 0.6, ld, cl);
  }

  public static drawNumSign(num: number, lx: number, ly: number, s: number, cl: number = 0, headChar: number = -1, floatDigit: number = -1): void {
    let x: number = lx;
    let y: number = ly;
    let n: number = num;
    let fd: number = floatDigit;
    for (;;) {
      if (fd <= 0) {
        Letter.drawLetterRev(n % 10, x, y, s, 0, cl);
        x -= s * Letter.LETTER_WIDTH;
      } else {
        Letter.drawLetterRev(n % 10, x, y - s * Letter.LETTER_WIDTH * 0.25, s * 0.5, 0, cl);
        x -= s * Letter.LETTER_WIDTH * 0.5;
      }
      n /= 10;
      if (n <= 0)
        break;
      fd--;
      if (fd == 0) {
        Letter.drawLetterRev(36, x, y - s * Letter.LETTER_WIDTH * 0.25, s * 0.5, 0, cl);
        x -= s * Letter.LETTER_WIDTH * 0.5;
      }
    }
    if (headChar >= 0)
      Letter.drawLetterRev(headChar, x + s * Letter.LETTER_WIDTH * 0.2, y - s * Letter.LETTER_WIDTH * 0.2,
                    s * 0.6, 0, cl);
  }

  public static drawTime(time: number, lx: number, y: number, s: number, cl: number = 0): void {
    let n: number = time;
    if (n < 0)
      n = 0;
    let x: number = lx;
    for (let i = 0; i < 7; i++) {
      if (i != 4) {
        Letter.drawLetter(n % 10, x, y, s, Direction.TO_RIGHT, cl);
        n /= 10;
      } else {
        Letter.drawLetter(n % 6, x, y, s, Direction.TO_RIGHT, cl);
        n /= 6;
      }
      if ((i & 1) == 1 || i == 0) {
        switch (i) {
        case 3:
          Letter.drawLetter(41, x + s * 1.16, y, s, Direction.TO_RIGHT, cl);
          break;
        case 5:
          Letter.drawLetter(40, x + s * 1.16, y, s, Direction.TO_RIGHT, cl);
          break;
        default:
          break;
        }
        x -= s * Letter.LETTER_WIDTH;
      } else {
        x -= s * Letter.LETTER_WIDTH * 1.3;
      }
      if (n <= 0)
        break;
    }
  }

  private static setLetter(idx: number, c: number): void {
    let x: number;
    let y: number;
    let length: number;
    let size: number;
    let t: number;
    // PORT_NOTE[D2TS:multi-decl]:
    // reason: Split D multi-variable declaration into one-per-line.
    // original: float x, y, length, size, t;
    let deg: number;
    for (let i = 0;; i++) {
      deg = /* D_CAST(int) */ spData[idx][i][4];
      if (deg > 99990) break;
      x = -spData[idx][i][0];
      y = -spData[idx][i][1];
      size = spData[idx][i][2];
      length = spData[idx][i][3];
      y *= 0.9;
      size *= 1.4;
      length *= 1.05;
      x = -x;
      y = y;
      deg %= 180;
      if (c == Letter.LINE_COLOR)
        Letter.setBoxLine(x, y, size, length, deg);
      else if (c == Letter.POLY_COLOR)
        Letter.setBoxPoly(x, y, size, length, deg);
      else
        Letter.setBox(x, y, size, length, deg,
                Letter.COLOR_RGB[c][0], Letter.COLOR_RGB[c][1], Letter.COLOR_RGB[c][2]);
    }
  }

  private static setBox(x: number, y: number, width: number, height: number, deg: number, r: number, g: number, b: number): void {
    glPushMatrix();
    glTranslatef(x - width / 2, y - height / 2, 0);
    glRotatef(deg, 0, 0, 1);
    Screen.setColor(r, g, b, 0.5);
    glBegin(GL_TRIANGLE_FAN);
    Letter.setBoxPart(width, height);
    glEnd();
    Screen.setColor(r, g, b);
    glBegin(GL_LINE_LOOP);
    Letter.setBoxPart(width, height);
    glEnd();
    glPopMatrix();
  }

  private static setBoxLine(x: number, y: number, width: number, height: number, deg: number): void {
    glPushMatrix();
    glTranslatef(x - width / 2, y - height / 2, 0);
    glRotatef(deg, 0, 0, 1);
    glBegin(GL_LINE_LOOP);
    Letter.setBoxPart(width, height);
    glEnd();
    glPopMatrix();
  }

  private static setBoxPoly(x: number, y: number, width: number, height: number, deg: number): void {
    glPushMatrix();
    glTranslatef(x - width / 2, y - height / 2, 0);
    glRotatef(deg, 0, 0, 1);
    glBegin(GL_TRIANGLE_FAN);
    Letter.setBoxPart(width, height);
    glEnd();
    glPopMatrix();
  }

  private static setBoxPart(width: number, height: number): void {
    glVertex3(-width / 2, 0, 0);
    glVertex3(-width / 3 * 1, -height / 2, 0);
    glVertex3( width / 3 * 1, -height / 2, 0);
    glVertex3( width / 2, 0, 0);
    glVertex3( width / 3 * 1,  height / 2, 0);
    glVertex3(-width / 3 * 1,  height / 2, 0);
  }
  
  private static spData: number[][][] =
    [[
     [0, 1.15, 0.65, 0.3, 0],
     [-0.6, 0.55, 0.65, 0.3, 90], [0.6, 0.55, 0.65, 0.3, 90],
     [-0.6, -0.55, 0.65, 0.3, 90], [0.6, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [0.5, 0.55, 0.65, 0.3, 90],
     [0.5, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [0.65, 0.55, 0.65, 0.3, 90],
     [0, 0, 0.65, 0.3, 0],
     [-0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [0.65, 0.55, 0.65, 0.3, 90],
     [0, 0, 0.65, 0.3, 0],
     [0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [0, 0, 0.65, 0.3, 0],
     [0.65, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90],
     [0, 0, 0.65, 0.3, 0],
     [0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90],
     [0, 0, 0.65, 0.3, 0],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [0.65, 0.55, 0.65, 0.3, 90],
     [0.65, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [0, 0, 0.65, 0.3, 0],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [0, 0, 0.65, 0.3, 0],
     [0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[//A
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [0, 0, 0.65, 0.3, 0],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.65, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[
     [-0.18, 1.15, 0.45, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90], [0.45, 0.55, 0.65, 0.3, 90],
     [-0.18, 0, 0.45, 0.3, 0],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90],
     [-0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [-0.15, 1.15, 0.45, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90], [0.45, 0.45, 0.65, 0.3, 90],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90],
     [0, 0, 0.65, 0.3, 0],
     [-0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[//F
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90],
     [0, 0, 0.65, 0.3, 0],
     [-0.65, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90],
     [0.05, 0, 0.3, 0.3, 0],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [0, 0, 0.65, 0.3, 0],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.65, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 0.55, 0.65, 0.3, 90],
     [0, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[
     [0.65, 0.55, 0.65, 0.3, 90],
     [0.65, -0.55, 0.65, 0.3, 90], [-0.7, -0.7, 0.3, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[//K
     [-0.65, 0.55, 0.65, 0.3, 90], [0.4, 0.55, 0.65, 0.3, 100],
     [-0.25, 0, 0.45, 0.3, 0],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.6, -0.55, 0.65, 0.3, 80],
     [0, 0, 0, 0, 99999],
    ],[
     [-0.65, 0.55, 0.65, 0.3, 90],
     [-0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [-0.5, 1.15, 0.3, 0.3, 0], [0.1, 1.15, 0.3, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.65, -0.55, 0.65, 0.3, 90],
     [0, 0.55, 0.65, 0.3, 90],
     [0, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.65, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[//P
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [0, 0, 0.65, 0.3, 0],
     [-0.65, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0.05, -0.55, 0.45, 0.3, 60],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [-0.2, 0, 0.45, 0.3, 0],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.45, -0.55, 0.65, 0.3, 80],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [-0.65, 0.55, 0.65, 0.3, 90],
     [0, 0, 0.65, 0.3, 0],
     [0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [-0.5, 1.15, 0.55, 0.3, 0], [0.5, 1.15, 0.55, 0.3, 0],
     [0.1, 0.55, 0.65, 0.3, 90],
     [0.1, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[//U
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.65, -0.55, 0.65, 0.3, 90],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [-0.5, -0.55, 0.65, 0.3, 90], [0.5, -0.55, 0.65, 0.3, 90],
     [-0.1, -1.15, 0.45, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[
     [-0.65, 0.55, 0.65, 0.3, 90], [0.65, 0.55, 0.65, 0.3, 90],
     [-0.65, -0.55, 0.65, 0.3, 90], [0.65, -0.55, 0.65, 0.3, 90],
     [-0.5, -1.15, 0.3, 0.3, 0], [0.1, -1.15, 0.3, 0.3, 0],
     [0, 0.55, 0.65, 0.3, 90],
     [0, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[
     [-0.4, 0.6, 0.85, 0.3, 360-120],
     [0.4, 0.6, 0.85, 0.3, 360-60],
     [-0.4, -0.6, 0.85, 0.3, 360-240],
     [0.4, -0.6, 0.85, 0.3, 360-300],
     [0, 0, 0, 0, 99999],
    ],[
     [-0.4, 0.6, 0.85, 0.3, 360-120],
     [0.4, 0.6, 0.85, 0.3, 360-60],
     [-0.1, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[
     [0, 1.15, 0.65, 0.3, 0],
     [0.3, 0.4, 0.65, 0.3, 120],
     [-0.3, -0.4, 0.65, 0.3, 120],
     [0, -1.15, 0.65, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[//.
     [0, -1.15, 0.3, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[//_
     [0, -1.15, 0.8, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[//-
     [0, 0, 0.9, 0.3, 0],
     [0, 0, 0, 0, 99999],
    ],[//+
     [-0.5, 0, 0.45, 0.3, 0], [0.45, 0, 0.45, 0.3, 0],
     [0.1, 0.55, 0.65, 0.3, 90],
     [0.1, -0.55, 0.65, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[//'
     [0, 1.0, 0.4, 0.2, 90],
     [0, 0, 0, 0, 99999],
    ],[//''
     [-0.19, 1.0, 0.4, 0.2, 90],
     [0.2, 1.0, 0.4, 0.2, 90],
     [0, 0, 0, 0, 99999],
    ],[//!
     [0.56, 0.25, 1.1, 0.3, 90],
     [0, -1.0, 0.3, 0.3, 90],
     [0, 0, 0, 0, 99999],
    ],[// /
     [0.8, 0, 1.75, 0.3, 120],
     [0, 0, 0, 0, 99999],
    ]];
}
