// @ts-nocheck
// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: mouseandpad.d,v 1.1 2005/09/11 00:47:40 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.mouseandpad;

// D_IMPORT: private import std.string;
// D_IMPORT: private import std.stream;
// D_IMPORT: private import SDL;
// D_IMPORT: private import abagames.util.sdl.input;
// D_IMPORT: private import abagames.util.sdl.recordableinput;
// D_IMPORT: private import abagames.util.sdl.mouse;
// D_IMPORT: private import abagames.util.sdl.pad;

/**
 * Record mouse and pad input.
 */
export class MouseAndPadState {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  mouseState: MouseState;
  padState: PadState;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:

  public static newInstance(): MouseAndPadState {
    return new MouseAndPadState();
  }

  public static newInstance(s: MouseAndPadState): MouseAndPadState {
    return new MouseAndPadState(s);
  }

  public constructor() {
    this.mouseState = new MouseState();
    this.padState = new PadState();
  }

  public constructor(s: MouseAndPadState) {
    constructor();
    this.set(s);
  }

  public set(s: MouseAndPadState): void {
    this.mouseState.set(s.mouseState);
    this.padState.set(s.padState);
  }

  public clear(): void {
    this.mouseState.clear();
    this.padState.clear();
  }

  public read(fd: File): void {
    this.mouseState.read(fd);
    this.padState.read(fd);
  }

  public write(fd: File): void {
    this.mouseState.write(fd);
    this.padState.write(fd);
  }

  public equals(s: MouseAndPadState): boolean {
    if (this.mouseState.equals(s.mouseState) && this.padState.equals(s.padState))
      return true;
    else
      return false;
  }
}

export class RecordableMouseAndPad {
  // PORT_NOTE[D2TS:d-specific-feature]:
  // reason: D-specific feature requires manual rewrite.
  // original: mixin RecordableInput!(MouseAndPadState);
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  state: MouseAndPadState;
  mouse: Mouse;
  pad: Pad;

  public constructor(mouse: Mouse, pad: Pad) {
    this.mouse = mouse;
    this.pad = pad;
    this.state = new MouseAndPadState();
  }

  public getState(doRecord: boolean = true): MouseAndPadState {
    let rm: RecordableMouse = /* D_CAST(RecordableMouse) */ this.mouse;
    if (rm)
      this.state.mouseState = rm.getState(false);
    else
      this.state.mouseState = this.mouse.getState();
    let rp: RecordablePad = /* D_CAST(RecordablePad) */ this.pad;
    if (rp)
      this.state.padState = rp.getState(false);
    else
      this.state.padState = this.pad.getState();
    if (doRecord)
      record(this.state);
    return this.state;
  }
}
