// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: mouse.d,v 1.1 2005/09/11 00:47:40 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.mouse;

// D_IMPORT: private import abagames.util.sdl.mouse;
// D_IMPORT: private import abagames.util.sdl.screen;

/**
 * Mouse input.
 */
export class RecordableMouse extends abagames.util.sdl.mouse.RecordableMouse {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly MOUSE_SCREEN_MAPPING_RATIO_X: number = 26.0;
  static readonly MOUSE_SCREEN_MAPPING_RATIO_Y: number = 19.5;
  screen: SizableScreen;

  public constructor(screen: SizableScreen) {
    super();
    this.screen = screen;
  }

  protected override adjustPos(ms: MouseState): void {
    ms.x =  (ms.x - this.screen.width  / 2) * RecordableMouse.MOUSE_SCREEN_MAPPING_RATIO_X / this.screen.width;
    ms.y = -(ms.y - this.screen.height / 2) * RecordableMouse.MOUSE_SCREEN_MAPPING_RATIO_Y / this.screen.height;
  }
}
