// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: particle.d,v 1.1.1.1 2005/06/18 00:46:00 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.particle;

// D_IMPORT: private import std.math;
// D_IMPORT: private import opengl;
// D_IMPORT: private import abagames.util.actor;
// D_IMPORT: private import abagames.util.vector;
// D_IMPORT: private import abagames.util.rand;
// D_IMPORT: private import abagames.util.sdl.luminous;
// D_IMPORT: private import abagames.util.sdl.displaylist;
// D_IMPORT: private import abagames.gr.field;
// D_IMPORT: private import abagames.gr.screen;

/**
 * Sparks.
 */
export class Spark extends LuminousActor {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static rand: Rand;
  pos: Vector;
  ppos: Vector;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: Vector pos, ppos;
  vel: Vector;
  r: number;
  g: number;
  b: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float r, g, b;
  cnt: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  static {
    rand = new Rand();
  }

  public static setRandSeed(seed: number): void {
    Spark.rand.setSeed(seed);
  }

  public constructor() {
    this.pos = new Vector();
    this.ppos = new Vector();
    this.vel = new Vector();
    this.r = this.g = this.b = 0;
    this.cnt = 0;
  }

  public override init(args: unknown[]): void {
  }

  public set(p: Vector, vx: number, vy: number, r: number, g: number, b: number, c: number): void {
    this.ppos.x = this.pos.x = p.x;
    this.ppos.y = this.pos.y = p.y;
    this.vel.x = vx;
    this.vel.y = vy;
    this.r = r;
    this.g = g;
    this.b = b;
    this.cnt = c;
    exists = true;
  }

  public override move(): void {
    this.cnt--;
    if (this.cnt <= 0 || this.vel.dist() < 0.005) {
      exists = false;
      return;
    }
    this.ppos.x = this.pos.x;
    this.ppos.y = this.pos.y;
    this.pos += this.vel;
    this.vel *= 0.96;
  }

  public override draw(): void {
    let ox: number = this.vel.x;
    let oy: number = this.vel.y;
    Screen.setColor(this.r, this.g, this.b, 1);
    ox *= 2;
    oy *= 2;
    glVertex3(this.pos.x - ox, this.pos.y - oy, 0);
    ox *= 0.5;
    oy *= 0.5;
    Screen.setColor(this.r * 0.5, this.g * 0.5, this.b * 0.5, 0);
    glVertex3(this.pos.x - oy, this.pos.y + ox, 0);
    glVertex3(this.pos.x + oy, this.pos.y - ox, 0);
  }

  public override drawLuminous(): void {
    let ox: number = this.vel.x;
    let oy: number = this.vel.y;
    Screen.setColor(this.r, this.g, this.b, 1);
    ox *= 2;
    oy *= 2;
    glVertex3(this.pos.x - ox, this.pos.y - oy, 0);
    ox *= 0.5;
    oy *= 0.5;
    Screen.setColor(this.r * 0.5, this.g * 0.5, this.b * 0.5, 0);
    glVertex3(this.pos.x - oy, this.pos.y + ox, 0);
    glVertex3(this.pos.x + oy, this.pos.y - ox, 0);
  }
}

export class SparkPool extends LuminousActorPool<Spark> {
  public constructor(n: number, args: unknown[]) {
    super(n, args);
  }
}

/**
 * Smokes.
 */
export class Smoke extends LuminousActor {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly SmokeType = {
    FIRE: 0,
    EXPLOSION: 1,
    SAND: 2,
    SPARK: 3,
    WAKE: 4,
    SMOKE: 5,
    LANCE_SPARK: 6
  } as const;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static rand: Rand;
  static windVel: Vector3;
  static wakePos: Vector;
  field: Field;
  wakes: WakePool;
  pos: Vector3;
  vel: Vector3;
  type: number;
  cnt: number;
  startCnt: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: int cnt, startCnt;
  size: number;
  r: number;
  g: number;
  b: number;
  a: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float r, g, b, a;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  static {
    rand = new Rand();
    wakePos = new Vector();
    windVel = new Vector3(0.04, 0.04, 0.02);
  }

  public static setRandSeed(seed: number): void {
    Smoke.rand.setSeed(seed);
  }

  public constructor() {
    this.pos = new Vector3();
    this.vel = new Vector3();
    this.type = 0;
    this.cnt = 0;
    this.startCnt = 1;
    this.size = 1;
    this.r = this.g = this.b = this.a = 0;
  }

  public override init(args: unknown[]): void {
    this.field = /* D_CAST(Field) */ args[0];
    this.wakes = /* D_CAST(WakePool) */ args[1];
  }

  public set(p: Vector, mx: number, my: number, mz: number, t: number, c: number = 60, sz: number = 2): void {
    this.set(p.x, p.y, mx, my, mz, t, c, sz);
  }

  public set(p: Vector3, mx: number, my: number, mz: number, t: number, c: number = 60, sz: number = 2): void {
    this.set(p.x, p.y, mx, my, mz, t, c, sz);
    this.pos.z = p.z;
  }

  public set(x: number, y: number, mx: number, my: number, mz: number, t: number, c: number = 60, sz: number = 2): void {
    if (!this.field.checkInOuterField(x, y))
      return;
    this.pos.x = x;
    this.pos.y = y;
    this.pos.z = 0;
    this.vel.x = mx;
    this.vel.y = my;
    this.vel.z = mz;
    this.type = t;
    this.startCnt = this.cnt = c;
    this.size = sz;
    switch (this.type) {
    case SmokeType.FIRE:
      this.r = Smoke.rand.nextFloat(0.1) + 0.9;
      this.g = Smoke.rand.nextFloat(0.2) + 0.2;
      this.b = 0;
      this.a = 1;
      break;
    case SmokeType.EXPLOSION:
      this.r = Smoke.rand.nextFloat(0.3) + 0.7;
      this.g = Smoke.rand.nextFloat(0.3) + 0.3;
      this.b = 0;
      this.a = 1;
      break;
    case SmokeType.SAND:
      this.r = 0.8;
      this.g = 0.8;
      this.b = 0.6;
      this.a = 0.6;
      break;
    case SmokeType.SPARK:
      this.r = Smoke.rand.nextFloat(0.3) + 0.7;
      this.g = Smoke.rand.nextFloat(0.5) + 0.5;
      this.b = 0;
      this.a = 1;
      break;
    case SmokeType.WAKE:
      this.r = 0.6;
      this.g = 0.6;
      this.b = 0.8;
      this.a = 0.6;
      break;
    case SmokeType.SMOKE:
      this.r = Smoke.rand.nextFloat(0.1) + 0.1;
      this.g = Smoke.rand.nextFloat(0.1) + 0.1;
      this.b = 0.1;
      this.a = 0.5;
      break;
    case SmokeType.LANCE_SPARK:
      this.r = 0.4;
      this.g = Smoke.rand.nextFloat(0.2) + 0.7;
      this.b = Smoke.rand.nextFloat(0.2) + 0.7;
      this.a = 1;
      break;
    }
    exists = true;
  }

  public override move(): void {
    this.cnt--;
    if (this.cnt <= 0 || !this.field.checkInOuterField(this.pos.x, this.pos.y)) {
      exists = false;
      return;
    }
    if (this.type != SmokeType.WAKE) {
      this.vel.x += (Smoke.windVel.x - this.vel.x) * 0.01;
      this.vel.y += (Smoke.windVel.y - this.vel.y) * 0.01;
      this.vel.z += (Smoke.windVel.z - this.vel.z) * 0.01;
    }
    this.pos += this.vel;
    this.pos.y -= this.field.lastScrollY;
    switch (this.type) {
    case SmokeType.FIRE:
    case SmokeType.EXPLOSION:
    case SmokeType.SMOKE:
      if (this.cnt < this.startCnt / 2) {
        this.r *= 0.95;
        this.g *= 0.95;
        this.b *= 0.95;
      } else {
        this.a *= 0.97;
      }
      this.size *= 1.01;
      break;
    case SmokeType.SAND:
      this.r *= 0.98;
      this.g *= 0.98;
      this.b *= 0.98;
      this.a *= 0.98;
      break;
    case SmokeType.SPARK:
      this.r *= 0.92;
      this.g *= 0.92;
      this.a *= 0.95;
      this.vel *= 0.9;
      break;
    case SmokeType.WAKE:
      this.a *= 0.98;
      this.size *= 1.005;
      break;
    case SmokeType.LANCE_SPARK:
      this.a *= 0.95;
      this.size *= 0.97;
      break;
    }
    if (this.size > 5)
      this.size = 5;
    if (this.type == SmokeType.EXPLOSION && this.pos.z < 0.01) {
      let bl: number = this.field.getBlock(this.pos.x, this.pos.y);
      if (bl >= 1)
        this.vel *= 0.8;
      if (this.cnt % 3 == 0 && bl < -1) {
        let sp: number = sqrt(this.vel.x * this.vel.x + this.vel.y * this.vel.y);
        if (sp > 0.3) {
          let d: number = atan2(this.vel.x, this.vel.y);
          assert(!Number.isNaN(d) && !Number.isNaN(0));
          Smoke.wakePos.x = this.pos.x + sin(d + PI / 2) * this.size * 0.25;
          Smoke.wakePos.y = this.pos.y + cos(d + PI / 2) * this.size * 0.25;
          let w: Wake = this.wakes.getInstanceForced();
          assert(!Number.isNaN(Smoke.wakePos.x) && !Number.isNaN(0));
          assert(!Number.isNaN(Smoke.wakePos.y) && !Number.isNaN(0));
          w.set(Smoke.wakePos, d + PI - 0.2 + Smoke.rand.nextSignedFloat(0.1), sp * 0.33,
                20 + Smoke.rand.nextInt(12), this.size * (7.0 + Smoke.rand.nextFloat(3)));
          Smoke.wakePos.x = this.pos.x + sin(d - PI / 2) * this.size * 0.25;
          Smoke.wakePos.y = this.pos.y + cos(d - PI / 2) * this.size * 0.25;
          w = this.wakes.getInstanceForced();
          assert(!Number.isNaN(Smoke.wakePos.x) && !Number.isNaN(0));
          assert(!Number.isNaN(Smoke.wakePos.y) && !Number.isNaN(0));
          w.set(Smoke.wakePos, d + PI + 0.2 + Smoke.rand.nextSignedFloat(0.1), sp * 0.33,
                20 + Smoke.rand.nextInt(12), this.size * (7.0 + Smoke.rand.nextFloat(3)));
        }
      }
    }
  }

  public override draw(): void {
    let quadSize: number = this.size / 2;
    Screen.setColor(this.r, this.g, this.b, this.a);
    glVertex3(this.pos.x - quadSize, this.pos.y - quadSize, this.pos.z);
    glVertex3(this.pos.x + quadSize, this.pos.y - quadSize, this.pos.z);
    glVertex3(this.pos.x + quadSize, this.pos.y + quadSize, this.pos.z);
    glVertex3(this.pos.x - quadSize, this.pos.y + quadSize, this.pos.z);
  }

  public override drawLuminous(): void {
    if (this.r + this.g > 0.8 && this.b < 0.5) {
      let quadSize: number = this.size / 2;
      Screen.setColor(this.r, this.g, this.b, this.a);
      glVertex3(this.pos.x - quadSize, this.pos.y - quadSize, this.pos.z);
      glVertex3(this.pos.x + quadSize, this.pos.y - quadSize, this.pos.z);
      glVertex3(this.pos.x + quadSize, this.pos.y + quadSize, this.pos.z);
      glVertex3(this.pos.x - quadSize, this.pos.y + quadSize, this.pos.z);
    }
  }
}

export class SmokePool extends LuminousActorPool<Smoke> {
  public constructor(n: number, args: unknown[]) {
    super(n, args);
  }
}

/**
 * Fragments of destroyed enemies.
 */
export class Fragment extends Actor {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static displayList: DisplayList;
  static rand: Rand;
  field: Field;
  smokes: SmokePool;
  pos: Vector3;
  vel: Vector3;
  size: number;
  d2: number;
  md2: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float d2, md2;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public static init(): void {
    Fragment.rand = new Rand();
    Fragment.displayList = new DisplayList(1);
    Fragment.displayList.beginNewList();
    Screen.setColor(0.7, 0.5, 0.5, 0.5);
    glBegin(GL_TRIANGLE_FAN);
    glVertex2(-0.5, -0.25);
    glVertex2(0.5, -0.25);
    glVertex2(0.5, 0.25);
    glVertex2(-0.5, 0.25);
    glEnd();
    Screen.setColor(0.7, 0.5, 0.5, 0.9);
    glBegin(GL_LINE_LOOP);
    glVertex2(-0.5, -0.25);
    glVertex2(0.5, -0.25);
    glVertex2(0.5, 0.25);
    glVertex2(-0.5, 0.25);
    glEnd();
    Fragment.displayList.endNewList();
  }

  public static setRandSeed(seed: number): void {
    Fragment.rand.setSeed(seed);
  }

  public static close(): void {
    Fragment.displayList.close();
  }

  public constructor() {
    this.pos = new Vector3();
    this.vel = new Vector3();
    this.size = 1;
    this.d2 = this.md2 = 0;
  }

  public override init(args: unknown[]): void {
    this.field = /* D_CAST(Field) */ args[0];
    this.smokes = /* D_CAST(SmokePool) */ args[1];
  }

  public set(p: Vector, mx: number, my: number, mz: number, sz: number = 1): void {
    if (!this.field.checkInOuterField(p.x, p.y))
      return;
    this.pos.x = p.x;
    this.pos.y = p.y;
    this.pos.z = 0;
    this.vel.x = mx;
    this.vel.y = my;
    this.vel.z = mz;
    this.size = sz;
    if (this.size > 5)
      this.size = 5;
    this.d2 = Fragment.rand.nextFloat(360);
    this.md2 = Fragment.rand.nextSignedFloat(20);
    exists = true;
  }

  public override move(): void {
    if (!this.field.checkInOuterField(this.pos.x, this.pos.y)) {
      exists = false;
      return;
    }
    this.vel.x *= 0.96;
    this.vel.y *= 0.96;
    this.vel.z += (-0.04 - this.vel.z) * 0.01;
    this.pos += this.vel;
    if (this.pos.z < 0) {
      let s: Smoke = this.smokes.getInstanceForced();
      if (this.field.getBlock(this.pos.x, this.pos.y) < 0)
        s.set(this.pos.x, this.pos.y, 0, 0, 0, Smoke.SmokeType.WAKE, 60, this.size * 0.66);
      else
        s.set(this.pos.x, this.pos.y, 0, 0, 0, Smoke.SmokeType.SAND, 60, this.size * 0.75);
      exists = false;
      return;
    }
    this.pos.y -= this.field.lastScrollY;
    this.d2 += this.md2;
  }

  public override draw(): void {
    glPushMatrix();
    Screen.glTranslate(this.pos);
    glRotatef(this.d2, 1, 0, 0);
    glScalef(this.size, this.size, 1);
    Fragment.displayList.call(0);
    glPopMatrix();
  }
}

export class FragmentPool extends ActorPool<Fragment> {
  public constructor(n: number, args: unknown[]) {
    super(n, args);
  }
}

/**
 * Luminous fragments.
 */
export class SparkFragment extends LuminousActor {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static displayList: DisplayList;
  static rand: Rand;
  field: Field;
  smokes: SmokePool;
  pos: Vector3;
  vel: Vector3;
  size: number;
  d2: number;
  md2: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float d2, md2;
  cnt: number;
  hasSmoke: boolean;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public static init(): void {
    SparkFragment.rand = new Rand();
    SparkFragment.displayList = new DisplayList(1);
    SparkFragment.displayList.beginNewList();
    glBegin(GL_TRIANGLE_FAN);
    glVertex2(-0.25, -0.25);
    glVertex2(0.25, -0.25);
    glVertex2(0.25, 0.25);
    glVertex2(-0.25, 0.25);
    glEnd();
    SparkFragment.displayList.endNewList();
  }

  public static setRandSeed(seed: number): void {
    SparkFragment.rand.setSeed(seed);
  }

  public static close(): void {
    SparkFragment.displayList.close();
  }

  public constructor() {
    this.pos = new Vector3();
    this.vel = new Vector3();
    this.size = 1;
    this.d2 = this.md2 = 0;
    this.cnt = 0;
  }

  public override init(args: unknown[]): void {
    this.field = /* D_CAST(Field) */ args[0];
    this.smokes = /* D_CAST(SmokePool) */ args[1];
  }

  public set(p: Vector, mx: number, my: number, mz: number, sz: number = 1): void {
    if (!this.field.checkInOuterField(p.x, p.y))
      return;
    this.pos.x = p.x;
    this.pos.y = p.y;
    this.pos.z = 0;
    this.vel.x = mx;
    this.vel.y = my;
    this.vel.z = mz;
    this.size = sz;
    if (this.size > 5)
      this.size = 5;
    this.d2 = SparkFragment.rand.nextFloat(360);
    this.md2 = SparkFragment.rand.nextSignedFloat(15);
    if (SparkFragment.rand.nextInt(4) == 0)
      this.hasSmoke = true;
    else
      this.hasSmoke = false;
    this.cnt = 0;
    exists = true;
  }

  public override move(): void {
    if (!this.field.checkInOuterField(this.pos.x, this.pos.y)) {
      exists = false;
      return;
    }
    this.vel.x *= 0.99;
    this.vel.y *= 0.99;
    this.vel.z += (-0.08 - this.vel.z) * 0.01;
    this.pos += this.vel;
    if (this.pos.z < 0) {
      let s: Smoke = this.smokes.getInstanceForced();
      if (this.field.getBlock(this.pos.x, this.pos.y) < 0)
        s.set(this.pos.x, this.pos.y, 0, 0, 0, Smoke.SmokeType.WAKE, 60, this.size * 0.66);
      else
        s.set(this.pos.x, this.pos.y, 0, 0, 0, Smoke.SmokeType.SAND, 60, this.size * 0.75);
      exists = false;
      return;
    }
    this.pos.y -= this.field.lastScrollY;
    this.d2 += this.md2;
    this.cnt++;
    if (this.hasSmoke && this.cnt % 5 == 0) {
      let s: Smoke = this.smokes.getInstance();
      if (s)
        s.set(this.pos, 0, 0, 0, Smoke.SmokeType.SMOKE, 90 + SparkFragment.rand.nextInt(60), this.size * 0.5);
    }
  }

  public override draw(): void {
    glPushMatrix();
    Screen.setColor(1, SparkFragment.rand.nextFloat(1), 0, 0.8);
    Screen.glTranslate(this.pos);
    glRotatef(this.d2, 1, 0, 0);
    glScalef(this.size, this.size, 1);
    SparkFragment.displayList.call(0);
    glPopMatrix();
  }

  public override drawLuminous(): void {
    glPushMatrix();
    Screen.setColor(1, SparkFragment.rand.nextFloat(1), 0, 0.8);
    Screen.glTranslate(this.pos);
    glRotatef(this.d2, 1, 0, 0);
    glScalef(this.size, this.size, 1);
    SparkFragment.displayList.call(0);
    glPopMatrix();
  }
}

export class SparkFragmentPool extends LuminousActorPool<SparkFragment> {
  public constructor(n: number, args: unknown[]) {
    super(n, args);
  }
}

/**
 * Wakes of ships and smokes.
 */
export class Wake extends Actor {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  field: Field;
  pos: Vector;
  vel: Vector;
  deg: number;
  speed: number;
  size: number;
  cnt: number;
  revShape: boolean;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor() {
    this.pos = new Vector();
    this.vel = new Vector();
    this.size = 1;
    this.deg = 0;
    this.speed = 0;
    this.cnt = 0;
  }

  public override init(args: unknown[]): void {
    this.field = /* D_CAST(Field) */ args[0];
  }

  public set(p: Vector, deg: number, speed: number, c: number = 60, sz: number = 1, rs: boolean = false): void {
    if (!this.field.checkInOuterField(p.x, p.y))
      return;
    this.pos.x = p.x;
    this.pos.y = p.y;
    this.deg = deg;
    this.speed = speed;
    this.vel.x = sin(deg) * speed;
    this.vel.y = cos(deg) * speed;
    this.cnt = c;
    this.size = sz;
    this.revShape = rs;
    exists = true;
  }

  public override move(): void {
    this.cnt--;
    if (this.cnt <= 0 || this.vel.dist() < 0.005 || !this.field.checkInOuterField(this.pos.x, this.pos.y)) {
      exists = false;
      return;
    }
    this.pos += this.vel;
    this.pos.y -= this.field.lastScrollY;
    this.vel *= 0.96;
    this.size *= 1.02;
  }

  public override draw(): void {
    let ox: number = this.vel.x;
    let oy: number = this.vel.y;
    Screen.setColor(0.33, 0.33, 1);
    ox *= this.size;
    oy *= this.size;
    if (this.revShape)
      glVertex3(this.pos.x + ox, this.pos.y + oy, 0);
    else
      glVertex3(this.pos.x - ox, this.pos.y - oy, 0);
    ox *= 0.2;
    oy *= 0.2;
    Screen.setColor(0.2, 0.2, 0.6, 0.5);
    glVertex3(this.pos.x - oy, this.pos.y + ox, 0);
    glVertex3(this.pos.x + oy, this.pos.y - ox, 0);
  }
}

export class WakePool extends ActorPool<Wake> {
  public constructor(n: number, args: unknown[]) {
    super(n, args);
  }
}
