// @ts-nocheck
// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: prefmanager.d,v 1.4 2005/09/11 00:47:40 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.prefmanager;

// D_IMPORT: private import std.stream;
// D_IMPORT: private import abagames.util.prefmanager;
// D_IMPORT: private import abagames.gr.gamemanager;

/**
 * Save/Load the high score.
 */
export class PrefManager extends abagames.util.prefmanager.PrefManager {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly VERSION_NUM: number = 14;
  static readonly VERSION_NUM_13: number = 13;
  static readonly PREF_FILE: string[] = "gr.prf";
  _prefData: PrefData;

  public constructor() {
    this._prefData = new PrefData();
  }

  public load(): void {
    let fd: File = new File;
    try {
      let ver: number;
      fd.open(PrefManager.PREF_FILE);
      fd.read(ver);
      if (ver == PrefManager.VERSION_NUM_13)
        this._prefData.loadVer13(fd);
      else if (ver != PrefManager.VERSION_NUM)
        throw new Error("Wrong version num");
      else
        this._prefData.load(fd);
    } catch (e) /* PORT_NOTE[D2TS:catch-type] D catch type was removed */ {
      this._prefData.init();
    } finally {
      if (fd.isOpen())
        fd.close();
    }
  }

  public save(): void {
    let fd: File = new File;
    fd.create(PrefManager.PREF_FILE);
    fd.write(PrefManager.VERSION_NUM);
    this._prefData.save(fd);
    fd.close();
  }

  public prefData(): PrefData {
    return this._prefData;
  }
}

export class PrefData {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  //int[InGameState.GAME_MODE_NUM] _highScore;
  _highScore: number[];
  _gameMode: number;

  public init(): void {
    for (const hs of this._highScore)
      hs = 0;
    this._gameMode = 0;
  }

  public load(fd: File): void {
    for (const hs of this._highScore)
      fd.read(hs);
    fd.read(this._gameMode);
  }

  public loadVer13(fd: File): void {
    this.init();
    for (let i = 0; i < 3; i++)
      fd.read(this._highScore[i]);
    fd.read(this._gameMode);
  }

  public save(fd: File): void {
    for (const hs of this._highScore)
      fd.write(hs);
    fd.write(this._gameMode);
  }

  public recordGameMode(gm: number): void {
    this._gameMode = gm;
  }

  public recordResult(score: number, gm: number): void {
    if (score > this._highScore[gm])
      this._highScore[gm] = score;
    this._gameMode = gm;
  }

  public highScore(gm: number): number {
    let _highScore: return[];
  }

  public gameMode(): number {
    return this._gameMode;
  }
}
