// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: reel.d,v 1.1.1.1 2005/06/18 00:46:00 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.reel;

// D_IMPORT: private import std.math;
// D_IMPORT: private import opengl;
// D_IMPORT: private import abagames.util.math;
// D_IMPORT: private import abagames.util.vector;
// D_IMPORT: private import abagames.util.actor;
// D_IMPORT: private import abagames.util.rand;
// D_IMPORT: private import abagames.gr.letter;
// D_IMPORT: private import abagames.gr.screen;
// D_IMPORT: private import abagames.gr.soundmanager;

/**
 * Rolling reel that displays the score.
 */
export class ScoreReel {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly MAX_DIGIT: number = 16;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  score: number;
  targetScore: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: int score, targetScore;
  _actualScore: number;
  digit: number;
  numReel: NumReel[];

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor() {
    for (const nr of this.numReel)
      nr = new NumReel();
    this.digit = 1;
  }

  public clear(digit: number = 9): void {
    this.score = this.targetScore = this._actualScore = 0;
    this.digit = digit;
    for (let i = 0; i < digit; i++)
      this.numReel[i].clear();
  }

  public move(): void {
    for (let i = 0; i < this.digit; i++)
      this.numReel[i].move();
  }

  public draw(x: number, y: number, s: number): void {
    let lx: number = x, ly = y;
    for (let i = 0; i < this.digit; i++) {
      this.numReel[i].draw(lx, ly, s);
      lx -= s * 2;
    }
  }

  public addReelScore(as: number): void {
    this.targetScore += as;
    let ts: number = this.targetScore;
    for (let i = 0; i < this.digit; i++) {
      this.numReel[i].targetDeg = /* D_CAST(float) */ ts * 360 / 10;
      ts /= 10;
      if (ts < 0)
        break;
    }
  }

  public accelerate(): void {
    for (let i = 0; i < this.digit; i++)
      this.numReel[i].accelerate();
  }

  public addActualScore(as: number): void {
    this._actualScore += as;
  }

  public actualScore(): number {
    return this._actualScore;
  }
}

export class NumReel {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly VEL_MIN: number = 5;
  static rand: Rand;
  deg: number;
  _targetDeg: number;
  ofs: number;
  velRatio: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  static {
    rand = new Rand();
  }

  public static setRandSeed(seed: number): void {
    NumReel.rand.setSeed(seed);
  }

  public constructor() {
    this.init();
  }

  private init(): void {
    this.deg = this._targetDeg = 0;
    this.ofs = 0;
    this.velRatio = 1;
  }

  public clear(): void {
    this.init();
  }

  public move(): void {
    let vd: number = this._targetDeg - this.deg;
    vd *= 0.05 * this.velRatio;
    if (vd < NumReel.VEL_MIN * this.velRatio)
      vd = NumReel.VEL_MIN * this.velRatio;
    this.deg += vd;
    if (this.deg > this._targetDeg)
      this.deg = this._targetDeg;
  }

  public draw(x: number, y: number, s: number): void {
    let n: number = /* D_CAST(int) */ ((this.deg * 10 / 360 + 0.99) + 1) % 10;
    let d: number = this.deg % 360;
    let od: number = d - n * 360 / 10;
    od -= 15;
    Math.normalizeDeg360(od);
    od *= 1.5;
    for (let i = 0; i < 3; i++) {
      glPushMatrix();
      if (this.ofs > 0.005)
        glTranslatef(x + NumReel.rand.nextSignedFloat(1) * this.ofs, y + NumReel.rand.nextSignedFloat(1) * this.ofs, 0);
      else
        glTranslatef(x, y, 0);
      glRotatef(od, 1, 0, 0);
      glTranslatef(0, 0, s * 2.4);
      glScalef(s, -s, s);
      let a: number = 1 - fabs((od + 15) / (360 / 10 * 1.5)) / 2;
      if (a < 0)
        a = 0;
      Screen.setColor(a, a, a);
      Letter.drawLetter(n, 2);
      Screen.setColor(a / 2, a / 2, a / 2);
      Letter.drawLetter(n, 3);
      glPopMatrix();
      n--;
      if (n < 0)
        n = 9;
      od += 360 / 10 * 1.5;
      Math.normalizeDeg360(od);
    }
    this.ofs *= 0.95;
  }

  public targetDeg(td: number): void {
    if ((td - this._targetDeg) > 1)
      this.ofs += 0.1;
    return this._targetDeg = td;
  }

  public accelerate(): void {
    this.velRatio = 4;
  }
}

/**
 * Flying indicator that shows the score and the multiplier.
 */
export class NumIndicator extends Actor {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly IndicatorType = {
    SCORE: 0,
    MULTIPLIER: 1
  } as const;
  static readonly FlyingToType = {
    RIGHT: 0,
    BOTTOM: 1
  } as const;
  static rand: Rand;
  static readonly TARGET_Y_MIN: number = -7;
  static readonly TARGET_Y_MAX: number = 7;
  static readonly TARGET_Y_INTERVAL: number = 1;
  static targetY: number;
  // PORT_NOTE[D2TS:struct]: D struct is converted to class for now.
  class Target {
    pos: Vector;
    flyingTo: number;
    initialVelRatio: number;
    size: number;
    n: number;
    cnt: number;
  };
  scoreReel: ScoreReel;
  pos: Vector;
  vel: Vector;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: Vector pos, vel;
  n: number;
  type: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: int n, type;
  size: number;
  cnt: number;
  alpha: number;
  target: Target[];
  targetIdx: number;
  targetNum: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  static {
    rand = new Rand();
    targetY = TARGET_Y_MIN;
  }

  public static setRandSeed(seed: number): void {
    NumIndicator.rand.setSeed(seed);
  }

  public static initTargetY(): void {
    NumIndicator.targetY = NumIndicator.TARGET_Y_MIN;
  }

  public static getTargetY(): number {
    let ty: number = NumIndicator.targetY;
    NumIndicator.targetY += NumIndicator.TARGET_Y_INTERVAL;
    if (NumIndicator.targetY > NumIndicator.TARGET_Y_MAX)
      NumIndicator.targetY = NumIndicator.TARGET_Y_MIN;
    return ty;
  }

  public static decTargetY(): void {
    NumIndicator.targetY -= NumIndicator.TARGET_Y_INTERVAL;
    if (NumIndicator.targetY < NumIndicator.TARGET_Y_MIN)
      NumIndicator.targetY = NumIndicator.TARGET_Y_MAX;
  }

  public constructor() {
    this.pos = new Vector();
    this.vel = new Vector();
    for (const t of this.target) {
      t.pos = new Vector();
      t.initialVelRatio = 0;
      t.size = 0;
    }
    this.targetIdx = this.targetNum = 0;
    this.alpha = 1;
  }

  public init(args: unknown[]): void {
    this.scoreReel = /* D_CAST(ScoreReel) */ args[0];
  }

  public set(n: number, type: IndicatorType, size: number, p: Vector): void {
    this.set(n, type, size, p.x, p.y);
  }

  public set(n: number, type: IndicatorType, size: number, x: number, y: number): void {
    if (exists && this.type == IndicatorType.SCORE) {
      if (this.target[this.targetIdx].flyingTo == FlyingToType.RIGHT)
        NumIndicator.decTargetY();
      this.scoreReel.addReelScore(this.target[this.targetNum - 1].n);
    }
    this.n = n;
    this.type = type;
    this.size = size;
    this.pos.x = x;
    this.pos.y = y;
    this.targetIdx = -1;
    this.targetNum = 0;
    this.alpha = 0.1;
    exists = true;
  }

  public addTarget(x: number, y: number, flyingTo: FlyingToType, initialVelRatio: number, size: number, n: number, cnt: number): void {
    this.target[this.targetNum].pos.x = x;
    this.target[this.targetNum].pos.y = y;
    this.target[this.targetNum].flyingTo = flyingTo;
    this.target[this.targetNum].initialVelRatio = initialVelRatio;
    this.target[this.targetNum].size = size;
    this.target[this.targetNum].n = n;
    this.target[this.targetNum].cnt = cnt;
    this.targetNum++;
  }

  public gotoNextTarget(): void {
    this.targetIdx++;
    if (this.targetIdx > 0)
      SoundManager.playSe("score_up.wav");
    if (this.targetIdx >= this.targetNum) {
      if (this.target[this.targetIdx - 1].flyingTo == FlyingToType.BOTTOM)
        this.scoreReel.addReelScore(this.target[this.targetIdx - 1].n);
      exists = false;
      return;
    }
    switch (this.target[this.targetIdx].flyingTo) {
    case FlyingToType.RIGHT:
      this.vel.x = -0.3 + NumIndicator.rand.nextSignedFloat(0.05);
      this.vel.y = NumIndicator.rand.nextSignedFloat(0.1);
      break;
    case FlyingToType.BOTTOM:
      this.vel.x = NumIndicator.rand.nextSignedFloat(0.1);
      this.vel.y = 0.3 + NumIndicator.rand.nextSignedFloat(0.05);
      NumIndicator.decTargetY();
      break;
    }
    this.vel *= this.target[this.targetIdx].initialVelRatio;
    this.cnt = this.target[this.targetIdx].cnt;
  }

  public move(): void {
    if (this.targetIdx < 0)
      return;
    let tp: Vector = this.target[this.targetIdx].pos;
    switch (this.target[this.targetIdx].flyingTo) {
    case FlyingToType.RIGHT:
      this.vel.x += (tp.x - this.pos.x) * 0.0036;
      this.pos.y += (tp.y - this.pos.y) * 0.1;
      if (fabs(this.pos.y - tp.y) < 0.5)
        this.pos.y += (tp.y - this.pos.y) * 0.33;
      this.alpha += (1 - this.alpha) * 0.03;
      break;
    case FlyingToType.BOTTOM:
      this.pos.x += (tp.x - this.pos.x) * 0.1;
      this.vel.y += (tp.y - this.pos.y) * 0.0036;
      this.alpha *= 0.97;
      break;
    }
    this.vel *= 0.98;
    this.size += (this.target[this.targetIdx].size - this.size) * 0.025;
    this.pos += this.vel;
    let vn: number = /* D_CAST(int) */ ((this.target[this.targetIdx].n - this.n) * 0.2);
    if (vn < 10 && vn > -10)
      this.n = this.target[this.targetIdx].n;
    else
      this.n += vn;
    switch (this.target[this.targetIdx].flyingTo) {
    case FlyingToType.RIGHT:
      if (this.pos.x > tp.x) {
        this.pos.x = tp.x;
        this.vel.x *= -0.05;
      }
      break;
    case FlyingToType.BOTTOM:
      if (this.pos.y < tp.y) {
        this.pos.y = tp.y;
        this.vel.y *= -0.05;
      }
      break;
    }
    this.cnt--;
    if (this.cnt < 0)
      this.gotoNextTarget();
  }

  public draw(): void {
    Screen.setColor(this.alpha, this.alpha, this.alpha);
    switch (this.type) {
    case IndicatorType.SCORE:
      Letter.drawNumSign(this.n, this.pos.x, this.pos.y, this.size, Letter.LINE_COLOR);
      break;
    case IndicatorType.MULTIPLIER:
      Screen.setColor(this.alpha, this.alpha, this.alpha);
      Letter.drawNumSign(this.n, this.pos.x, this.pos.y, this.size, Letter.LINE_COLOR, 33, 3);
      break;
    }
  }
}

export class NumIndicatorPool extends ActorPool<NumIndicator> {
  public constructor(n: number, args: unknown[]) {
    super(n, args);
  }
}
