// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: replay.d,v 1.4 2005/09/11 00:47:40 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.replay;

// D_IMPORT: private import std.stream;
// D_IMPORT: private import abagames.util.sdl.recordableinput;
// D_IMPORT: private import abagames.util.sdl.pad;
// D_IMPORT: private import abagames.util.sdl.twinstick;
// D_IMPORT: private import abagames.util.sdl.mouse;
// D_IMPORT: private import abagames.gr.gamemanager;
// D_IMPORT: private import abagames.gr.mouseandpad;

/**
 * Save/Load a replay data.
 */
export class ReplayData {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly dir: string[] = "replay";
  static readonly VERSION_NUM: number = 11;
  padInputRecord: InputRecord<PadState>;
  twinStickInputRecord: InputRecord<TwinStickState>;
  mouseAndPadInputRecord: InputRecord<MouseAndPadState>;
  seed: number;
  score: number = 0;
  shipTurnSpeed: number;
  shipReverseFire: boolean;
  gameMode: number;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:

  public save(fileName: string[]): void {
    let fd: File = new File;
    fd.create(dir + "/" + fileName);
    fd.write(ReplayData.VERSION_NUM);
    fd.write(this.seed);
    fd.write(this.score);
    fd.write(this.shipTurnSpeed);
    if (this.shipReverseFire)
      fd.write(1);
    else
      fd.write(0);
    fd.write(this.gameMode);
    switch (this.gameMode) {
    case InGameState.GameMode.NORMAL:
      this.padInputRecord.save(fd);
      break;
    case InGameState.GameMode.TWIN_STICK:
    case InGameState.GameMode.DOUBLE_PLAY:
      this.twinStickInputRecord.save(fd);
      break;
    case InGameState.GameMode.MOUSE:
      this.mouseAndPadInputRecord.save(fd);
      break;
    }
    fd.close();
  }

  public load(fileName: string[]): void {
    let fd: File = new File;
    fd.open(dir + "/" + fileName);
    let ver: number;
    fd.read(ver);
    if (ver != ReplayData.VERSION_NUM)
      throw new Error("Wrong version num");
    fd.read(this.seed);
    fd.read(this.score);
    fd.read(this.shipTurnSpeed);
    let srf: number;
    fd.read(srf);
    if (srf == 1)
      this.shipReverseFire = true;
    else
      this.shipReverseFire = false;
    fd.read(this.gameMode);
    switch (this.gameMode) {
    case InGameState.GameMode.NORMAL:
      this.padInputRecord = new InputRecord!(PadState);
      this.padInputRecord.load(fd);
      break;
    case InGameState.GameMode.TWIN_STICK:
    case InGameState.GameMode.DOUBLE_PLAY:
      this.twinStickInputRecord = new InputRecord!(TwinStickState);
      this.twinStickInputRecord.load(fd);
      break;
    case InGameState.GameMode.MOUSE:
      this.mouseAndPadInputRecord = new InputRecord!(MouseAndPadState);
      this.mouseAndPadInputRecord.load(fd);
      break;
    }
    fd.close();
  }
}
