// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: screen.d,v 1.1.1.1 2005/06/18 00:46:00 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.screen;

// D_IMPORT: private import std.math;
// D_IMPORT: private import opengl;
// D_IMPORT: private import openglu;
// D_IMPORT: private import abagames.util.rand;
// D_IMPORT: private import abagames.util.sdl.screen3d;
// D_IMPORT: private import abagames.util.sdl.luminous;

/**
 * Initialize an OpenGL and set the caption.
 * Handle a luminous screen and a viewpoint.
 */
export class Screen extends Screen3D {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  readonly CAPTION: string[] = "Gunroar";
  static rand: Rand;
  static lineWidthBase: number;
  luminousScreen: LuminousScreen;
  _luminosity: number = 0;
  screenShakeCnt: number;
  screenShakeIntense: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  static {
    rand = new Rand();
  }

  public static setRandSeed(seed: number): void {
    Screen.rand.setSeed(seed);
  }

  public constructor() {
    this._luminosity = 0;
    this.screenShakeCnt = 0;
    this.screenShakeIntense = 0;
  }

  protected override init(): void {
    setCaption(this.CAPTION);
    glLineWidth(1);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE);
    glEnable(GL_BLEND);
    glEnable(GL_LINE_SMOOTH);
    glDisable(GL_TEXTURE_2D);
    glDisable(GL_COLOR_MATERIAL);
    glDisable(GL_CULL_FACE);
    glDisable(GL_DEPTH_TEST);
    glDisable(GL_LIGHTING);
    setClearColor(0, 0, 0, 1);
    if (this._luminosity > 0) {
      this.luminousScreen = new LuminousScreen();
      this.luminousScreen.init(this._luminosity, width, height);
    } else {
      this.luminousScreen = null;
    }
    this.screenResized();
  }

  public override close(): void {
    if (this.luminousScreen)
      this.luminousScreen.close();
  }

  public startRenderToLuminousScreen(): boolean {
    if (!this.luminousScreen)
      return false;
    this.luminousScreen.startRender();
    return true;
  }

  public endRenderToLuminousScreen(): void {
    if (this.luminousScreen)
      this.luminousScreen.endRender();
  }

  public drawLuminous(): void {
    if (this.luminousScreen)
      this.luminousScreen.draw();
  }

  public override resized(width: number, height: number): void {
    if (this.luminousScreen)
      this.luminousScreen.resized(width, height);
    super.resized(width, height);
  }

  public override screenResized(): void {
    super.screenResized();
    let lw: number = (/* D_CAST(float) */ width / 640 + /* D_CAST(float) */ height / 480) / 2;
    if (lw < 1)
      lw = 1;
    else if (lw > 4)
      lw = 4;
    Screen.lineWidthBase = lw;
    Screen.lineWidth(1);
  }

  public static lineWidth(w: number): void {
    glLineWidth(/* D_CAST(int) */ (Screen.lineWidthBase * w));
  }

  public override clear(): void {
    glClear(GL_COLOR_BUFFER_BIT);
  }

  public static viewOrthoFixed(): void {
    glMatrixMode(GL_PROJECTION);
    glPushMatrix();
    glLoadIdentity();
    glOrtho(0, 640, 480, 0, -1, 1);
    glMatrixMode(GL_MODELVIEW);
    glPushMatrix();
    glLoadIdentity();
  }

  public static viewPerspective(): void {
    glMatrixMode(GL_PROJECTION);
    glPopMatrix();
    glMatrixMode(GL_MODELVIEW);
    glPopMatrix();
  }

  public setEyepos(): void {
    let ex: number;
    let ey: number;
    let ez: number;
    // PORT_NOTE[D2TS:multi-decl]:
    // reason: Split D multi-variable declaration into one-per-line.
    // original: float ex, ey, ez;
    let lx: number;
    let ly: number;
    let lz: number;
    // PORT_NOTE[D2TS:multi-decl]:
    // reason: Split D multi-variable declaration into one-per-line.
    // original: float lx, ly, lz;
    ex = ey = 0;
    ez = 13.0;
    lx = ly = lz = 0;
    if (this.screenShakeCnt > 0) {
      let mx: number = Screen.rand.nextSignedFloat(this.screenShakeIntense * (this.screenShakeCnt + 4));
      let my: number = Screen.rand.nextSignedFloat(this.screenShakeIntense * (this.screenShakeCnt + 4));
      ex += mx;
      ey += my;
      lx += mx;
      ly += my;
    }
    gluLookAt(ex, ey, ez, lx, ly, lz, 0, 1, 0);
  }

  public setScreenShake(cnt: number, its: number): void {
    this.screenShakeCnt = cnt;
    this.screenShakeIntense = its;
  }

  public move(): void {
    if (this.screenShakeCnt > 0)
      this.screenShakeCnt--;
  }

  public luminosity(v: number): number {
    return this._luminosity = v;
  }

  public static setColorForced(r: number, g: number, b: number, a: number = 1): void {
    glColor4(r, g, b, a);
  }
}
