// @ts-nocheck
// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: shape.d,v 1.1.1.1 2005/06/18 00:46:00 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.shape;

// D_IMPORT: private import std.math;
// D_IMPORT: private import opengl;
// D_IMPORT: private import abagames.util.vector;
// D_IMPORT: private import abagames.util.rand;
// D_IMPORT: private import abagames.util.sdl.shape;
// D_IMPORT: private import abagames.gr.screen;
// D_IMPORT: private import abagames.gr.particle;

/**
 * Shape of a ship/platform/turret/bridge.
 */
export class BaseShape extends DrawableShape {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly ShapeType = {
    SHIP: 0,
    SHIP_ROUNDTAIL: 1,
    SHIP_SHADOW: 2,
    PLATFORM: 3,
    TURRET: 4,
    BRIDGE: 5,
    SHIP_DAMAGED: 6,
    SHIP_DESTROYED: 7,
    PLATFORM_DAMAGED: 8,
    PLATFORM_DESTROYED: 9,
    TURRET_DAMAGED: 10,
    TURRET_DESTROYED: 11
  } as const;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly POINT_NUM: number = 16;
  static rand: Rand;
  static wakePos: Vector;
  size: number;
  distRatio: number;
  spinyRatio: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float size, distRatio, spinyRatio;
  type: number;
  r: number;
  g: number;
  b: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float r, g, b;
  static readonly PILLAR_POINT_NUM: number = 8;
  pillarPos: Vector[];
  _pointPos: Vector[];
  _pointDeg: number[];

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  static {
    rand = new Rand();
    wakePos = new Vector();
  }

  public static setRandSeed(seed: number): void {
    BaseShape.rand.setSeed(seed);
  }

  public constructor(size: number, distRatio: number, spinyRatio: number, type: number, r: number, g: number, b: number) {
    this.size = size;
    this.distRatio = distRatio;
    this.spinyRatio = spinyRatio;
    this.type = type;
    this.r = r;
    this.g = g;
    this.b = b;
    super();
  }

  public override createDisplayList(): void {
    let height: number = this.size * 0.5;
    let z: number = 0;
    let sz: number = 1;
    if (this.type == ShapeType.BRIDGE)
      z += height;
    if (this.type != ShapeType.SHIP_DESTROYED)
      Screen.setColor(this.r, this.g, this.b);
    glBegin(GL_LINE_LOOP);
    if (this.type != ShapeType.BRIDGE)
      this.createLoop(sz, z, false, true);
    else
      this.createSquareLoop(sz, z, false, true);
    glEnd();
    if (this.type != ShapeType.SHIP_SHADOW && this.type != ShapeType.SHIP_DESTROYED &&
        this.type != ShapeType.PLATFORM_DESTROYED && this.type != ShapeType.TURRET_DESTROYED) {
      Screen.setColor(this.r * 0.4, this.g * 0.4, this.b * 0.4);
      glBegin(GL_TRIANGLE_FAN);
      this.createLoop(sz, z, true);
      glEnd();
    }
    switch (this.type) {
    case ShapeType.SHIP:
    case ShapeType.SHIP_ROUNDTAIL:
    case ShapeType.SHIP_SHADOW:
    case ShapeType.SHIP_DAMAGED:
    case ShapeType.SHIP_DESTROYED:
      if (this.type != ShapeType.SHIP_DESTROYED)
        Screen.setColor(this.r * 0.4, this.g * 0.4, this.b * 0.4);
      for (let i = 0; i < 3; i++) {
        z -= height / 4;
        sz -= 0.2;
        glBegin(GL_LINE_LOOP);
        this.createLoop(sz, z);
        glEnd();
      }
      break;
    case ShapeType.PLATFORM:
    case ShapeType.PLATFORM_DAMAGED:
    case ShapeType.PLATFORM_DESTROYED:
      Screen.setColor(this.r * 0.4, this.g * 0.4, this.b * 0.4);
      for (let i = 0; i < 3; i++) {
        z -= height / 3;
        for (const pp of this.pillarPos) {
          glBegin(GL_LINE_LOOP);
          this.createPillar(pp, this.size * 0.2, z);
          glEnd();
        }
      }
      break;
    case ShapeType.BRIDGE:
    case ShapeType.TURRET:
    case ShapeType.TURRET_DAMAGED:
      Screen.setColor(this.r * 0.6, this.g * 0.6, this.b * 0.6);
      z += height;
      sz -= 0.33;
      glBegin(GL_LINE_LOOP);
      if (this.type == ShapeType.BRIDGE)
        this.createSquareLoop(sz, z);
      else
        this.createSquareLoop(sz, z / 2, false, 3);
      glEnd();
      Screen.setColor(this.r * 0.25, this.g * 0.25, this.b * 0.25);
      glBegin(GL_TRIANGLE_FAN);
      if (this.type == ShapeType.BRIDGE)
        this.createSquareLoop(sz, z, true);
      else
        this.createSquareLoop(sz, z / 2, true, 3);
      glEnd();
      break;
    case ShapeType.TURRET_DESTROYED:
      break;
    }
  }

  private createLoop(s: number, z: number, backToFirst: boolean = false, record: boolean = false): void {
    let d: number = 0;
    let pn: number;
    let firstPoint: boolean = true;
    let fpx: number;
    let fpy: number;
    // PORT_NOTE[D2TS:multi-decl]:
    // reason: Split D multi-variable declaration into one-per-line.
    // original: float fpx, fpy;
    for (let i = 0; i < BaseShape.POINT_NUM; i++) {
      if (this.type != ShapeType.SHIP && this.type != ShapeType.SHIP_DESTROYED && this.type != ShapeType.SHIP_DAMAGED &&
          i > BaseShape.POINT_NUM * 2 / 5 && i <= BaseShape.POINT_NUM * 3 / 5)
        continue;
      if ((this.type == ShapeType.TURRET || this.type == ShapeType.TURRET_DAMAGED || this.type == ShapeType.TURRET_DESTROYED) &&
          (i <= BaseShape.POINT_NUM / 5 || i > BaseShape.POINT_NUM * 4 / 5))
        continue;
      d = PI * 2 * i / BaseShape.POINT_NUM;
      let cx: number = sin(d) * this.size * s * (1 - this.distRatio);
      let cy: number = cos(d) * this.size * s;
      let sx: number;
      let sy: number;
      // PORT_NOTE[D2TS:multi-decl]:
      // reason: Split D multi-variable declaration into one-per-line.
      // original: float sx, sy;
      if (i == BaseShape.POINT_NUM / 4 || i == BaseShape.POINT_NUM / 4 * 3)
        sy = 0;
      else
        sy = 1 / (1 + fabs(tan(d)));
      assert(!Number.isNaN(sy) && !Number.isNaN(0));
      sx = 1 - sy;
      if (i >= BaseShape.POINT_NUM / 2)
        sx *= -1;
      if (i >= BaseShape.POINT_NUM / 4 && i <= BaseShape.POINT_NUM / 4 * 3)
        sy *= -1;
      sx *= this.size * s * (1 - this.distRatio);
      sy *= this.size * s;
      let px: number = cx * (1 - this.spinyRatio) + sx * this.spinyRatio;
      let py: number = cy * (1 - this.spinyRatio) + sy * this.spinyRatio;
      glVertex3(px, py, z);
      if (backToFirst && firstPoint) {
        fpx = px;
        fpy = py;
        firstPoint = false;
      }
      if (record) {
        if (i == BaseShape.POINT_NUM / 8 || i == BaseShape.POINT_NUM / 8 * 3 ||
            i == BaseShape.POINT_NUM / 8 * 5 || i == BaseShape.POINT_NUM / 8 * 7)
          pillarPos.push(new Vector(px * 0.8, py * 0.8)); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
        _pointPos.push(new Vector(px, py)); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
        _pointDeg.push(d); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
      }
    }
    if (backToFirst)
      glVertex3(fpx, fpy, z);
  }

  private createSquareLoop(s: number, z: number, backToFirst: boolean = false, yRatio: number = 1): void {
    let d: number;
    let pn: number;
    if (backToFirst)
      pn = 4;
    else
      pn = 3;
    for (let i = 0; i <= pn; i++) {
      d = PI * 2 * i / 4 + PI / 4;
      let px: number = sin(d) * this.size * s;
      let py: number = cos(d) * this.size * s;
      if (py > 0)
        py *= yRatio;
      glVertex3(px, py, z);
    }
  }

  private createPillar(p: Vector, s: number, z: number): void {
    let d: number;
    for (let i = 0; i < BaseShape.PILLAR_POINT_NUM; i++) {
      d = PI * 2 * i / BaseShape.PILLAR_POINT_NUM;
      glVertex3(sin(d) * s + p.x, cos(d) * s + p.y, z);
    }
  }

  public addWake(wakes: WakePool, pos: Vector, deg: number, spd: number, sr: number = 1): void {
    let sp: number = spd;
    if (sp > 0.1)
      sp = 0.1;
    let sz: number = this.size;
    if (sz > 10)
      sz = 10;
    BaseShape.wakePos.x = pos.x + sin(deg + PI / 2 + 0.7) * this.size * 0.5 * sr;
    BaseShape.wakePos.y = pos.y + cos(deg + PI / 2 + 0.7) * this.size * 0.5 * sr;
    let w: Wake = wakes.getInstanceForced();
    w.set(BaseShape.wakePos, deg + PI - 0.2 + BaseShape.rand.nextSignedFloat(0.1), sp, 40, sz * 32 * sr);
    BaseShape.wakePos.x = pos.x + sin(deg - PI / 2 - 0.7) * this.size * 0.5 * sr;
    BaseShape.wakePos.y = pos.y + cos(deg - PI / 2 - 0.7) * this.size * 0.5 * sr;
    w = wakes.getInstanceForced();
    w.set(BaseShape.wakePos, deg + PI + 0.2 + BaseShape.rand.nextSignedFloat(0.1), sp, 40, sz * 32 * sr);
  }

  public pointPos(): Vector[] {
    return this._pointPos;
  }

  public pointDeg(): number[] {
    return this._pointDeg;
  }

  public checkShipCollision(x: number, y: number, deg: number, sr: number = 1): boolean {
    let cs: number = this.size * (1 - this.distRatio) * 1.1 * sr;
    if (this.dist(x, y, 0, 0) < cs)
      return true;
    let ofs: number = 0;
    for (;;) {
      ofs += cs;
      cs *= this.distRatio;
      if (cs < 0.2)
        return false;
      if (this.dist(x, y, sin(deg) * ofs, cos(deg) * ofs) < cs ||
          this.dist(x, y, -sin(deg) * ofs, -cos(deg) * ofs) < cs)
        return true;
    }
  }

  private dist(x: number, y: number, px: number, py: number): number {
    let ax: number = fabs(x - px);
    let ay: number = fabs(y - py);
    if (ax > ay)
      return ax + ay / 2;
    else
      return ay + ax / 2;
  }
}

export class CollidableBaseShape extends BaseShape implements Collidable {
  // PORT_NOTE[D2TS:d-specific-feature]:
  // reason: D-specific feature requires manual rewrite.
  // original: mixin CollidableImpl;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  _collision: Vector;

  public constructor(size: number, distRatio: number, spinyRatio: number, type: number, r: number, g: number, b: number) {
    super(size, distRatio, spinyRatio, type, r, g, b);
    _collision = new Vector(size / 2, size / 2);
  }

  public collision(): Vector {
    return _collision;
  }
}

export class TurretShape extends ResizableDrawable {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly TurretShapeType = {
    NORMAL: 0,
    DAMAGED: 1,
    DESTROYED: 2
  } as const;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static shapes: BaseShape[];

  public static init(): void {
    shapes.push(new CollidableBaseShape(1, 0, 0, BaseShape.ShapeType.TURRET, 1, 0.8, 0.8)); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
    shapes.push(new BaseShape(1, 0, 0, BaseShape.ShapeType.TURRET_DAMAGED, 0.9, 0.9, 1)); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
    shapes.push(new BaseShape(1, 0, 0, BaseShape.ShapeType.TURRET_DESTROYED, 0.8, 0.33, 0.66)); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
  }

  public static close(): void {
    for (const s of TurretShape.shapes)
      s.close();
  }

  public constructor(t: number) {
    shape = TurretShape.shapes[t];
  }
}

export class EnemyShape extends ResizableDrawable {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly EnemyShapeType = {
    SMALL: 0,
    SMALL_DAMAGED: 1,
    SMALL_BRIDGE: 2,
    MIDDLE: 3,
    MIDDLE_DAMAGED: 4,
    MIDDLE_DESTROYED: 5,
    MIDDLE_BRIDGE: 6,
    PLATFORM: 7,
    PLATFORM_DAMAGED: 8,
    PLATFORM_DESTROYED: 9,
    PLATFORM_BRIDGE: 10
  } as const;
  static readonly MIDDLE_COLOR_R: number = 1;
  static readonly MIDDLE_COLOR_G: number = 0.6;
  static readonly MIDDLE_COLOR_B: number = 0.5;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static shapes: BaseShape[];

  public static init(): void {
    EnemyShape.shapes.push(new BaseShape(1, 0.5, 0.1, BaseShape.ShapeType.SHIP, 0.9, 0.7, 0.5));
    EnemyShape.shapes.push(new BaseShape(1, 0.5, 0.1, BaseShape.ShapeType.SHIP_DAMAGED, 0.5, 0.5, 0.9));
    EnemyShape.shapes.push(new CollidableBaseShape(0.66, 0, 0, BaseShape.ShapeType.BRIDGE, 1, 0.2, 0.3));
    EnemyShape.shapes.push(new BaseShape(1, 0.7, 0.33, BaseShape.ShapeType.SHIP, EnemyShape.MIDDLE_COLOR_R, EnemyShape.MIDDLE_COLOR_G, EnemyShape.MIDDLE_COLOR_B));
    EnemyShape.shapes.push(new BaseShape(1, 0.7, 0.33, BaseShape.ShapeType.SHIP_DAMAGED, 0.5, 0.5, 0.9));
    EnemyShape.shapes.push(new BaseShape(1, 0.7, 0.33, BaseShape.ShapeType.SHIP_DESTROYED, 0, 0, 0));
    EnemyShape.shapes.push(new CollidableBaseShape(0.66, 0, 0, BaseShape.ShapeType.BRIDGE, 1, 0.2, 0.3));
    EnemyShape.shapes.push(new BaseShape(1, 0, 0, BaseShape.ShapeType.PLATFORM, 1, 0.6, 0.7));
    EnemyShape.shapes.push(new BaseShape(1, 0, 0, BaseShape.ShapeType.PLATFORM_DAMAGED, 0.5, 0.5, 0.9));
    EnemyShape.shapes.push(new BaseShape(1, 0, 0, BaseShape.ShapeType.PLATFORM_DESTROYED, 1, 0.6, 0.7));
    EnemyShape.shapes.push(new CollidableBaseShape(0.5, 0, 0, BaseShape.ShapeType.BRIDGE, 1, 0.2, 0.3));
  }

  public static close(): void {
    for (const s of EnemyShape.shapes)
      s.close();
  }

  public constructor(t: number) {
    shape = EnemyShape.shapes[t];
  }

  public addWake(wakes: WakePool, pos: Vector, deg: number, sp: number): void {
    (/* D_CAST(BaseShape) */ shape).addWake(wakes, pos, deg, sp, size);
  }

  public checkShipCollision(x: number, y: number, deg: number): boolean {
    return (/* D_CAST(BaseShape) */ shape).checkShipCollision(x, y, deg, size);
  }
}

export class BulletShape extends ResizableDrawable {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly BulletShapeType = {
    NORMAL: 0,
    SMALL: 1,
    MOVING_TURRET: 2,
    DESTRUCTIVE: 3
  } as const;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static shapes: DrawableShape[];

  public static init(): void {
    shapes.push(new NormalBulletShape); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
    shapes.push(new SmallBulletShape); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
    shapes.push(new MovingTurretBulletShape); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
    shapes.push(new DestructiveBulletShape); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
  }

  public static close(): void {
    for (const s of BulletShape.shapes)
      s.close();
  }

  public set(t: number): void {
    shape = BulletShape.shapes[t];
  }
}

export class NormalBulletShape extends DrawableShape {
  public override createDisplayList(): void {
    glDisable(GL_BLEND);
    Screen.setColor(1, 1, 0.3);
    glBegin(GL_LINE_STRIP);
    glVertex3(0.2, -0.25, 0.2);
    glVertex3(0, 0.33, 0);
    glVertex3(-0.2, -0.25, -0.2);
    glEnd();
    glBegin(GL_LINE_STRIP);
    glVertex3(-0.2, -0.25, 0.2);
    glVertex3(0, 0.33, 0);
    glVertex3(0.2, -0.25, -0.2);
    glEnd();
    glEnable(GL_BLEND);
    Screen.setColor(0.5, 0.2, 0.1);
    glBegin(GL_TRIANGLE_FAN);
    glVertex3(0, 0.33, 0);
    glVertex3(0.2, -0.25, 0.2);
    glVertex3(-0.2, -0.25, 0.2);
    glVertex3(-0.2, -0.25, -0.2);
    glVertex3(0.2, -0.25, -0.2);
    glVertex3(0.2, -0.25, 0.2);
    glEnd();
  }
}

export class SmallBulletShape extends DrawableShape {
  public override createDisplayList(): void {
    glDisable(GL_BLEND);
    Screen.setColor(0.6, 0.9, 0.3);
    glBegin(GL_LINE_STRIP);
    glVertex3(0.25, -0.25, 0.25);
    glVertex3(0, 0.33, 0);
    glVertex3(-0.25, -0.25, -0.25);
    glEnd();
    glBegin(GL_LINE_STRIP);
    glVertex3(-0.25, -0.25, 0.25);
    glVertex3(0, 0.33, 0);
    glVertex3(0.25, -0.25, -0.25);
    glEnd();
    glEnable(GL_BLEND);
    Screen.setColor(0.2, 0.4, 0.1);
    glBegin(GL_TRIANGLE_FAN);
    glVertex3(0, 0.33, 0);
    glVertex3(0.25, -0.25, 0.25);
    glVertex3(-0.25, -0.25, 0.25);
    glVertex3(-0.25, -0.25, -0.25);
    glVertex3(0.25, -0.25, -0.25);
    glVertex3(0.25, -0.25, 0.25);
    glEnd();
  }
}

export class MovingTurretBulletShape extends DrawableShape {
  public override createDisplayList(): void {
    glDisable(GL_BLEND);
    Screen.setColor(0.7, 0.5, 0.9);
    glBegin(GL_LINE_STRIP);
    glVertex3(0.25, -0.25, 0.25);
    glVertex3(0, 0.33, 0);
    glVertex3(-0.25, -0.25, -0.25);
    glEnd();
    glBegin(GL_LINE_STRIP);
    glVertex3(-0.25, -0.25, 0.25);
    glVertex3(0, 0.33, 0);
    glVertex3(0.25, -0.25, -0.25);
    glEnd();
    glEnable(GL_BLEND);
    Screen.setColor(0.2, 0.2, 0.3);
    glBegin(GL_TRIANGLE_FAN);
    glVertex3(0, 0.33, 0);
    glVertex3(0.25, -0.25, 0.25);
    glVertex3(-0.25, -0.25, 0.25);
    glVertex3(-0.25, -0.25, -0.25);
    glVertex3(0.25, -0.25, -0.25);
    glVertex3(0.25, -0.25, 0.25);
    glEnd();
  }
}

export class DestructiveBulletShape extends DrawableShape implements Collidable {
  // PORT_NOTE[D2TS:d-specific-feature]:
  // reason: D-specific feature requires manual rewrite.
  // original: mixin CollidableImpl;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  _collision: Vector;

  public override createDisplayList(): void {
    glDisable(GL_BLEND);
    Screen.setColor(0.9, 0.9, 0.6);
    glBegin(GL_LINE_LOOP);
    glVertex3(0.2, 0, 0);
    glVertex3(0, 0.4, 0);
    glVertex3(-0.2, 0, 0);
    glVertex3(0, -0.4, 0);
    glEnd();
    glEnable(GL_BLEND);
    Screen.setColor(0.7, 0.5, 0.4);
    glBegin(GL_TRIANGLE_FAN);
    glVertex3(0.2, 0, 0);
    glVertex3(0, 0.4, 0);
    glVertex3(-0.2, 0, 0);
    glVertex3(0, -0.4, 0);
    glEnd();
    _collision = new Vector(0.4, 0.4);
  }

  public collision(): Vector {
    return _collision;
  }
}

export class CrystalShape extends DrawableShape {
  public override createDisplayList(): void {
    Screen.setColor(0.6, 1, 0.7);
    glBegin(GL_LINE_LOOP);
    glVertex3(-0.2, 0.2, 0);
    glVertex3(0.2, 0.2, 0);
    glVertex3(0.2, -0.2, 0);
    glVertex3(-0.2, -0.2, 0);
    glEnd();
  }
}

export class ShieldShape extends DrawableShape {
  public override createDisplayList(): void {
    Screen.setColor(0.5, 0.5, 0.7);
    glBegin(GL_LINE_LOOP);
    let d: number = 0;
    for (let i = 0; i < 8; i++) {
      glVertex3(sin(d), cos(d), 0);
      d += PI / 4;
    }
    glEnd();
    glBegin(GL_TRIANGLE_FAN);
    Screen.setColor(0, 0, 0);
    glVertex3(0, 0, 0);
    d = 0;
    Screen.setColor(0.3, 0.3, 0.5);
    for (let i = 0; i < 9; i++) {
      glVertex3(sin(d), cos(d), 0);
      d += PI / 4;
    }
    glEnd();
  }
}
