// @ts-nocheck
// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: ship.d,v 1.4 2005/09/11 00:47:40 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.ship;

// D_IMPORT: private import std.math;
// D_IMPORT: private import opengl;
// D_IMPORT: private import abagames.util.vector;
// D_IMPORT: private import abagames.util.rand;
// D_IMPORT: private import abagames.util.math;
// D_IMPORT: private import abagames.util.sdl.pad;
// D_IMPORT: private import abagames.util.sdl.twinstick;
// D_IMPORT: private import abagames.util.sdl.mouse;
// D_IMPORT: private import abagames.util.sdl.recordableinput;
// D_IMPORT: private import abagames.util.sdl.shape;
// D_IMPORT: private import abagames.gr.field;
// D_IMPORT: private import abagames.gr.gamemanager;
// D_IMPORT: private import abagames.gr.screen;
// D_IMPORT: private import abagames.gr.particle;
// D_IMPORT: private import abagames.gr.letter;
// D_IMPORT: private import abagames.gr.shot;
// D_IMPORT: private import abagames.gr.enemy;
// D_IMPORT: private import abagames.gr.stagemanager;
// D_IMPORT: private import abagames.gr.soundmanager;
// D_IMPORT: private import abagames.gr.prefmanager;
// D_IMPORT: private import abagames.gr.shape;
// D_IMPORT: private import abagames.gr.mouseandpad;

/**
 * Player's ship.
 */
export class Ship {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly SCROLL_SPEED_BASE: number = 0.01;
  static readonly SCROLL_SPEED_MAX: number = 0.1;
  static readonly SCROLL_START_Y: number = 2.5;
  field: Field;
  boat: Boat[];
  gameMode: number;
  boatNum: number;
  gameState: InGameState;
  scrollSpeed: number;
  _scrollSpeedBase: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float scrollSpeed, _scrollSpeedBase;
  _midstPos: Vector;
  _higherPos: Vector;
  _lowerPos: Vector;
  _nearPos: Vector;
  _nearVel: Vector;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: Vector _midstPos, _higherPos, _lowerPos, _nearPos, _nearVel;
  bridgeShape: BaseShape;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor(pad: Pad, twinStick: TwinStick, mouse: Mouse, mouseAndPad: RecordableMouseAndPad, field: Field, screen: Screen, sparks: SparkPool, smokes: SmokePool, fragments: FragmentPool, wakes: WakePool) {
    this.field = field;
    Boat.init();
    let i: number = 0;
    for (const b of this.boat) {
      b = new Boat(i, this, pad, twinStick, mouse, mouseAndPad,
                   field, screen, sparks, smokes, fragments, wakes);
      i++;
    }
    this.boatNum = 1;
    this.scrollSpeed = this._scrollSpeedBase = Ship.SCROLL_SPEED_BASE;
    this._midstPos = new Vector();
    this._higherPos = new Vector();
    this._lowerPos = new Vector();
    this._nearPos = new Vector();
    this._nearVel = new Vector();
    this.bridgeShape = new BaseShape(0.3, 0.2, 0.1, BaseShape.ShapeType.BRIDGE, 0.3, 0.7, 0.7);
  }

  public setRandSeed(seed: number): void {
    Boat.setRandSeed(seed);
  }

  public close(): void {
    for (const b of this.boat)
      b.close();
  }

  public setShots(shots: ShotPool): void {
    for (const b of this.boat)
      b.setShots(shots);
  }

  public setEnemies(enemies: EnemyPool): void {
    for (const b of this.boat)
      b.setEnemies(enemies);
  }

  public setStageManager(stageManager: StageManager): void {
    for (const b of this.boat)
      b.setStageManager(stageManager);
  }

  public setGameState(gameState: InGameState): void {
    this.gameState = gameState;
    for (const b of this.boat)
      b.setGameState(gameState);
  }

  public start(gameMode: number): void {
    this.gameMode = gameMode;
    if (gameMode == InGameState.GameMode.DOUBLE_PLAY)
      this.boatNum = 2;
    else
      this.boatNum = 1;
    this._scrollSpeedBase = Ship.SCROLL_SPEED_BASE;
    for (let i = 0; i < this.boatNum; i++)
      this.boat[i].start(gameMode);
    this._midstPos.x = this._midstPos.y = 0;
    this._higherPos.x = this._higherPos.y = 0;
    this._lowerPos.x = this._lowerPos.y = 0;
    this._nearPos.x = this._nearPos.y = 0;
    this._nearVel.x = this._nearVel.y = 0;
    this.restart();
  }

  public restart(): void {
    this.scrollSpeed = this._scrollSpeedBase;
    for (let i = 0; i < this.boatNum; i++)
      this.boat[i].restart();
  }

  public move(): void {
    this.field.scroll(this.scrollSpeed);
    let sf: number = false;
    for (let i = 0; i < this.boatNum; i++) {
      this.boat[i].move();
      if (this.boat[i].hasCollision &&
          this.boat[i].pos.x > this.field.size.x / 3 && this.boat[i].pos.y < -this.field.size.y / 4 * 3)
        sf = true;
    }
    if (sf)
        this.gameState.shrinkScoreReel();
    if (higherPos.y >= Ship.SCROLL_START_Y)
      this.scrollSpeed += (Ship.SCROLL_SPEED_MAX - this.scrollSpeed) * 0.1;
    else
      this.scrollSpeed += (this._scrollSpeedBase - this.scrollSpeed) * 0.1;
    this._scrollSpeedBase += (Ship.SCROLL_SPEED_MAX - this._scrollSpeedBase) * 0.00001;
  }

  public checkBulletHit(p: Vector, pp: Vector): boolean {
    for (let i = 0; i < this.boatNum; i++)
      if (this.boat[i].checkBulletHit(p, pp))
        return true;
    return false;
  }

  public clearBullets(): void {
    this.gameState.clearBullets();
  }

  public destroyed(): void {
    for (let i = 0; i < this.boatNum; i++)
      this.boat[i].destroyedBoat();
  }

  public draw(): void {
    for (let i = 0; i < this.boatNum; i++)
      this.boat[i].draw();
    if (this.gameMode == InGameState.GameMode.DOUBLE_PLAY && this.boat[0].hasCollision) {
      Screen.setColor(0.5, 0.5, 0.9, 0.8);
      glBegin(GL_LINE_STRIP);
      glVertex2(this.boat[0].pos.x, this.boat[0].pos.y);
      Screen.setColor(0.5, 0.5, 0.9, 0.3);
      glVertex2(midstPos.x, midstPos.y);
      Screen.setColor(0.5, 0.5, 0.9, 0.8);
      glVertex2(this.boat[1].pos.x, this.boat[1].pos.y);
      glEnd();
      glPushMatrix();
      Screen.glTranslate(midstPos);
      glRotatef(-degAmongBoats * 180 / PI, 0, 0, 1);
      this.bridgeShape.draw();
      glPopMatrix();
    }
  }

  public drawFront(): void {
    for (let i = 0; i < this.boatNum; i++)
      this.boat[i].drawFront();
  }
  
  public drawShape(): void {
    this.boat[0].drawShape();
  }

  public scrollSpeedBase(): number {
    return this._scrollSpeedBase;
  }

  public setReplayMode(turnSpeed: number, reverseFire: boolean): void {
    for (const b of this.boat)
      b.setReplayMode(turnSpeed, reverseFire);
  }

  public unsetReplayMode(): void {
    for (const b of this.boat)
      b.unsetReplayMode();
  }

  public replayMode(): boolean {
    return this.boat[0].replayMode();
  }

  public midstPos(): Vector {
    this._midstPos.x = this._midstPos.y = 0;
    for (let i = 0; i < this.boatNum; i++) {
      this._midstPos.x += this.boat[i].pos.x;
      this._midstPos.y += this.boat[i].pos.y;
    }
    this._midstPos /= this.boatNum;
    return this._midstPos;
  }

  public higherPos(): Vector {
    this._higherPos.y = -99999;
    for (let i = 0; i < this.boatNum; i++) {
      if (this.boat[i].pos.y > this._higherPos.y) {
        this._higherPos.x = this.boat[i].pos.x;
        this._higherPos.y = this.boat[i].pos.y;
      }
    }
    return this._higherPos;
  }

  public lowerPos(): Vector {
    this._lowerPos.y = 99999;
    for (let i = 0; i < this.boatNum; i++) {
      if (this.boat[i].pos.y < this._lowerPos.y) {
        this._lowerPos.x = this.boat[i].pos.x;
        this._lowerPos.y = this.boat[i].pos.y;
      }
    }
    return this._lowerPos;
  }

  public nearPos(p: Vector): Vector {
    let dist: number = 99999;
    for (let i = 0; i < this.boatNum; i++) {
      if (this.boat[i].pos.dist(p) < dist) {
        dist = this.boat[i].pos.dist(p);
        this._nearPos.x = this.boat[i].pos.x;
        this._nearPos.y = this.boat[i].pos.y;
      }
    }
    return this._nearPos;
  }

  public nearVel(p: Vector): Vector {
    let dist: number = 99999;
    for (let i = 0; i < this.boatNum; i++) {
      if (this.boat[i].pos.dist(p) < dist) {
        dist = this.boat[i].pos.dist(p);
        this._nearVel.x = this.boat[i].vel.x;
        this._nearVel.y = this.boat[i].vel.y;
      }
    }
    return this._nearVel;
  }

  public distAmongBoats(): number {
    return this.boat[0].pos.dist(this.boat[1].pos);
  }

  public degAmongBoats(): number {
    if (distAmongBoats < 0.1)
      return 0;
    else
      return atan2(this.boat[0].pos.x - this.boat[1].pos.x, this.boat[0].pos.y - this.boat[1].pos.y);
  }
}

export class Boat {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly RESTART_CNT: number = 300;
  static readonly INVINCIBLE_CNT: number = 228;
  static readonly HIT_WIDTH: number = 0.02;
  static readonly FIRE_INTERVAL: number = 2;
  static readonly FIRE_INTERVAL_MAX: number = 4;
  static readonly FIRE_LANCE_INTERVAL: number = 15;
  static readonly SPEED_BASE: number = 0.15;
  static readonly TURN_RATIO_BASE: number = 0.2;
  static readonly SLOW_TURN_RATIO: number = 0;
  static readonly TURN_CHANGE_RATIO: number = 0.5;
  static rand: Rand;
  static padInput: PadState;
  static stickInput: TwinStickState;
  static mouseInput: MouseState;
  pad: RecordablePad;
  twinStick: RecordableTwinStick;
  mouse: RecordableMouse;
  mouseAndPad: RecordableMouseAndPad;
  field: Field;
  screen: Screen;
  shots: ShotPool;
  sparks: SparkPool;
  smokes: SmokePool;
  fragments: FragmentPool;
  wakes: WakePool;
  enemies: EnemyPool;
  stageManager: StageManager;
  gameState: InGameState;
  _pos: Vector;
  firePos: Vector;
  deg: number;
  speed: number;
  turnRatio: number;
  _shape: BaseShape;
  bridgeShape: BaseShape;
  fireCnt: number;
  fireSprCnt: number;
  fireInterval: number;
  fireSprDeg: number;
  fireLanceCnt: number;
  fireDeg: number;
  aPressed: boolean;
  bPressed: boolean;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: bool aPressed, bPressed;
  cnt: number;
  onBlock: boolean;
  _vel: Vector;
  refVel: Vector;
  shieldCnt: number;
  shieldShape: ShieldShape;
  _replayMode: boolean;
  turnSpeed: number;
  reverseFire: boolean;
  gameMode: number;
  vx: number;
  vy: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float vx, vy;
  idx: number;
  ship: Ship;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public static init(): void {
    Boat.rand = new Rand();
  }

  public static setRandSeed(seed: number): void {
    Boat.rand.setSeed(seed);
  }

  public constructor(idx: number, ship: Ship, pad: Pad, twinStick: TwinStick, mouse: Mouse, mouseAndPad: RecordableMouseAndPad, field: Field, screen: Screen, sparks: SparkPool, smokes: SmokePool, fragments: FragmentPool, wakes: WakePool) {
    this.idx = idx;
    this.ship = ship;
    this.pad = /* D_CAST(RecordablePad) */ pad;
    this.twinStick = /* D_CAST(RecordableTwinStick) */ twinStick;
    this.mouse = /* D_CAST(RecordableMouse) */ mouse;
    this.mouseAndPad = mouseAndPad;
    this.field = field;
    this.screen = screen;
    this.sparks = sparks;
    this.smokes = smokes;
    this.fragments = fragments;
    this.wakes = wakes;
    this._pos = new Vector();
    this.firePos = new Vector();
    this._vel = new Vector();
    this.refVel = new Vector();
    switch (idx) {
    case 0:
      this._shape = new BaseShape(0.7, 0.6, 0.6, BaseShape.ShapeType.SHIP_ROUNDTAIL, 0.5, 0.7, 0.5);
      this.bridgeShape = new BaseShape(0.3, 0.6, 0.6, BaseShape.ShapeType.BRIDGE, 0.3, 0.7, 0.3);
      break;
    case 1:
      this._shape = new BaseShape(0.7, 0.6, 0.6, BaseShape.ShapeType.SHIP_ROUNDTAIL, 0.4, 0.3, 0.8);
      this.bridgeShape = new BaseShape(0.3, 0.6, 0.6, BaseShape.ShapeType.BRIDGE, 0.2, 0.3, 0.6);
      break;
    }
    this.deg = 0;
    this.speed = 0;
    this.turnRatio = 0;
    this.turnSpeed = 1;
    this.fireInterval = Boat.FIRE_INTERVAL;
    this.fireSprDeg = 0;
    this.cnt = 0;
    this.shieldCnt = 0;
    this.shieldShape = new ShieldShape();
  }

  public close(): void {
    this._shape.close();
    this.bridgeShape.close();
    this.shieldShape.close();
  }

  public setShots(shots: ShotPool): void {
    this.shots = shots;
  }

  public setEnemies(enemies: EnemyPool): void {
    this.enemies = enemies;
  }

  public setStageManager(stageManager: StageManager): void {
    this.stageManager = stageManager;
  }

  public setGameState(gameState: InGameState): void {
    this.gameState = gameState;
  }

  public start(gameMode: number): void {
    this.gameMode = gameMode;
    if (gameMode == InGameState.GameMode.DOUBLE_PLAY) {
      switch (this.idx) {
      case 0:
        this._pos.x = -this.field.size.x * 0.5;
        break;
      case 1:
        this._pos.x = this.field.size.x * 0.5;
        break;
      }
    } else {
      this._pos.x = 0;
    }
    this._pos.y = -this.field.size.y * 0.8;
    this.firePos.x = this.firePos.y = 0;
    this._vel.x = this._vel.y = 0;
    this.deg = 0;
    this.speed = Boat.SPEED_BASE;
    this.turnRatio = Boat.TURN_RATIO_BASE;
    this.cnt = -Boat.INVINCIBLE_CNT;
    this.aPressed = this.bPressed = true;
    Boat.padInput = this.pad.getNullState();
    Boat.stickInput = this.twinStick.getNullState();
    Boat.mouseInput = this.mouse.getNullState();
  }

  public restart(): void {
    switch (this.gameMode) {
    case InGameState.GameMode.NORMAL:
      this.fireCnt = 99999;
      this.fireInterval = 99999;
      break;
    case InGameState.GameMode.TWIN_STICK:
    case InGameState.GameMode.DOUBLE_PLAY:
    case InGameState.GameMode.MOUSE:
      this.fireCnt = 0;
      this.fireInterval = Boat.FIRE_INTERVAL;
      break;
    }
    this.fireSprCnt = 0;
    this.fireSprDeg = 0.5;
    this.fireLanceCnt = 0;
    if (this.field.getBlock(this._pos) >= 0)
      this.onBlock = true;
    else
      this.onBlock = false;
    this.refVel.x = this.refVel.y = 0;
    this.shieldCnt = 20 * 60;
  }

  public move(): void {
    let px: number = this._pos.x, py = this._pos.y;
    this.cnt++;
    this.vx = this.vy = 0;
    switch (this.gameMode) {
    case InGameState.GameMode.NORMAL:
      this.moveNormal();
      break;
    case InGameState.GameMode.TWIN_STICK:
      this.moveTwinStick();
      break;
    case InGameState.GameMode.DOUBLE_PLAY:
      this.moveDoublePlay();
      break;
    case InGameState.GameMode.MOUSE:
      this.moveMouse();
      break;
    }
    if (this.gameState.isGameOver) {
      this.clearBullets();
      if (this.cnt < -Boat.INVINCIBLE_CNT)
        this.cnt = -Boat.RESTART_CNT;
    } else if (this.cnt < -Boat.INVINCIBLE_CNT) {
      this.clearBullets();
    }
    this.vx *= this.speed;
    this.vy *= this.speed;
    this.vx += this.refVel.x;
    this.vy += this.refVel.y;
    this.refVel *= 0.9;
    if (this.field.checkInField(this._pos.x, this._pos.y - this.field.lastScrollY))
      this._pos.y -= this.field.lastScrollY;
    if ((this.onBlock || this.field.getBlock(this._pos.x + this.vx, this._pos.y) < 0) &&
        this.field.checkInField(this._pos.x + this.vx, this._pos.y)) {
      this._pos.x += this.vx;
      this._vel.x = this.vx;
    } else {
      this._vel.x = 0;
      this.refVel.x = 0;
    }
    let srf: boolean = false;
    if ((this.onBlock || this.field.getBlock(px, this._pos.y + this.vy) < 0) &&
        this.field.checkInField(this._pos.x, this._pos.y + this.vy)) {
      this._pos.y += this.vy;
      this._vel.y = this.vy;
    } else {
      this._vel.y = 0;
      this.refVel.y = 0;
    }
    if (this.field.getBlock(this._pos.x, this._pos.y) >= 0) {
      if (!this.onBlock)
        if (this.cnt <= 0)
          this.onBlock = true;
        else {
          if (this.field.checkInField(this._pos.x, this._pos.y - this.field.lastScrollY)) {
            this._pos.x = px;
            this._pos.y = py;
          } else {
            this.destroyed();
          }
        }
    } else {
      this.onBlock = false;
    }
    switch (this.gameMode) {
    case InGameState.GameMode.NORMAL:
      this.fireNormal();
      break;
    case InGameState.GameMode.TWIN_STICK:
      this.fireTwinStick();
      break;
    case InGameState.GameMode.DOUBLE_PLAY:
      this.fireDobulePlay();
      break;
    case InGameState.GameMode.MOUSE:
      this.fireMouse();
      break;
    }
    if (this.cnt % 3 == 0 && this.cnt >= -Boat.INVINCIBLE_CNT) {
      let sp: number;
      if (this.vx != 0 || this.vy != 0)
        sp = 0.4;
      else
        sp = 0.2;
      sp *= 1 + Boat.rand.nextSignedFloat(0.33);
      sp *= Boat.SPEED_BASE;
      this._shape.addWake(this.wakes, this._pos, this.deg, sp);
    }
    let he: Enemy = this.enemies.checkHitShip(pos.x, pos.y);
    if (he) {
      let rd: number;
      if (pos.dist(he.pos) < 0.1)
        rd = 0;
      else
        rd = atan2(this._pos.x - he.pos.x, this._pos.y - he.pos.y);
      assert(!Number.isNaN(rd) && !Number.isNaN(0));
      let sz: number = he.size;
      this.refVel.x = sin(rd) * sz * 0.1;
      this.refVel.y = cos(rd) * sz * 0.1;
      let rs: number = this.refVel.vctSize;
      if (rs > 1) {
        this.refVel.x /= rs;
        this.refVel.y /= rs;
      }
    }
    if (this.shieldCnt > 0)
      this.shieldCnt--;
  }

  private moveNormal(): void {
    if (!this._replayMode) {
      Boat.padInput = this.pad.getState();
    } else {
      try {
        Boat.padInput = this.pad.replay();
      } catch (e) /* PORT_NOTE[D2TS:catch-type] D catch type was removed */ {
        this.gameState.isGameOver = true;
        Boat.padInput = this.pad.getNullState();
      }
    }
    if (this.gameState.isGameOver || this.cnt < -Boat.INVINCIBLE_CNT)
      Boat.padInput.clear();
    if (Boat.padInput.dir & PadState.Dir.UP)
      this.vy = 1;
    if (Boat.padInput.dir & PadState.Dir.DOWN)
      this.vy = -1;
    if (Boat.padInput.dir & PadState.Dir.RIGHT)
      this.vx = 1;
    if (Boat.padInput.dir & PadState.Dir.LEFT)
      this.vx = -1;
    if (this.vx != 0 && this.vy != 0) {
      this.vx *= 0.7;
      this.vy *= 0.7;
    }
    if (this.vx != 0 || this.vy != 0) {
      let ad: number = atan2(this.vx, this.vy);
      assert(!Number.isNaN(ad) && !Number.isNaN(0));
      Math.normalizeDeg(ad);
      ad -= this.deg;
      Math.normalizeDeg(ad);
      this.deg += ad * this.turnRatio * this.turnSpeed;
      Math.normalizeDeg(this.deg);
    }
  }

  private moveTwinStick(): void {
    if (!this._replayMode) {
      Boat.stickInput = this.twinStick.getState();
    } else {
      try {
        Boat.stickInput = this.twinStick.replay();
      } catch (e) /* PORT_NOTE[D2TS:catch-type] D catch type was removed */ {
        this.gameState.isGameOver = true;
        Boat.stickInput = this.twinStick.getNullState();
      }
    }
    if (this.gameState.isGameOver || this.cnt < -Boat.INVINCIBLE_CNT)
      Boat.stickInput.clear();
    this.vx = Boat.stickInput.left.x;
    this.vy = Boat.stickInput.left.y;
    if (this.vx != 0 || this.vy != 0) {
      let ad: number = atan2(this.vx, this.vy);
      assert(!Number.isNaN(ad) && !Number.isNaN(0));
      Math.normalizeDeg(ad);
      ad -= this.deg;
      Math.normalizeDeg(ad);
      this.deg += ad * this.turnRatio * this.turnSpeed;
      Math.normalizeDeg(this.deg);
    }
  }

  private moveDoublePlay(): void {
    switch (this.idx) {
    case 0:
      if (!this._replayMode) {
        Boat.stickInput = this.twinStick.getState();
      } else {
        try {
          Boat.stickInput = this.twinStick.replay();
        } catch (e) /* PORT_NOTE[D2TS:catch-type] D catch type was removed */ {
          this.gameState.isGameOver = true;
          Boat.stickInput = this.twinStick.getNullState();
        }
      }
      if (this.gameState.isGameOver || this.cnt < -Boat.INVINCIBLE_CNT)
        Boat.stickInput.clear();
      this.vx = Boat.stickInput.left.x;
      this.vy = Boat.stickInput.left.y;
      break;
    case 1:
      this.vx = Boat.stickInput.right.x;
      this.vy = Boat.stickInput.right.y;
      break;
    }
    if (this.vx != 0 || this.vy != 0) {
      let ad: number = atan2(this.vx, this.vy);
      assert(!Number.isNaN(ad) && !Number.isNaN(0));
      Math.normalizeDeg(ad);
      ad -= this.deg;
      Math.normalizeDeg(ad);
      this.deg += ad * this.turnRatio * this.turnSpeed;
      Math.normalizeDeg(this.deg);
    }
  }

  private moveMouse(): void {
    if (!this._replayMode) {
      let mps: MouseAndPadState = this.mouseAndPad.getState();
      Boat.padInput = mps.padState;
      Boat.mouseInput = mps.mouseState;
    } else {
      try {
        let mps: MouseAndPadState = this.mouseAndPad.replay();
        Boat.padInput = mps.padState;
        Boat.mouseInput = mps.mouseState;
      } catch (e) /* PORT_NOTE[D2TS:catch-type] D catch type was removed */ {
        this.gameState.isGameOver = true;
        Boat.padInput = this.pad.getNullState();
        Boat.mouseInput = this.mouse.getNullState();
      }
    }
    if (this.gameState.isGameOver || this.cnt < -Boat.INVINCIBLE_CNT) {
      Boat.padInput.clear();
      Boat.mouseInput.clear();
    }
    if (Boat.padInput.dir & PadState.Dir.UP)
      this.vy = 1;
    if (Boat.padInput.dir & PadState.Dir.DOWN)
      this.vy = -1;
    if (Boat.padInput.dir & PadState.Dir.RIGHT)
      this.vx = 1;
    if (Boat.padInput.dir & PadState.Dir.LEFT)
      this.vx = -1;
    if (this.vx != 0 && this.vy != 0) {
      this.vx *= 0.7;
      this.vy *= 0.7;
    }
    if (this.vx != 0 || this.vy != 0) {
      let ad: number = atan2(this.vx, this.vy);
      assert(!Number.isNaN(ad) && !Number.isNaN(0));
      Math.normalizeDeg(ad);
      ad -= this.deg;
      Math.normalizeDeg(ad);
      this.deg += ad * this.turnRatio * this.turnSpeed;
      Math.normalizeDeg(this.deg);
    }
  }

  private fireNormal(): void {
    if (Boat.padInput.button & PadState.Button.A) {
      this.turnRatio += (Boat.SLOW_TURN_RATIO - this.turnRatio) * Boat.TURN_CHANGE_RATIO;
      this.fireInterval = Boat.FIRE_INTERVAL;
      if (!this.aPressed) {
        this.fireCnt = 0;
        this.aPressed = true;
      }
    } else {
      this.turnRatio += (Boat.TURN_RATIO_BASE - this.turnRatio) * Boat.TURN_CHANGE_RATIO;
      this.aPressed = false;
      this.fireInterval *= 1.033;
      if (this.fireInterval > Boat.FIRE_INTERVAL_MAX)
        this.fireInterval = 99999;
    }
    this.fireDeg = this.deg;
    if (this.reverseFire)
      this.fireDeg += PI;
    if (this.fireCnt <= 0) {
      SoundManager.playSe("shot.wav");
      let s: Shot = this.shots.getInstance();
      let foc: number = (this.fireSprCnt % 2) * 2 - 1;
      this.firePos.x = this._pos.x + cos(this.fireDeg + PI) * 0.2 * foc;
      this.firePos.y = this._pos.y - sin(this.fireDeg + PI) * 0.2 * foc;
      if (s)
        s.set(this.firePos, this.fireDeg);
      this.fireCnt = /* D_CAST(int) */ this.fireInterval;
      let td: number;
      switch (foc) {
      case -1:
        td = this.fireSprDeg * (this.fireSprCnt / 2 % 4 + 1) * 0.2;
        break;
      case 1:
        td = -this.fireSprDeg * (this.fireSprCnt / 2 % 4 + 1) * 0.2;
        break;
      }
      this.fireSprCnt++;
      s = this.shots.getInstance();
      if (s)
        s.set(this.firePos, this.fireDeg + td);
      let sm: Smoke = this.smokes.getInstanceForced();
      let sd: number = this.fireDeg + td / 2;
      sm.set(this.firePos, sin(sd) * Shot.SPEED * 0.33, cos(sd) * Shot.SPEED * 0.33, 0,
             Smoke.SmokeType.SPARK, 10, 0.33);
    }
    this.fireCnt--;
    if (Boat.padInput.button & PadState.Button.B) {
      if (!this.bPressed && this.fireLanceCnt <= 0 && !this.shots.existsLance()) {
        SoundManager.playSe("lance.wav");
        let fd: number = this.deg;
        if (this.reverseFire)
          fd += PI;
        let s: Shot = this.shots.getInstance();
        if (s)
          s.set(pos, fd, true);
        for (let i = 0; i < 4; i++) {
          let sm: Smoke = this.smokes.getInstanceForced();
          let sd: number = fd + Boat.rand.nextSignedFloat(1);
          sm.set(pos,
                 sin(sd) * Shot.LANCE_SPEED * i * 0.2,
                 cos(sd) * Shot.LANCE_SPEED * i * 0.2,
                 0, Smoke.SmokeType.SPARK, 15, 0.5);
        }
        this.fireLanceCnt = Boat.FIRE_LANCE_INTERVAL;
      }
      this.bPressed = true;
    } else {
      this.bPressed = false;
    }
    this.fireLanceCnt--;
  }

  private fireTwinStick(): void {
    if (fabs(Boat.stickInput.right.x) + fabs(Boat.stickInput.right.y) > 0.01) {
      this.fireDeg = atan2(Boat.stickInput.right.x, Boat.stickInput.right.y);
      assert(!Number.isNaN(this.fireDeg) && !Number.isNaN(0));
      if (this.fireCnt <= 0) {
        SoundManager.playSe("shot.wav");
        let foc: number = (this.fireSprCnt % 2) * 2 - 1;
        let rsd: number = Boat.stickInput.right.vctSize;
        if (rsd > 1)
          rsd = 1;
        this.fireSprDeg = 1 - rsd + 0.05;
        this.firePos.x = this._pos.x + cos(this.fireDeg + PI) * 0.2 * foc;
        this.firePos.y = this._pos.y - sin(this.fireDeg + PI) * 0.2 * foc;
        this.fireCnt = /* D_CAST(int) */ this.fireInterval;
        let td: number;
        switch (foc) {
        case -1:
          td = this.fireSprDeg * (this.fireSprCnt / 2 % 4 + 1) * 0.2;
          break;
        case 1:
          td = -this.fireSprDeg * (this.fireSprCnt / 2 % 4 + 1) * 0.2;
          break;
        }
        this.fireSprCnt++;
        let s: Shot = this.shots.getInstance();
        if (s)
          s.set(this.firePos, this.fireDeg + td / 2, false, 2);
        s = this.shots.getInstance();
        if (s)
          s.set(this.firePos, this.fireDeg + td, false, 2);
        let sm: Smoke = this.smokes.getInstanceForced();
        let sd: number = this.fireDeg + td / 2;
        sm.set(this.firePos, sin(sd) * Shot.SPEED * 0.33, cos(sd) * Shot.SPEED * 0.33, 0,
               Smoke.SmokeType.SPARK, 10, 0.33);
      }
    } else {
      this.fireDeg = 99999;
    }
    this.fireCnt--;
  }

  private fireDobulePlay(): void {
    if (this.gameState.isGameOver || this.cnt < -Boat.INVINCIBLE_CNT)
      return;
    let dist: number = this.ship.distAmongBoats();
    this.fireInterval = Boat.FIRE_INTERVAL + 10.0 / (dist + 0.005);
    if (dist < 2)
      this.fireInterval = 99999;
    else if (dist < 4)
      this.fireInterval *= 3;
    else if (dist < 6)
      this.fireInterval *= 1.6;
    if (this.fireCnt > this.fireInterval)
      this.fireCnt = /* D_CAST(int) */ this.fireInterval;
    if (this.fireCnt <= 0) {
      SoundManager.playSe("shot.wav");
      let foc: number = (this.fireSprCnt % 2) * 2 - 1;
      this.fireDeg = 0;//this.ship.degAmongBoats() + PI / 2;
      this.firePos.x = this._pos.x + cos(this.fireDeg + PI) * 0.2 * foc;
      this.firePos.y = this._pos.y - sin(this.fireDeg + PI) * 0.2 * foc;
      let s: Shot = this.shots.getInstance();
      if (s)
        s.set(this.firePos, this.fireDeg, false , 2);
      this.fireCnt = /* D_CAST(int) */ this.fireInterval;
      let sm: Smoke = this.smokes.getInstanceForced();
      let sd: number = this.fireDeg;
      sm.set(this.firePos, sin(sd) * Shot.SPEED * 0.33, cos(sd) * Shot.SPEED * 0.33, 0,
             Smoke.SmokeType.SPARK, 10, 0.33);
      if (this.idx == 0) {
        let fd: number = this.ship.degAmongBoats() + PI / 2;
        let td: number;
        switch (foc) {
        case -1:
          td = this.fireSprDeg * (this.fireSprCnt / 2 % 4 + 1) * 0.15;
          break;
        case 1:
          td = -this.fireSprDeg * (this.fireSprCnt / 2 % 4 + 1) * 0.15;
          break;
        }
        this.firePos.x = this.ship.midstPos.x + cos(fd + PI) * 0.2 * foc;
        this.firePos.y = this.ship.midstPos.y - sin(fd + PI) * 0.2 * foc;
        s = this.shots.getInstance();
        if (s)
          s.set(this.firePos, fd, false, 2);
        s = this.shots.getInstance();
        if (s)
          s.set(this.firePos, fd + td, false , 2);
        sm = this.smokes.getInstanceForced();
        sm.set(this.firePos, sin(fd + td / 2) * Shot.SPEED * 0.33, cos(fd + td / 2) * Shot.SPEED * 0.33, 0,
               Smoke.SmokeType.SPARK, 10, 0.33);
      }
      this.fireSprCnt++;
    }
    this.fireCnt--;
  }

  private fireMouse(): void {
    let fox: number = Boat.mouseInput.x - this._pos.x;
    let foy: number = Boat.mouseInput.y - this._pos.y;
    if (fabs(fox) < 0.01)
      fox = 0.01;
    if (fabs(foy) < 0.01)
      foy = 0.01;
    this.fireDeg = atan2(fox, foy);
    assert(!Number.isNaN(this.fireDeg) && !Number.isNaN(0));
    if (Boat.mouseInput.button & (MouseState.Button.LEFT | MouseState.Button.RIGHT)) {
      if (this.fireCnt <= 0) {
        SoundManager.playSe("shot.wav");
        let foc: number = (this.fireSprCnt % 2) * 2 - 1;
        let rsd: number = Boat.stickInput.right.vctSize;
        let fstd: number = 0.05;
        if (Boat.mouseInput.button & MouseState.Button.RIGHT)
          fstd += 0.5;
        this.fireSprDeg += (fstd - this.fireSprDeg) * 0.16;
        this.firePos.x = this._pos.x + cos(this.fireDeg + PI) * 0.2 * foc;
        this.firePos.y = this._pos.y - sin(this.fireDeg + PI) * 0.2 * foc;
        this.fireCnt = /* D_CAST(int) */ this.fireInterval;
        let td: number;
        switch (foc) {
        case -1:
          td = this.fireSprDeg * (this.fireSprCnt / 2 % 4 + 1) * 0.2;
          break;
        case 1:
          td = -this.fireSprDeg * (this.fireSprCnt / 2 % 4 + 1) * 0.2;
          break;
        }
        this.fireSprCnt++;
        let s: Shot = this.shots.getInstance();
        if (s)
          s.set(this.firePos, this.fireDeg + td / 2, false, 2);
        s = this.shots.getInstance();
        if (s)
          s.set(this.firePos, this.fireDeg + td, false, 2);
        let sm: Smoke = this.smokes.getInstanceForced();
        let sd: number = this.fireDeg + td / 2;
        sm.set(this.firePos, sin(sd) * Shot.SPEED * 0.33, cos(sd) * Shot.SPEED * 0.33, 0,
               Smoke.SmokeType.SPARK, 10, 0.33);
      }
    }
    this.fireCnt--;
  }

  public checkBulletHit(p: Vector, pp: Vector): boolean {
    if (this.cnt <= 0)
      return false;
    let bmvx: number;
    let bmvy: number;
    let inaa: number;
    // PORT_NOTE[D2TS:multi-decl]:
    // reason: Split D multi-variable declaration into one-per-line.
    // original: float bmvx, bmvy, inaa;
    bmvx = pp.x;
    bmvy = pp.y;
    bmvx -= p.x;
    bmvy -= p.y;
    inaa = bmvx * bmvx + bmvy * bmvy;
    if (inaa > 0.00001) {
      let sofsx: number;
      let sofsy: number;
      let inab: number;
      let hd: number;
      // PORT_NOTE[D2TS:multi-decl]:
      // reason: Split D multi-variable declaration into one-per-line.
      // original: float sofsx, sofsy, inab, hd;
      sofsx = this._pos.x;
      sofsy = this._pos.y;
      sofsx -= p.x;
      sofsy -= p.y;
      inab = bmvx * sofsx + bmvy * sofsy;
      if (inab >= 0 && inab <= inaa) {
        hd = sofsx * sofsx + sofsy * sofsy - inab * inab / inaa;
        if (hd >= 0 && hd <= Boat.HIT_WIDTH) {
          this.destroyed();
          return true;
        }
      }
    }
    return false;
  }

  private destroyed(): void {
    if (this.cnt <= 0)
      return;
    if (this.shieldCnt > 0) {
      this.destroyedBoatShield();
      return;
    }
    this.ship.destroyed();
    this.gameState.shipDestroyed();
  }

  private destroyedBoatShield(): void {
    for (let i = 0; i < 100; i++) {
      let sp: Spark = this.sparks.getInstanceForced();
      sp.set(pos, Boat.rand.nextSignedFloat(1), Boat.rand.nextSignedFloat(1),
             0.5 + Boat.rand.nextFloat(0.5), 0.5 + Boat.rand.nextFloat(0.5), 0,
             40 + Boat.rand.nextInt(40));
    }
    SoundManager.playSe("ship_shield_lost.wav");
    this.screen.setScreenShake(30, 0.02);
    this.shieldCnt = 0;
    this.cnt = -Boat.INVINCIBLE_CNT / 2;
  }

  public destroyedBoat(): void {
    for (let i = 0; i < 128; i++) {
      let sp: Spark = this.sparks.getInstanceForced();
      sp.set(pos, Boat.rand.nextSignedFloat(1), Boat.rand.nextSignedFloat(1),
             0.5 + Boat.rand.nextFloat(0.5), 0.5 + Boat.rand.nextFloat(0.5), 0,
             40 + Boat.rand.nextInt(40));
    }
    SoundManager.playSe("ship_destroyed.wav");
    for (let i = 0; i < 64; i++) {
      let s: Smoke = this.smokes.getInstanceForced();
      s.set(pos, Boat.rand.nextSignedFloat(0.2), Boat.rand.nextSignedFloat(0.2),
            Boat.rand.nextFloat(0.1),
            Smoke.SmokeType.EXPLOSION, 50 + Boat.rand.nextInt(30), 1);
    }
    this.screen.setScreenShake(60, 0.05);
    this.restart();
    this.cnt = -Boat.RESTART_CNT;
  }

  public hasCollision(): boolean {
    if (this.cnt < -Boat.INVINCIBLE_CNT)
      return false;
    else
      return true;
  }

  public draw(): void {
    if (this.cnt < -Boat.INVINCIBLE_CNT)
      return;
    if (this.fireDeg < 99999) {
      Screen.setColor(0.5, 0.9, 0.7, 0.4);
      glBegin(GL_LINE_STRIP);
      glVertex2(this._pos.x, this._pos.y);
      Screen.setColor(0.5, 0.9, 0.7, 0.8);
      glVertex2(this._pos.x + sin(this.fireDeg) * 20, this._pos.y + cos(this.fireDeg) * 20);
      glEnd();
    }
    if (this.cnt < 0 && (-this.cnt % 32) < 16)
      return;
    glPushMatrix();
    Screen.glTranslate(pos);
    glRotatef(-this.deg * 180 / PI, 0, 0, 1);
    this._shape.draw();
    this.bridgeShape.draw();
    if (this.shieldCnt > 0) {
      let ss: number = 0.66;
      if (this.shieldCnt < 120)
        ss *= /* D_CAST(float) */ this.shieldCnt / 120;
      glScalef(ss, ss, ss);
      glRotatef(this.shieldCnt * 5, 0, 0, 1);
      this.shieldShape.draw();
    }
    glPopMatrix();
  }

  public drawFront(): void {
    if (this.cnt < -Boat.INVINCIBLE_CNT)
      return;
    if (this.gameMode == InGameState.GameMode.MOUSE) {
      Screen.setColor(0.7, 0.9, 0.8, 1.0);
      Screen.lineWidth(2);
      this.drawSight(Boat.mouseInput.x, Boat.mouseInput.y, 0.3);
      let ss: number = 0.9 - 0.8 * ((this.cnt + 1024) % 32) / 32;
      Screen.setColor(0.5, 0.9, 0.7, 0.8);
      this.drawSight(Boat.mouseInput.x, Boat.mouseInput.y, ss);
      Screen.lineWidth(1);
    }
  }

  private drawSight(x: number, y: number, size: number): void {
    glBegin(GL_LINE_STRIP);
    glVertex2(x - size, y - size * 0.5);
    glVertex2(x - size, y - size);
    glVertex2(x - size * 0.5, y - size);
    glEnd();
    glBegin(GL_LINE_STRIP);
    glVertex2(x + size, y - size * 0.5);
    glVertex2(x + size, y - size);
    glVertex2(x + size * 0.5, y - size);
    glEnd();
    glBegin(GL_LINE_STRIP);
    glVertex2(x + size, y + size * 0.5);
    glVertex2(x + size, y + size);
    glVertex2(x + size * 0.5, y + size);
    glEnd();
    glBegin(GL_LINE_STRIP);
    glVertex2(x - size, y + size * 0.5);
    glVertex2(x - size, y + size);
    glVertex2(x - size * 0.5, y + size);
    glEnd();
  }

  public drawShape(): void {
    this._shape.draw();
    this.bridgeShape.draw();
  }

  public clearBullets(): void {
    this.gameState.clearBullets();
  }

  public pos(): Vector {
    return this._pos;
  }

  public vel(): Vector {
    return this._vel;
  }

  public setReplayMode(turnSpeed: number, reverseFire: boolean): void {
    this._replayMode = true;
    this.turnSpeed = turnSpeed;
    this.reverseFire = reverseFire;
  }

  public unsetReplayMode(): void {
    this._replayMode = false;
    this.turnSpeed = GameManager.shipTurnSpeed;
    this.reverseFire = GameManager.shipReverseFire;
  }

  public replayMode(): boolean {
    return this._replayMode;
  }
}
