// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: shot.d,v 1.2 2005/07/03 07:05:22 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.shot;

// D_IMPORT: private import std.math;
// D_IMPORT: private import std.string;
// D_IMPORT: private import opengl;
// D_IMPORT: private import abagames.util.actor;
// D_IMPORT: private import abagames.util.vector;
// D_IMPORT: private import abagames.util.rand;
// D_IMPORT: private import abagames.util.sdl.shape;
// D_IMPORT: private import abagames.gr.field;
// D_IMPORT: private import abagames.gr.screen;
// D_IMPORT: private import abagames.gr.enemy;
// D_IMPORT: private import abagames.gr.particle;
// D_IMPORT: private import abagames.gr.bullet;
// D_IMPORT: private import abagames.gr.soundmanager;

/**
 * Player's shot.
 */
export class Shot extends Actor {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly SPEED: number = 0.6;
  static readonly LANCE_SPEED: number = 0.5;//0.4;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static shape: ShotShape;
  static lanceShape: LanceShape;
  static rand: Rand;
  field: Field;
  enemies: EnemyPool;
  sparks: SparkPool;
  smokes: SmokePool;
  bullets: BulletPool;
  pos: Vector;
  cnt: number;
  hitCnt: number;
  _deg: number;
  _damage: number;
  lance: boolean;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public static init(): void {
    Shot.shape = new ShotShape();
    Shot.lanceShape = new LanceShape();
    Shot.rand = new Rand();
  }

  public static setRandSeed(seed: number): void {
    Shot.rand.setSeed(seed);
  }

  public static close(): void {
    Shot.shape.close();
  }

  public constructor() {
    this.pos = new Vector();
    this.cnt = this.hitCnt = 0;
    this._deg = 0;
    this._damage = 1;
    this.lance = false;
  }

  public override init(args: unknown[]): void {
    this.field = /* D_CAST(Field) */ args[0];
    this.enemies = /* D_CAST(EnemyPool) */ args[1];
    this.sparks = /* D_CAST(SparkPool) */ args[2];
    this.smokes = /* D_CAST(SmokePool) */ args[3];
    this.bullets = /* D_CAST(BulletPool) */ args[4];
  }

  public set(p: Vector, d: number, lance: boolean = false, dmg: number = -1): void {
    this.pos.x = p.x;
    this.pos.y = p.y;
    this.cnt = this.hitCnt = 0;
    this._deg = d;
    this.lance = lance;
    if (lance)
      this._damage = 10;
    else
      this._damage = 1;
    if (dmg >= 0)
      this._damage = dmg;
    exists = true;
  }

  public override move(): void {
    this.cnt++;
    if (this.hitCnt > 0) {
      this.hitCnt++;
      if (this.hitCnt > 30)
        this.remove();
      return;
    }
    let sp: number;
    if (!this.lance) {
      sp = Shot.SPEED;
    } else {
      if (this.cnt < 10)
        sp = Shot.LANCE_SPEED * this.cnt / 10;
      else
        sp = Shot.LANCE_SPEED;
    }
    this.pos.x += sin(this._deg) * sp;
    this.pos.y += cos(this._deg) * sp;
    this.pos.y -= this.field.lastScrollY;
    if (this.field.getBlock(this.pos) >= Field.ON_BLOCK_THRESHOLD ||
        !this.field.checkInOuterField(this.pos) || this.pos.y > this.field.size.y)
      this.remove();
    if (this.lance) {
      this.enemies.checkShotHit(this.pos, Shot.lanceShape, this);
    } else {
      this.bullets.checkShotHit(this.pos, Shot.shape, this);
      this.enemies.checkShotHit(this.pos, Shot.shape, this);
    }
  }

  public remove(): void {
    if (this.lance && this.hitCnt <= 0) {
      this.hitCnt = 1;
      return;
    }
    exists = false;
  }

  public removeHitToBullet(): void {
    this.removeHit();
  }

  public removeHitToEnemy(isSmallEnemy: boolean = false): void {
    if (isSmallEnemy && this.lance)
      return;
    SoundManager.playSe("hit.wav");
    this.removeHit();
  }

  private removeHit(): void {
    this.remove();
    let sn: number;
    if (this.lance) {
      for (let i = 0; i < 10; i++) {
        let s: Smoke = this.smokes.getInstanceForced();
        let d: number = this._deg + Shot.rand.nextSignedFloat(0.1);
        let sp: number = Shot.rand.nextFloat(Shot.LANCE_SPEED);
        s.set(this.pos, sin(d) * sp, cos(d) * sp, 0,
              Smoke.SmokeType.LANCE_SPARK, 30 + Shot.rand.nextInt(30), 1);
        s = this.smokes.getInstanceForced();
        d = this._deg + Shot.rand.nextSignedFloat(0.1);
        sp = Shot.rand.nextFloat(Shot.LANCE_SPEED);
        s.set(this.pos, -sin(d) * sp, -cos(d) * sp, 0,
              Smoke.SmokeType.LANCE_SPARK, 30 + Shot.rand.nextInt(30), 1);
      }
    } else {
      let s: Spark = this.sparks.getInstanceForced();
      let d: number = this._deg + Shot.rand.nextSignedFloat(0.5);
      s.set(this.pos, sin(d) * Shot.SPEED, cos(d) * Shot.SPEED,
            0.6 + Shot.rand.nextSignedFloat(0.4), 0.6 + Shot.rand.nextSignedFloat(0.4), 0.1, 20);
      s = this.sparks.getInstanceForced();
      d = this._deg + Shot.rand.nextSignedFloat(0.5);
      s.set(this.pos, -sin(d) * Shot.SPEED, -cos(d) * Shot.SPEED,
            0.6 + Shot.rand.nextSignedFloat(0.4), 0.6 + Shot.rand.nextSignedFloat(0.4), 0.1, 20);
    }
  }

  public override draw(): void {
    if (this.lance) {
      let x: number = this.pos.x, y = this.pos.y;
      let size: number = 0.25, a = 0.6;
      let hc: number = this.hitCnt;
      for (let i = 0; i < this.cnt / 4 + 1; i++) {
        size *= 0.9;
        a *= 0.8;
        if (hc > 0) {
          hc--;
          continue;
        }
        let d: number = i * 13 + this.cnt * 3;
        for (let j = 0; j < 6; j++) {
          glPushMatrix();
          glTranslatef(x, y, 0);
          glRotatef(-this._deg * 180 / PI, 0, 0, 1);
          glRotatef(d, 0, 1, 0);
          Screen.setColor(0.4, 0.8, 0.8, a);
          glBegin(GL_LINE_LOOP);
          glVertex3(-size, Shot.LANCE_SPEED, size / 2);
          glVertex3(size, Shot.LANCE_SPEED, size / 2);
          glVertex3(size, -Shot.LANCE_SPEED, size / 2);
          glVertex3(-size, -Shot.LANCE_SPEED, size / 2);
          glEnd();
          Screen.setColor(0.2, 0.5, 0.5, a / 2);
          glBegin(GL_TRIANGLE_FAN);
          glVertex3(-size, Shot.LANCE_SPEED, size / 2);
          glVertex3(size, Shot.LANCE_SPEED, size / 2);
          glVertex3(size, -Shot.LANCE_SPEED, size / 2);
          glVertex3(-size, -Shot.LANCE_SPEED, size / 2);
          glEnd();
          glPopMatrix();
          d += 60;
        }
        x -= sin(deg) * Shot.LANCE_SPEED * 2;
        y -= cos(deg) * Shot.LANCE_SPEED * 2;
      }
    } else {
      glPushMatrix();
      Screen.glTranslate(this.pos);
      glRotatef(-this._deg * 180 / PI, 0, 0, 1);
      glRotatef(this.cnt * 31, 0, 1, 0);
      Shot.shape.draw();
      glPopMatrix();
    }
  }

  public deg(): number {
    return this._deg;
  }

  public damage(): number {
    return this._damage;
  }

  public removed(): boolean {
    if (this.hitCnt > 0)
      return true;
    else
      return false;
  }
}

export class ShotPool extends ActorPool<Shot> {
  public constructor(n: number, args: unknown[]) {
    super(n, args);
  }

  public existsLance(): boolean {
    for (const s of actor)
      if (s.exists)
        if (s.lance && !s.removed)
          return true;
    return false;
  }
}

export class ShotShape extends CollidableDrawable {
  protected override createDisplayList(): void {
    Screen.setColor(0.1, 0.33, 0.1);
    glBegin(GL_QUADS);
    glVertex3(0, 0.3, 0.1);
    glVertex3(0.066, 0.3, -0.033);
    glVertex3(0.1, -0.3, -0.05);
    glVertex3(0, -0.3, 0.15);
    glVertex3(0.066, 0.3, -0.033);
    glVertex3(-0.066, 0.3, -0.033);
    glVertex3(-0.1, -0.3, -0.05);
    glVertex3(0.1, -0.3, -0.05);
    glVertex3(-0.066, 0.3, -0.033);
    glVertex3(0, 0.3, 0.1);
    glVertex3(0, -0.3, 0.15);
    glVertex3(-0.1, -0.3, -0.05);
    glEnd();
  }

  protected override setCollision(): void {
    _collision = new Vector(0.33, 0.33);
  }
}

export class LanceShape extends Collidable {
  // PORT_NOTE[D2TS:d-specific-feature]:
  // reason: D-specific feature requires manual rewrite.
  // original: mixin CollidableImpl;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  _collision: Vector;

  public constructor() {
    this._collision = new Vector(0.66, 0.66);
  }

  public collision(): Vector {
    return this._collision;
  }
}
