// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: soundmanager.d,v 1.5 2005/09/11 00:47:40 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.soundmanager;

// D_IMPORT: private import std.path;
// D_IMPORT: private import std.file;
// D_IMPORT: private import abagames.util.rand;
// D_IMPORT: private import abagames.util.logger;
// D_IMPORT: private import abagames.util.sdl.sound;

/**
 * Manage BGMs and SEs.
 */
export class SoundManager extends abagames.util.sdl.sound.SoundManager {
 private static:
  char[][] seFileName =
    ["shot.wav", "lance.wav", "hit.wav",
     "turret_destroyed.wav", "destroyed.wav", "small_destroyed.wav", "explode.wav",
     "ship_destroyed.wav", "ship_shield_lost.wav", "score_up.wav"];
  int[] seChannel =
    [0, 1, 2, 3, 4, 5, 6, 7, 7, 6];
  bgm: Music[string[]];
  se: Chunk[string[]];
  seMark: boolean[string[]];
  bgmDisabled: boolean = false;
  seDisabled: boolean = false;
  readonly RANDOM_BGM_START_INDEX: number = 1;
  rand: Rand;
  bgmFileName: string[][];
  currentBgm: string[];
  prevBgmIdx: number;
  nextIdxMv: number;

  public static setRandSeed(seed: number): void {
    this.rand.setSeed(seed);
  }

  public static loadSounds(): void {
    SoundManager.loadMusics();
    SoundManager.loadChunks();
    this.rand = new Rand();
  }

  private static loadMusics(): void {
    let musics: Music[string[]];
    let files: string[][] = listdir(Music.dir);
    for (const fileName of files) {
      let ext: string[] = getExt(fileName);
      if (ext != "ogg" && ext != "wav")
        continue;
      let music: Music = new Music();
      music.load(fileName);
      this.bgm[fileName] = music;
      bgmFileName.push(fileName); // PORT_NOTE[D2TS:append-op] D '~=' converted to push()
      Logger.info("Load bgm: " + fileName);
    }
  }

  private static loadChunks(): void {
    let i: number = 0;
    for (const fileName of seFileName) {
      let chunk: Chunk = new Chunk();
      chunk.load(fileName, seChannel[i]);
      this.se[fileName] = chunk;
      this.seMark[fileName] = false;
      Logger.info("Load SE: " + fileName);
      i++;
    }
  }

  public static playBgm(name: string[]): void {
    this.currentBgm = name;
    if (this.bgmDisabled)
      return;
    Music.haltMusic();
    this.bgm[name].play();
  }

  public static playBgm(): void {
    let bgmIdx: number = this.rand.nextInt(this.bgm.length - this.RANDOM_BGM_START_INDEX) + this.RANDOM_BGM_START_INDEX;
    this.nextIdxMv = this.rand.nextInt(2) * 2 - 1;
    this.prevBgmIdx = bgmIdx;
    SoundManager.playBgm(this.bgmFileName[bgmIdx]);
  }

  public static nextBgm(): void {
    let bgmIdx: number = this.prevBgmIdx + this.nextIdxMv;
    if (bgmIdx < this.RANDOM_BGM_START_INDEX)
      bgmIdx = this.bgm.length - 1;
    else if (bgmIdx >= this.bgm.length)
        bgmIdx = this.RANDOM_BGM_START_INDEX;
    this.prevBgmIdx = bgmIdx;
    SoundManager.playBgm(this.bgmFileName[bgmIdx]);
  }

  public static playCurrentBgm(): void {
    SoundManager.playBgm(this.currentBgm);
  }

  public static fadeBgm(): void {
    Music.fadeMusic();
  }

  public static haltBgm(): void {
    Music.haltMusic();
  }

  public static playSe(name: string[]): void {
    if (this.seDisabled)
      return;
    this.seMark[name] = true;
  }

  public static playMarkedSe(): void {
    let keys: string[][] = this.seMark.keys;
    for (const key of keys) {
      if (this.seMark[key]) {
        this.se[key].play();
        this.seMark[key] = false;
      }
    }
  }

  public static disableSe(): void {
    this.seDisabled = true;
  }

  public static enableSe(): void {
    this.seDisabled = false;
  }

  public static disableBgm(): void {
    this.bgmDisabled = true;
  }

  public static enableBgm(): void {
    this.bgmDisabled = false;
  }
}
