// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: stagemanager.d,v 1.2 2005/07/03 07:05:22 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.stagemanager;

// D_IMPORT: private import std.string;
// D_IMPORT: private import std.math;
// D_IMPORT: private import abagames.util.vector;
// D_IMPORT: private import abagames.util.rand;
// D_IMPORT: private import abagames.util.sdl.shape;
// D_IMPORT: private import abagames.gr.enemy;
// D_IMPORT: private import abagames.gr.bullet;
// D_IMPORT: private import abagames.gr.ship;
// D_IMPORT: private import abagames.gr.field;
// D_IMPORT: private import abagames.gr.letter;
// D_IMPORT: private import abagames.gr.particle;
// D_IMPORT: private import abagames.gr.soundmanager;

/**
 * Manage an enemys' appearance, a rank(difficulty) and a field.
 */
export class StageManager {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly RANK_INC_BASE: number = 0.0018;
  static readonly BLOCK_DENSITY_MIN: number = 0;
  static readonly BLOCK_DENSITY_MAX: number = 3;
  field: Field;
  enemies: EnemyPool;
  ship: Ship;
  bullets: BulletPool;
  sparks: SparkPool;
  smokes: SmokePool;
  fragments: FragmentPool;
  wakes: WakePool;
  rand: Rand;
  rank: number;
  baseRank: number;
  addRank: number;
  rankVel: number;
  rankInc: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float rank, baseRank, addRank, rankVel, rankInc;
  enemyApp: EnemyAppearance[];
  _blockDensity: number;
  batteryNum: number;
  platformEnemySpec: PlatformEnemySpec;
  _bossMode: boolean;
  bossAppCnt: number;
  bossAppTime: number;
  bossAppTimeBase: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: int bossAppTime, bossAppTimeBase;
  bgmStartCnt: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor(field: Field, enemies: EnemyPool, ship: Ship, bullets: BulletPool, sparks: SparkPool, smokes: SmokePool, fragments: FragmentPool, wakes: WakePool) {
    this.field = field;
    this.enemies = enemies;
    this.ship = ship;
    this.bullets = bullets;
    this.sparks = sparks;
    this.smokes = smokes;
    this.fragments = fragments;
    this.wakes = wakes;
    this.rand = new Rand();
    this.enemyApp = new EnemyAppearance[3];
    for (const ea of this.enemyApp)
      ea = new EnemyAppearance();
    PlatformEnemySpec this.platformEnemySpec =
      new PlatformEnemySpec(field, ship, sparks, smokes, fragments, wakes);
    this.rank = this.baseRank = 1;
    this.addRank = this.rankVel = this.rankInc = 0;
    this._blockDensity = 2;
  }

  public setRandSeed(seed: number): void {
    this.rand.setSeed(seed);
  }

  public start(rankIncRatio: number): void {
    this.rank = this.baseRank = 1;
    this.addRank = this.rankVel = 0;
    this.rankInc = StageManager.RANK_INC_BASE * rankIncRatio;
    this._blockDensity = this.rand.nextInt(StageManager.BLOCK_DENSITY_MAX - StageManager.BLOCK_DENSITY_MIN + 1) + StageManager.BLOCK_DENSITY_MIN;
    this._bossMode = false;
    this.bossAppTimeBase = 60 * 1000;
    this.resetBossMode();
    this.gotoNextBlockArea();
    this.bgmStartCnt = -1;
  }

  public startBossMode(): void {
    this._bossMode = true;
    this.bossAppCnt = 2;
    SoundManager.fadeBgm();
    this.bgmStartCnt = 120;
    this.rankVel = 0;
  }

  public resetBossMode(): void {
    if (this._bossMode) {
      this._bossMode = false;
      SoundManager.fadeBgm();
      this.bgmStartCnt = 120;
      this.bossAppTimeBase += 30 * 1000;
    }
    this.bossAppTime = this.bossAppTimeBase;
  }

  public move(): void {
    this.bgmStartCnt--;
    if (this.bgmStartCnt == 0) {
      if (this._bossMode)
        SoundManager.playBgm("gr0.ogg");
      else
        SoundManager.nextBgm();
    }
    if (this._bossMode) {
      this.addRank *= 0.999;
      if (!this.enemies.hasBoss && this.bossAppCnt <= 0)
        this.resetBossMode();
    } else {
      let rv: number = this.field.lastScrollY / this.ship.scrollSpeedBase - 2;
      this.bossAppTime -= 17;
      if (this.bossAppTime <= 0) {
        this.bossAppTime = 0;
        this.startBossMode();
      }
      if (rv > 0) {
        this.rankVel += rv * rv * 0.0004 * this.baseRank;
      } else {
        this.rankVel += rv * this.baseRank;
        if (this.rankVel < 0)
          this.rankVel = 0;
      }
      this.addRank += this.rankInc * (this.rankVel + 1);
      this.addRank *= 0.999;
      this.baseRank += this.rankInc + this.addRank * 0.0001;
    }
    this.rank = this.baseRank + this.addRank;
    for (const ea of this.enemyApp)
      ea.move(this.enemies, this.field);
  }

  public shipDestroyed(): void {
    this.rankVel = 0;
    if (!this._bossMode)
      this.addRank = 0;
    else
      this.addRank /= 2;
  }

  public gotoNextBlockArea(): void {
    if (this._bossMode) {
      this.bossAppCnt--;
      if (this.bossAppCnt == 0) {
        let ses: ShipEnemySpec = new ShipEnemySpec(this.field, this.ship, this.sparks, this.smokes, this.fragments, this.wakes);
        ses.setParam(this.rank, ShipEnemySpec.ShipClass.BOSS, this.rand);
        let en: Enemy = this.enemies.getInstance();
        if (en) {
          if ((/* D_CAST(HasAppearType) */ ses).setFirstState(en.state, EnemyState.AppearanceType.CENTER))
            en.set(ses);
        } else {
          this.resetBossMode();
        }
      }
      for (const ea of this.enemyApp)
        ea.unset();
      return;
    }
    let noSmallShip: boolean;
    if (this._blockDensity < StageManager.BLOCK_DENSITY_MAX && this.rand.nextInt(2) == 0)
      noSmallShip = true;
    else
      noSmallShip = false;
    this._blockDensity += this.rand.nextSignedInt(1);
    if (this._blockDensity < StageManager.BLOCK_DENSITY_MIN)
      this._blockDensity = StageManager.BLOCK_DENSITY_MIN;
    else if (this._blockDensity > StageManager.BLOCK_DENSITY_MAX)
      this._blockDensity = StageManager.BLOCK_DENSITY_MAX;
    this.batteryNum = /* D_CAST(int) */ ((this._blockDensity + this.rand.nextSignedFloat(1)) * 0.75);
    let tr: number = this.rank;
    let largeShipNum: number = /* D_CAST(int) */ ((2 - this._blockDensity + this.rand.nextSignedFloat(1)) * 0.5);
    if (noSmallShip)
      largeShipNum *= 1.5;
    else
      largeShipNum *= 0.5;
    let appType: number = this.rand.nextInt(2);
    if (largeShipNum > 0) {
      let lr: number = tr * (0.25 + this.rand.nextFloat(0.15));
      if (noSmallShip)
        lr *= 1.5;
      tr -= lr;
      let ses: ShipEnemySpec = new ShipEnemySpec(this.field, this.ship, this.sparks, this.smokes, this.fragments, this.wakes);
      ses.setParam(lr / largeShipNum, ShipEnemySpec.ShipClass.LARGE, this.rand);
      this.enemyApp[0].set(ses, largeShipNum, appType, this.rand);
    } else {
      this.enemyApp[0].unset();
    }
    if (this.batteryNum > 0) {
      this.platformEnemySpec = new PlatformEnemySpec(this.field, this.ship, this.sparks, this.smokes, this.fragments, this.wakes);
      let pr: number = tr * (0.3 + this.rand.nextFloat(0.1));
      this.platformEnemySpec.setParam(pr / this.batteryNum, this.rand);
    }
    appType = (appType + 1) % 2;
    let middleShipNum: number = /* D_CAST(int) */ ((4 - this._blockDensity + this.rand.nextSignedFloat(1)) * 0.66);
    if (noSmallShip)
      middleShipNum *= 2;
    if (middleShipNum > 0) {
      let mr: number;
      if (noSmallShip)
        mr = tr;
      else
        mr = tr * (0.33 + this.rand.nextFloat(0.33));
      tr -= mr;
      let ses: ShipEnemySpec = new ShipEnemySpec(this.field, this.ship, this.sparks, this.smokes, this.fragments, this.wakes);
      ses.setParam(mr / middleShipNum, ShipEnemySpec.ShipClass.MIDDLE, this.rand);
      this.enemyApp[1].set(ses, middleShipNum, appType, this.rand);
    } else {
      this.enemyApp[1].unset();
    }
    if (!noSmallShip) {
      appType = EnemyState.AppearanceType.TOP;
      int smallShipNum =
        /* D_CAST(int) */ (sqrt(3 + tr) * (1 + rand.nextSignedFloat(0.5)) * 2) + 1;
      if (smallShipNum > 256)
        smallShipNum = 256;
      let sses: SmallShipEnemySpec = new SmallShipEnemySpec(this.field, this.ship, this.sparks, this.smokes, this.fragments, this.wakes);
      sses.setParam(tr / smallShipNum, this.rand);
      this.enemyApp[2].set(sses, smallShipNum, appType, this.rand);
    } else {
      this.enemyApp[2].unset();
    }
  }

  public addBatteries(platformPos: PlatformPos[], platformPosNum: number): void {
    let ppn: number = platformPosNum;
    let bn: number = this.batteryNum;
    for (let i = 0; i < 100; i++) {
      if (ppn <= 0 || bn <= 0)
        break;
      let ppi: number = this.rand.nextInt(platformPosNum);
      for (let j = 0; j < platformPosNum; j++) {
        if (!platformPos[ppi].used)
          break;
        ppi++;
        if (ppi >= platformPosNum)
          ppi = 0;
      }
      if (platformPos[ppi].used)
        break;
      let en: Enemy = this.enemies.getInstance();
      if (!en)
        break;
      platformPos[ppi].used = true;
      ppn--;
      Vector p = this.field.convertToScreenPos
        (/* D_CAST(int) */ platformPos[ppi].pos.x, /* D_CAST(int) */ platformPos[ppi].pos.y);
      if (!this.platformEnemySpec.setFirstState(en.state, p.x, p.y, platformPos[ppi].deg))
        continue;
      for (let i = 0; i < platformPosNum; i++) {
        if (fabs(platformPos[ppi].pos.x - platformPos[i].pos.x) <= 1 &&
            fabs(platformPos[ppi].pos.y - platformPos[i].pos.y) <= 1 &&
            !platformPos[i].used) {
          platformPos[i].used = true;
          ppn--;
        }
      }
      en.set(this.platformEnemySpec);
      bn--;
    }
  }

  public blockDensity(): number {
    return this._blockDensity;
  }

  public draw(): void {
    Letter.drawNum(/* D_CAST(int) */ (this.rank * 1000), 620, 10, 10, 0, 0, 33, 3);
    Letter.drawTime(this.bossAppTime, 120, 20, 7);
  }

  public rankMultiplier(): number {
    return this.rank;
  }

  public bossMode(): boolean {
    return this._bossMode;
  }
}

export class EnemyAppearance {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  spec: EnemySpec;
  nextAppDist: number;
  nextAppDistInterval: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float nextAppDist, nextAppDistInterval;
  appType: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor() {
    this.nextAppDist = 0;
    this.nextAppDistInterval = 1;
  }

  public set(s: EnemySpec, num: number, appType: number, rand: Rand): void {
    this.spec = s;
    this.nextAppDistInterval = (/* D_CAST(float) */ Field.NEXT_BLOCK_AREA_SIZE) / num;
    this.nextAppDist = rand.nextFloat(this.nextAppDistInterval);
    this.appType = appType;
  }

  public unset(): void {
    this.spec = null;
  }

  public move(enemies: EnemyPool, field: Field): void {
    if (!this.spec)
      return;
    this.nextAppDist -= field.lastScrollY;
    if (this.nextAppDist <= 0) {
      this.nextAppDist += this.nextAppDistInterval;
      this.appear(enemies);
    }
  }

  private appear(enemies: EnemyPool): void {
    let en: Enemy = enemies.getInstance();
    if (en) {
      if ((/* D_CAST(HasAppearType) */ this.spec).setFirstState(en.state, this.appType))
        en.set(this.spec);
    }
  }
}
