// @ts-nocheck
// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: title.d,v 1.4 2005/09/11 00:47:40 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.title;

// D_IMPORT: private import std.math;
// D_IMPORT: private import opengl;
// D_IMPORT: private import openglu;
// D_IMPORT: private import abagames.util.vector;
// D_IMPORT: private import abagames.util.sdl.displaylist;
// D_IMPORT: private import abagames.util.sdl.texture;
// D_IMPORT: private import abagames.util.sdl.pad;
// D_IMPORT: private import abagames.util.sdl.mouse;
// D_IMPORT: private import abagames.gr.screen;
// D_IMPORT: private import abagames.gr.prefmanager;
// D_IMPORT: private import abagames.gr.field;
// D_IMPORT: private import abagames.gr.letter;
// D_IMPORT: private import abagames.gr.gamemanager;
// D_IMPORT: private import abagames.gr.replay;
// D_IMPORT: private import abagames.gr.soundmanager;

/**
 * Title screen.
 */
export class TitleManager {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly SCROLL_SPEED_BASE: number = 0.025;
  prefManager: PrefManager;
  pad: RecordablePad;
  mouse: RecordableMouse;
  field: Field;
  gameManager: GameManager;
  displayList: DisplayList;
  logo: Texture;
  cnt: number;
  _replayData: ReplayData;
  btnPressedCnt: number;
  gameMode: number;

  public constructor(prefManager: PrefManager, pad: Pad, mouse: Mouse, field: Field, gameManager: GameManager) {
    this.prefManager = prefManager;
    this.pad = /* D_CAST(RecordablePad) */ pad;
    this.mouse = /* D_CAST(RecordableMouse) */ mouse;
    this.field = field;
    this.gameManager = gameManager;
    this.init();
  }

  private init(): void {
    logo = new Texture("title.bmp");
    this.displayList = new DisplayList(1);
    this.displayList.beginNewList();
    glEnable(GL_TEXTURE_2D);
    this.logo.bind();
    Screen.setColor(1, 1, 1);
    glBegin(GL_TRIANGLE_FAN); 
    glTexCoord2(0, 0);
    glVertex2(0, -63);
    glTexCoord2(1, 0);
    glVertex2(255, -63);
    glTexCoord2(1, 1);
    glVertex2(255, 0);
    glTexCoord2(0, 1);
    glVertex2(0, 0);
    glEnd();
    Screen.lineWidth(3);
    glDisable(GL_TEXTURE_2D);
    glBegin(GL_LINE_STRIP);
    glVertex2(-80, -7);
    glVertex2(-20, -7);
    glVertex2(10, -70);
    glEnd();
    glBegin(GL_LINE_STRIP);
    glVertex2(45, -2);
    glVertex2(-15, -2);
    glVertex2(-45, 61);
    glEnd();
    glBegin(GL_TRIANGLE_FAN);
    Screen.setColor(1, 1, 1);
    glVertex2(-19, -6);
    Screen.setColor(0, 0, 0);
    glVertex2(-79, -6);
    glVertex2(11, -69);
    glEnd();
    glBegin(GL_TRIANGLE_FAN);
    Screen.setColor(1, 1, 1);
    glVertex2(-16, -3);
    Screen.setColor(0, 0, 0);
    glVertex2(44, -3);
    glVertex2(-46, 60);
    glEnd();
    Screen.lineWidth(1);
    this.displayList.endNewList();
    this.gameMode = this.prefManager.prefData.gameMode;
  }

  public close(): void {
    this.displayList.close();
    this.logo.close();
  }

  public start(): void {
    this.cnt = 0;
    this.field.start();
    this.btnPressedCnt = 1;
  }

  public move(): void {
    if (!this._replayData) {
      this.field.move();
      this.field.scroll(TitleManager.SCROLL_SPEED_BASE, true);
    }
    let input: PadState = this.pad.getState(false);
    let mouseInput: MouseState = this.mouse.getState(false);
    if (this.btnPressedCnt <= 0) {
      if (((input.button & PadState.Button.A) ||
           (this.gameMode == InGameState.GameMode.MOUSE &&
            (mouseInput.button & MouseState.Button.LEFT))) &&
          this.gameMode >= 0)
        this.gameManager.startInGame(this.gameMode);
      let gmc: number = 0;
      if ((input.button & PadState.Button.B) || (input.dir & PadState.Dir.DOWN))
        gmc = 1;
      else if (input.dir & PadState.Dir.UP)
        gmc = -1;
      if (gmc != 0) {
        this.gameMode += gmc;
        if (this.gameMode >= InGameState.GAME_MODE_NUM)
          this.gameMode = -1;
        else if (this.gameMode < -1)
          this.gameMode = InGameState.GAME_MODE_NUM - 1;
        if (this.gameMode == -1 && this._replayData) {
          SoundManager.enableBgm();
          SoundManager.enableSe();
          SoundManager.playCurrentBgm();
        } else {
          SoundManager.fadeBgm();
          SoundManager.disableBgm();
          SoundManager.disableSe();
        }
      }
    }
    if ((input.button & (PadState.Button.A | PadState.Button.B)) ||
        (input.dir & (PadState.Dir.UP | PadState.Dir.DOWN)) ||
        (mouseInput.button & MouseState.Button.LEFT))
      this.btnPressedCnt = 6;
    else
      this.btnPressedCnt--;
    this.cnt++;
  }

  public draw(): void {
    if (this.gameMode < 0) {
      Letter.drawString("REPLAY", 3, 400, 5);
      return;
    }
    let ts: number = 1;
    if (this.cnt > 120) {
      ts -= (this.cnt - 120) * 0.015;
      if (ts < 0.5)
        ts = 0.5;
    }
    glPushMatrix();
    glTranslatef(80 * ts, 240, 0);
    glScalef(ts, ts, 0);
    this.displayList.call();
    glPopMatrix();
    if (this.cnt > 150) {
      Letter.drawString("HIGH", 3, 305, 4, Letter.Direction.TO_RIGHT, 1);
      Letter.drawNum(this.prefManager.prefData.highScore(this.gameMode), 80, 320, 4, 0, 9);
    }
    if (this.cnt > 200) {
      Letter.drawString("LAST", 3, 345, 4, Letter.Direction.TO_RIGHT, 1);
      let ls: number = 0;
      if (this._replayData)
        ls = this._replayData.score;
      Letter.drawNum(ls, 80, 360, 4, 0, 9);
    }
    Letter.drawString(InGameState.gameModeText[this.gameMode], 3, 400, 5);
  }

  public replayData(v: ReplayData): ReplayData {
    return this._replayData = v;
  }
}
