// @ts-nocheck
// Generated by d2ts.py (safe-mode)
// This output is a porting scaffold, not a complete transpilation.

/*
 * $Id: turret.d,v 1.3 2005/07/17 11:02:46 kenta Exp $
 *
 * Copyright 2005 Kenta Cho. Some rights reserved.
 */
// D_MODULE: module abagames.gr.turret;

// D_IMPORT: private import std.math;
// D_IMPORT: private import opengl;
// D_IMPORT: private import abagames.util.vector;
// D_IMPORT: private import abagames.util.actor;
// D_IMPORT: private import abagames.util.rand;
// D_IMPORT: private import abagames.util.math;
// D_IMPORT: private import abagames.util.sdl.shape;
// D_IMPORT: private import abagames.gr.field;
// D_IMPORT: private import abagames.gr.bullet;
// D_IMPORT: private import abagames.gr.ship;
// D_IMPORT: private import abagames.gr.screen;
// D_IMPORT: private import abagames.gr.particle;
// D_IMPORT: private import abagames.gr.shot;
// D_IMPORT: private import abagames.gr.shape;
// D_IMPORT: private import abagames.gr.enemy;
// D_IMPORT: private import abagames.gr.soundmanager;

/**
 * Turret mounted on a deck of an enemy ship.
 */
export class Turret {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static rand: Rand;
  static damagedPos: Vector;
  field: Field;
  bullets: BulletPool;
  ship: Ship;
  sparks: SparkPool;
  smokes: SmokePool;
  fragments: FragmentPool;
  spec: TurretSpec;
  pos: Vector;
  deg: number;
  baseDeg: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float deg, baseDeg;
  cnt: number;
  appCnt: number;
  startCnt: number;
  shield: number;
  damaged: boolean;
  destroyedCnt: number;
  damagedCnt: number;
  bulletSpeed: number;
  burstCnt: number;
  parent: Enemy;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public static init(): void {
    Turret.rand = new Rand();
    Turret.damagedPos = new Vector();
  }

  public static setRandSeed(seed: number): void {
    Turret.rand.setSeed(seed);
  }

  public constructor(field: Field, bullets: BulletPool, ship: Ship, sparks: SparkPool, smokes: SmokePool, fragments: FragmentPool, parent: Enemy) {
    this.field = field;
    this.bullets = bullets;
    this.ship = ship;
    this.sparks = sparks;
    this.smokes = smokes;
    this.fragments = fragments;
    this.parent = parent;
    this.pos = new Vector();
    this.deg = this.baseDeg = 0;
    this.bulletSpeed = 1;
  }

  public start(spec: TurretSpec): void {
    this.spec = spec;
    this.shield = spec.shield;
    this.appCnt = this.cnt = this.startCnt = 0;
    this.deg = this.baseDeg = 0;
    this.damaged = false;
    this.damagedCnt = 0;
    this.destroyedCnt = -1;
    this.bulletSpeed = 1;
    this.burstCnt = 0;
  }

  public move(x: number, y: number, d: number, bulletFireSpeed: number = 0, bulletFireDeg: number = -99999): boolean {
    this.pos.x = x;
    this.pos.y = y;
    this.baseDeg = d;
    if (this.destroyedCnt >= 0) {
      this.destroyedCnt++;
      let itv: number = 5 + this.destroyedCnt / 12;
      if (itv < 60 && this.destroyedCnt % itv == 0) {
        let s: Smoke = this.smokes.getInstance();
        if (s)
          s.set(this.pos, 0, 0, 0.01 + Turret.rand.nextFloat(0.01), Smoke.SmokeType.FIRE, 90 + Turret.rand.nextInt(30), this.spec.size);
      }
      return false;
    }
    let td: number = this.baseDeg + this.deg;
    let shipPos: Vector = this.ship.nearPos(this.pos);
    let shipVel: Vector = this.ship.nearVel(this.pos);
    let ax: number = shipPos.x - this.pos.x;
    let ay: number = shipPos.y - this.pos.y;
    if (this.spec.lookAheadRatio != 0) {
      let rd: number = this.pos.dist(shipPos) / this.spec.speed * 1.2;
      ax += shipVel.x * this.spec.lookAheadRatio * rd;
      ay += shipVel.y * this.spec.lookAheadRatio * rd;
    }
    let ad: number;
    if (fabs(ax) + fabs(ay) < 0.1)
      ad = 0;
    else
      ad = atan2(ax, ay);
    assert(!Number.isNaN(ad) && !Number.isNaN(0));
    let od: number = td - ad;
    Math.normalizeDeg(od);
    let ts: number;
    if (this.cnt >= 0)
      ts = this.spec.turnSpeed;
    else
      ts = this.spec.turnSpeed * this.spec.burstTurnRatio;
    if (fabs(od) <= ts)
      this.deg = ad - this.baseDeg;
    else if (od > 0)
      this.deg -= ts;
    else
      this.deg += ts;
    Math.normalizeDeg(this.deg);
    if (this.deg > this.spec.turnRange)
      this.deg = this.spec.turnRange;
    else if (this.deg < -this.spec.turnRange)
      this.deg = -this.spec.turnRange;
    this.cnt++;
    if (this.field.checkInField(this.pos) || (this.parent.isBoss && this.cnt % 4 == 0))
      this.appCnt++;
    if (this.cnt >= this.spec.interval) {
      if (this.spec.blind || (fabs(od) <= this.spec.turnSpeed &&
                         this.pos.dist(shipPos) < this.spec.maxRange * 1.1 &&
                         this.pos.dist(shipPos) > this.spec.minRange)) {
        this.cnt = -(this.spec.burstNum - 1) * this.spec.burstInterval;
        this.bulletSpeed = this.spec.speed;
        this.burstCnt = 0;
      }
    }
    if (this.cnt <= 0 && -this.cnt % this.spec.burstInterval == 0 &&
        ((this.spec.invisible && this.field.checkInField(this.pos)) ||
         (this.spec.invisible && this.parent.isBoss && this.field.checkInOuterField(this.pos)) ||
         (!this.spec.invisible && this.field.checkInFieldExceptTop(this.pos))) &&
        this.pos.dist(shipPos) > this.spec.minRange) {
      let bd: number = this.baseDeg + this.deg;
      let s: Smoke = this.smokes.getInstance();
      if (s)
        s.set(this.pos, sin(bd) * this.bulletSpeed, cos(bd) * this.bulletSpeed, 0,
              Smoke.SmokeType.SPARK, 20, this.spec.size * 2);
      let nw: number = this.spec.nway;
      if (this.spec.nwayChange && this.burstCnt % 2 == 1)
        nw--;
      bd -= this.spec.nwayAngle * (nw - 1) / 2;
      for (let i = 0; i < nw; i++) {
        let b: Bullet = this.bullets.getInstance();
        if (!b)
          break;
        b.set(this.parent.index,
              this.pos, bd, this.bulletSpeed, this.spec.size * 3, this.spec.bulletShape, this.spec.maxRange,
              bulletFireSpeed, bulletFireDeg, this.spec.bulletDestructive);
        bd += this.spec.nwayAngle;
      }
      this.bulletSpeed += this.spec.speedAccel;
      this.burstCnt++;
    }
    this.damaged = false;
    if (this.damagedCnt > 0)
      this.damagedCnt--;
    this.startCnt++;
    return true;
  }

  public draw(): void {
    if (this.spec.invisible)
      return;
    glPushMatrix();
    if (this.destroyedCnt < 0 && this.damagedCnt > 0) {
      Turret.damagedPos.x = this.pos.x + Turret.rand.nextSignedFloat(this.damagedCnt * 0.015);
      Turret.damagedPos.y = this.pos.y + Turret.rand.nextSignedFloat(this.damagedCnt * 0.015);
      Screen.glTranslate(Turret.damagedPos);
    } else {
      Screen.glTranslate(this.pos);
    }
    glRotatef(-(this.baseDeg + this.deg) * 180 / PI, 0, 0, 1);
    if (this.destroyedCnt >= 0)
      this.spec.destroyedShape.draw();
    else if (!this.damaged)
      this.spec.shape.draw();
    else
      this.spec.damagedShape.draw();
    glPopMatrix();
    if (this.destroyedCnt >= 0)
      return;
    if (this.appCnt > 120)
      return;
    let a: number = 1 - /* D_CAST(float) */ this.appCnt / 120;
    if (this.startCnt < 12)
      a = /* D_CAST(float) */ this.startCnt / 12;
    let td: number = this.baseDeg + this.deg;
    if (this.spec.nway <= 1) {
      glBegin(GL_LINE_STRIP);
      Screen.setColor(0.9, 0.1, 0.1, a);
      glVertex2(this.pos.x + sin(td) * this.spec.minRange, this.pos.y + cos(td) * this.spec.minRange);
      Screen.setColor(0.9, 0.1, 0.1, a * 0.5);
      glVertex2(this.pos.x + sin(td) * this.spec.maxRange, this.pos.y + cos(td) * this.spec.maxRange);
      glEnd();
    } else {
      td -= this.spec.nwayAngle * (this.spec.nway - 1) / 2;
      glBegin(GL_LINE_STRIP);
      Screen.setColor(0.9, 0.1, 0.1, a * 0.75);
      glVertex2(this.pos.x + sin(td) * this.spec.minRange, this.pos.y + cos(td) * this.spec.minRange);
      Screen.setColor(0.9, 0.1, 0.1, a * 0.25);
      glVertex2(this.pos.x + sin(td) * this.spec.maxRange, this.pos.y + cos(td) * this.spec.maxRange);
      glEnd();
      glBegin(GL_QUADS);
      for (let i = 0; i < this.spec.nway - 1; i++) {
        Screen.setColor(0.9, 0.1, 0.1, a * 0.3);
        glVertex2(this.pos.x + sin(td) * this.spec.minRange, this.pos.y + cos(td) * this.spec.minRange);
        Screen.setColor(0.9, 0.1, 0.1, a * 0.05);
        glVertex2(this.pos.x + sin(td) * this.spec.maxRange, this.pos.y + cos(td) * this.spec.maxRange);
        td += this.spec.nwayAngle;
        glVertex2(this.pos.x + sin(td) * this.spec.maxRange, this.pos.y + cos(td) * this.spec.maxRange);
        Screen.setColor(0.9, 0.1, 0.1, a * 0.3);
        glVertex2(this.pos.x + sin(td) * this.spec.minRange, this.pos.y + cos(td) * this.spec.minRange);
      }
      glEnd();
      glBegin(GL_LINE_STRIP);
      Screen.setColor(0.9, 0.1, 0.1, a * 0.75);
      glVertex2(this.pos.x + sin(td) * this.spec.minRange, this.pos.y + cos(td) * this.spec.minRange);
      Screen.setColor(0.9, 0.1, 0.1, a * 0.25);
      glVertex2(this.pos.x + sin(td) * this.spec.maxRange, this.pos.y + cos(td) * this.spec.maxRange);
      glEnd();
    }
  }

  public checkCollision(x: number, y: number, c: Collidable, shot: Shot): boolean {
    if (this.destroyedCnt >= 0 || this.spec.invisible)
      return false;
    let ox: number = fabs(this.pos.x - x), oy = fabs(this.pos.y - y);
    if (this.spec.shape.checkCollision(ox, oy, c)) {
      this.addDamage(shot.damage);
      return true;
    }
    return false;
  }

  public addDamage(n: number): void {
    this.shield -= n;
    if (this.shield <= 0)
      this.destroyed();
    this.damaged = true;
    this.damagedCnt = 10;
  }

  public destroyed(): void {
    SoundManager.playSe("turret_destroyed.wav");
    this.destroyedCnt = 0;
    for (let i = 0; i < 6; i++) {
      let s: Smoke = this.smokes.getInstanceForced();
      s.set(this.pos, Turret.rand.nextSignedFloat(0.1), Turret.rand.nextSignedFloat(0.1), Turret.rand.nextFloat(0.04),
            Smoke.SmokeType.EXPLOSION, 30 + Turret.rand.nextInt(20), this.spec.size * 1.5);
    }
    for (let i = 0; i < 32; i++) {
      let sp: Spark = this.sparks.getInstanceForced();
      sp.set(this.pos, Turret.rand.nextSignedFloat(0.5), Turret.rand.nextSignedFloat(0.5),
             0.5 + Turret.rand.nextFloat(0.5), 0.5 + Turret.rand.nextFloat(0.5), 0, 30 + Turret.rand.nextInt(30));
    }
    for (let i = 0; i < 7; i++) {
      let f: Fragment = this.fragments.getInstanceForced();
      f.set(this.pos, Turret.rand.nextSignedFloat(0.25), Turret.rand.nextSignedFloat(0.25), 0.05 + Turret.rand.nextFloat(0.05),
            this.spec.size * (0.5 + Turret.rand.nextFloat(0.5)));
    }
    switch (this.spec.type) {
    case TurretSpec.TurretType.MAIN:
      this.parent.increaseMultiplier(2);
      this.parent.addScore(40);
      break;
    case TurretSpec.TurretType.SUB:
    case TurretSpec.TurretType.SUB_DESTRUCTIVE:
      this.parent.increaseMultiplier(1);
      this.parent.addScore(20);
      break;
    }
  }

  public remove(): void {
    if (this.destroyedCnt < 0)
      this.destroyedCnt = 999;
  }
}

/**
 * Turret specification changing according to a rank(difficulty).
 */
export class TurretSpec {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly TurretType = {
    MAIN: 0,
    SUB: 1,
    SUB_DESTRUCTIVE: 2,
    SMALL: 3,
    MOVING: 4,
    DUMMY: 5
  } as const;
  type: number;
  interval: number;
  speed: number;
  speedAccel: number;
  minRange: number;
  maxRange: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float minRange, maxRange;
  turnSpeed: number;
  turnRange: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: float turnSpeed, turnRange;
  burstNum: number;
  burstInterval: number;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: int burstNum, burstInterval;
  burstTurnRatio: number;
  blind: boolean;
  lookAheadRatio: number;
  nway: number;
  nwayAngle: number;
  nwayChange: boolean;
  bulletShape: number;
  bulletDestructive: boolean;
  shield: number;
  invisible: boolean;
  shape: TurretShape;
  damagedShape: TurretShape;
  destroyedShape: TurretShape;
  // PORT_NOTE[D2TS:multi-decl]:
  // reason: Split D multi-variable declaration into one-per-line.
  // original: TurretShape shape, damagedShape, destroyedShape;
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  _size: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor() {
    this.shape = new TurretShape(TurretShape.TurretShapeType.NORMAL);
    this.damagedShape = new TurretShape(TurretShape.TurretShapeType.DAMAGED);
    this.destroyedShape = new TurretShape(TurretShape.TurretShapeType.DESTROYED);
    this.init();
  }

  private init(): void {
    this.type = 0;
    this.interval = 99999;
    this.speed = 1;
    this.speedAccel = 0;
    this.minRange = 0;
    this.maxRange = 99999;
    this.turnSpeed = 99999;
    this.turnRange = 99999;
    this.burstNum = 1;
    this.burstInterval = 99999;
    this.burstTurnRatio = 0;
    this.blind = false;
    this.lookAheadRatio = 0;
    this.nway = 1;
    this.nwayAngle = 0;
    this.nwayChange = false;
    this.bulletShape = BulletShape.BulletShapeType.NORMAL;
    this.bulletDestructive = false;
    this.shield = 99999;
    this.invisible = false;
    this._size = 1;
  }

  public setParam(ts: TurretSpec): void {
    this.type = ts.type;
    this.interval = ts.interval;
    this.speed = ts.speed;
    this.speedAccel = ts.speedAccel;
    this.minRange = ts.minRange;
    this.maxRange = ts.maxRange;
    this.turnSpeed = ts.turnSpeed;
    this.turnRange = ts.turnRange;
    this.burstNum = ts.burstNum;
    this.burstInterval = ts.burstInterval;
    this.burstTurnRatio = ts.burstTurnRatio;
    this.blind = ts.blind;
    this.lookAheadRatio = ts.lookAheadRatio;
    this.nway = ts.nway;
    this.nwayAngle = ts.nwayAngle;
    this.nwayChange = ts.nwayChange;
    this.bulletShape = ts.bulletShape;
    this.bulletDestructive = ts.bulletDestructive;
    this.shield = ts.shield;
    this.invisible = ts.invisible;
    size = ts.size;
  }

  public setParam(rank: number, type: number, rand: Rand): void {
    this.init();
    this.type = type;
    if (type == TurretType.DUMMY) {
      this.invisible = true;
      return;
    }
    let rk: number = rank;
    switch (type) {
    case TurretType.SMALL:
      this.minRange = 8;
      this.bulletShape = BulletShape.BulletShapeType.SMALL;
      this.blind = true;
      this.invisible = true;
      break;
    case TurretType.MOVING:
      this.minRange = 6;
      this.bulletShape = BulletShape.BulletShapeType.MOVING_TURRET;
      this.blind = true;
      this.invisible = true;
      this.turnSpeed = 0;
      this.maxRange = 9 + rand.nextFloat(12);
      rk *= (10.0 / sqrt(this.maxRange));
      break;
    default:
      this.maxRange = 9 + rand.nextFloat(16);
      this.minRange = this.maxRange / (4 + rand.nextFloat(0.5));
      if (type == TurretType.SUB || type == TurretType.SUB_DESTRUCTIVE) {
        this.maxRange *= 0.72;
        this.minRange *= 0.9;
      }
      rk *= (10.0 / sqrt(this.maxRange));
      if (rand.nextInt(4) == 0) {
        let lar: number = rank * 0.1;
        if (lar > 1)
          lar = 1;
        this.lookAheadRatio = rand.nextFloat(lar / 2) + lar / 2;
        rk /= (1 + this.lookAheadRatio * 0.3);
      }
      if (rand.nextInt(3) == 0 && this.lookAheadRatio == 0) {
        this.blind = false;
        rk *= 1.5;
      } else {
        this.blind = true;
      }
      this.turnRange = PI / 4 + rand.nextFloat(PI / 4);
      this.turnSpeed = 0.005 + rand.nextFloat(0.015);
      if (type == TurretType.MAIN)
        this.turnRange *= 1.2;
      if (rand.nextInt(4) == 0)
        this.burstTurnRatio = rand.nextFloat(0.66) + 0.33;
      break;
    }
    this.burstInterval = 6 + rand.nextInt(8);
    switch (type) {
    case TurretType.MAIN:
      size = 0.42 + rand.nextFloat(0.05);
      let br: number = (rk * 0.3) * (1 + rand.nextSignedFloat(0.2));
      let nr: number = (rk * 0.33) * rand.nextFloat(1);
      let ir: number = (rk * 0.1) * (1 + rand.nextSignedFloat(0.2));
      this.burstNum = /* D_CAST(int) */ br + 1;
      this.nway = /* D_CAST(int) */ (nr * 0.66 + 1);
      this.interval = /* D_CAST(int) */ (120.0 / (ir * 2 + 1)) + 1;
      let sr: number = rk - this.burstNum + 1 - (this.nway - 1) / 0.66 - ir;
      if (sr < 0)
        sr = 0;
      this.speed = sqrt(sr * 0.6);
      assert(!Number.isNaN(this.speed) && !Number.isNaN(0));
      this.speed *= 0.12;
      this.shield = 20;
      break;
    case TurretType.SUB:
      size = 0.36 + rand.nextFloat(0.025);
      let br: number = (rk * 0.4) * (1 + rand.nextSignedFloat(0.2));
      let nr: number = (rk * 0.2) * rand.nextFloat(1);
      let ir: number = (rk * 0.2) * (1 + rand.nextSignedFloat(0.2));
      this.burstNum = /* D_CAST(int) */ br + 1;
      this.nway = /* D_CAST(int) */ (nr * 0.66 + 1);
      this.interval = /* D_CAST(int) */ (120.0 / (ir * 2 + 1)) + 1;
      let sr: number = rk - this.burstNum + 1 - (this.nway - 1) / 0.66 - ir;
      if (sr < 0)
        sr = 0;
      this.speed = sqrt(sr * 0.7);
      assert(!Number.isNaN(this.speed) && !Number.isNaN(0));
      this.speed *= 0.2;
      this.shield = 12;
      break;
    case TurretType.SUB_DESTRUCTIVE:
      size = 0.36 + rand.nextFloat(0.025);
      let br: number = (rk * 0.4) * (1 + rand.nextSignedFloat(0.2));
      let nr: number = (rk * 0.2) * rand.nextFloat(1);
      let ir: number = (rk * 0.2) * (1 + rand.nextSignedFloat(0.2));
      this.burstNum = /* D_CAST(int) */ br * 2 + 1;
      this.nway = /* D_CAST(int) */ (nr * 0.66 + 1);
      this.interval = /* D_CAST(int) */ (60.0 / (ir * 2 + 1)) + 1;
      this.burstInterval *= 0.88;
      this.bulletShape = BulletShape.BulletShapeType.DESTRUCTIVE;
      this.bulletDestructive = true;
      let sr: number = rk - (this.burstNum - 1) / 2 - (this.nway - 1) / 0.66 - ir;
      if (sr < 0)
        sr = 0;
      this.speed = sqrt(sr * 0.7);
      assert(!Number.isNaN(this.speed) && !Number.isNaN(0));
      this.speed *= 0.33;
      this.shield = 12;
      break;
    case TurretType.SMALL:
      size = 0.33;
      let br: number = (rk * 0.33) * (1 + rand.nextSignedFloat(0.2));
      let ir: number = (rk * 0.2) * (1 + rand.nextSignedFloat(0.2));
      this.burstNum = /* D_CAST(int) */ br + 1;
      this.nway = 1;
      this.interval = /* D_CAST(int) */ (120.0 / (ir * 2 + 1)) + 1;
      let sr: number = rk - this.burstNum + 1 - ir;
      if (sr < 0)
        sr = 0;
      this.speed = sqrt(sr);
      assert(!Number.isNaN(this.speed) && !Number.isNaN(0));
      this.speed *= 0.24;
      break;
    case TurretType.MOVING:
      size = 0.36;
      let br: number = (rk * 0.3) * (1 + rand.nextSignedFloat(0.2));
      let nr: number = (rk * 0.1) * rand.nextFloat(1);
      let ir: number = (rk * 0.33) * (1 + rand.nextSignedFloat(0.2));
      this.burstNum = /* D_CAST(int) */ br + 1;
      this.nway = /* D_CAST(int) */ (nr * 0.66 + 1);
      this.interval = /* D_CAST(int) */ (120.0 / (ir * 2 + 1)) + 1;
      let sr: number = rk - this.burstNum + 1 - (this.nway - 1) / 0.66 - ir;
      if (sr < 0)
        sr = 0;
      this.speed = sqrt(sr * 0.7);
      assert(!Number.isNaN(this.speed) && !Number.isNaN(0));
      this.speed *= 0.2;
      break;
    }
    if (this.speed < 0.1)
      this.speed = 0.1;
    else
      this.speed = sqrt(this.speed * 10) / 10;
    assert(!Number.isNaN(this.speed) && !Number.isNaN(0));
    if (this.burstNum > 2) {
      if (rand.nextInt(4) == 0) {
        this.speed *= 0.8;
        this.burstInterval *= 0.7;
        this.speedAccel = (this.speed * (0.4 + rand.nextFloat(0.3))) / this.burstNum;
        if (rand.nextInt(2) == 0)
          this.speedAccel *= -1;
        this.speed -= this.speedAccel * this.burstNum / 2;
      }
      if (rand.nextInt(5) == 0) {
        if (this.nway > 1)
          this.nwayChange = true;
      }
    }
    this.nwayAngle = (0.1 + rand.nextFloat(0.33)) / (1 + this.nway * 0.1);
  }

  public setBossSpec(): void {
    this.minRange = 0;
    this.maxRange *= 1.5;
    this.shield *= 2.1;
  }

  public size(): number {
    return this._size;
  }

  public size(v: number): number {
    this._size = v;
    this.shape.size = this.damagedShape.size = this.destroyedShape.size = this._size;
    return this._size;
  }
}

/**
 * Grouped turrets.
 */
export class TurretGroup {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly MAX_NUM: number = 16;
  ship: Ship;
  sparks: SparkPool;
  smokes: SmokePool;
  fragments: FragmentPool;
  spec: TurretGroupSpec;
  centerPos: Vector;
  turret: Turret[];
  cnt: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor(field: Field, bullets: BulletPool, ship: Ship, sparks: SparkPool, smokes: SmokePool, fragments: FragmentPool, parent: Enemy) {
    this.ship = ship;
    this.centerPos = new Vector();
    for (const t of this.turret)
      t = new Turret(field, bullets, ship, sparks, smokes, fragments, parent);
  }

  public set(spec: TurretGroupSpec): void {
    this.spec = spec;
    for (let i = 0; i < spec.num; i++)
      this.turret[i].start(spec.turretSpec);
    this.cnt = 0;
  }

  public move(p: Vector, deg: number): boolean {
    let alive: boolean = false;
    this.centerPos.x = p.x;
    this.centerPos.y = p.y;
    let d: number;
    let md: number;
    let y: number;
    let my: number;
    // PORT_NOTE[D2TS:multi-decl]:
    // reason: Split D multi-variable declaration into one-per-line.
    // original: float d, md, y, my;
    switch (this.spec.alignType) {
    case TurretGroupSpec.AlignType.ROUND:
      d = this.spec.alignDeg;
      if (this.spec.num > 1) {
        md = this.spec.alignWidth / (this.spec.num - 1);
        d -= this.spec.alignWidth / 2;
      } else {
        md = 0;
      }
      break;
    case TurretGroupSpec.AlignType.STRAIGHT:
      y = 0;
      my = this.spec.offset.y / (this.spec.num + 1);
      break;
    }
    for (let i = 0; i < this.spec.num; i++) {
      let tbx: number;
      let tby: number;
      // PORT_NOTE[D2TS:multi-decl]:
      // reason: Split D multi-variable declaration into one-per-line.
      // original: float tbx, tby;
      switch (this.spec.alignType) {
      case TurretGroupSpec.AlignType.ROUND:
        tbx = sin(d) * this.spec.radius;
        tby = cos(d) * this.spec.radius;
        break;
      case TurretGroupSpec.AlignType.STRAIGHT:
        y += my;
        tbx = this.spec.offset.x;
        tby = y;
        d = atan2(tbx, tby);
        assert(!Number.isNaN(d) && !Number.isNaN(0));
        break;
      }
      tbx *= (1 - this.spec.distRatio);
      let bx: number = tbx * cos(-deg) - tby * sin(-deg);
      let by: number = tbx * sin(-deg) + tby * cos(-deg);
      alive |= this.turret[i].move(this.centerPos.x + bx, this.centerPos.y + by, d + deg);
      if (this.spec.alignType == TurretGroupSpec.AlignType.ROUND)
        d += md;
    }
    this.cnt++;
    return alive;
  }

  public draw(): void {
    for (let i = 0; i < this.spec.num; i++)
      this.turret[i].draw();
  }

  public remove(): void {
    for (let i = 0; i < this.spec.num; i++)
      this.turret[i].remove();
  }

  public checkCollision(x: number, y: number, c: Collidable, shot: Shot): boolean {
    let col: boolean = false;
    for (let i = 0; i < this.spec.num; i++)
      col |= this.turret[i].checkCollision(x, y, c, shot);
    return col;
  }
}

export class TurretGroupSpec {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly AlignType = {
    ROUND: 0,
    STRAIGHT: 1
  } as const;
  turretSpec: TurretSpec;
  num: number;
  alignType: number;
  alignDeg: number;
  alignWidth: number;
  radius: number;
  distRatio: number;
  offset: Vector;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor() {
    this.turretSpec = new TurretSpec();
    this.offset = new Vector();
    this.num = 1;
    this.alignDeg = this.alignWidth = 0;
    this.radius = 0;
    this.distRatio = 0;
  }

  public init(): void {
    this.num = 1;
    this.alignType = AlignType.ROUND;
    this.alignDeg = this.alignWidth = this.radius = this.distRatio = 0;
    this.offset.x = this.offset.y = 0;
  }
}

/**
 * Turrets moving around a bridge.
 */
export class MovingTurretGroup {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: private:
  static readonly MAX_NUM: number = 16;
  ship: Ship;
  spec: MovingTurretGroupSpec;
  radius: number;
  radiusAmpCnt: number;
  deg: number;
  rollAmpCnt: number;
  swingAmpCnt: number;
  swingAmpDeg: number;
  swingFixDeg: number;
  alignAmpCnt: number;
  distDeg: number;
  distAmpCnt: number;
  cnt: number;
  centerPos: Vector;
  turret: Turret[];

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor(field: Field, bullets: BulletPool, ship: Ship, sparks: SparkPool, smokes: SmokePool, fragments: FragmentPool, parent: Enemy) {
    this.ship = ship;
    this.centerPos = new Vector();
    for (const t of this.turret)
      t = new Turret(field, bullets, ship, sparks, smokes, fragments, parent);
    this.radius = this.radiusAmpCnt = 0;
    this.deg = 0;
    this.rollAmpCnt = this.swingAmpCnt = this.swingAmpDeg = this.swingFixDeg = this.alignAmpCnt = 0;
    this.distDeg = this.distAmpCnt = 0;
  }

  public set(spec: MovingTurretGroupSpec): void {
    this.spec = spec;
    this.radius = spec.radiusBase;
    this.radiusAmpCnt = 0;
    this.deg = 0;
    this.rollAmpCnt = this.swingAmpCnt = this.swingAmpDeg = this.alignAmpCnt = 0;
    this.distDeg = this.distAmpCnt = 0;
    this.swingFixDeg = PI;
    for (let i = 0; i < spec.num; i++)
      this.turret[i].start(spec.turretSpec);
    this.cnt = 0;
  }

  public move(p: Vector, ed: number): void {
    if (this.spec.moveType == MovingTurretGroupSpec.MoveType.SWING_FIX)
      this.swingFixDeg = ed;
    this.centerPos.x = p.x;
    this.centerPos.y = p.y;
    if (this.spec.radiusAmp > 0) {
      this.radiusAmpCnt += this.spec.radiusAmpVel;
      let av: number = sin(this.radiusAmpCnt);
      this.radius = this.spec.radiusBase + this.spec.radiusAmp * av;
    }
    if (this.spec.moveType == MovingTurretGroupSpec.MoveType.ROLL) {
      if (this.spec.rollAmp != 0) {
        this.rollAmpCnt += this.spec.rollAmpVel;
        let av: number = sin(this.rollAmpCnt);
        this.deg += this.spec.rollDegVel + this.spec.rollAmp * av;
      } else {
        this.deg += this.spec.rollDegVel;
      }
    } else {
      this.swingAmpCnt += this.spec.swingAmpVel;
      if (cos(this.swingAmpCnt) > 0) {
        this.swingAmpDeg += this.spec.swingDegVel;
      } else {
        this.swingAmpDeg -= this.spec.swingDegVel;
      }
      if (this.spec.moveType == MovingTurretGroupSpec.MoveType.SWING_AIM) {
        let od: number;
        let shipPos: Vector = this.ship.nearPos(this.centerPos);
        if (shipPos.dist(this.centerPos) < 0.1)
          od = 0;
        else
          od = atan2(shipPos.x - this.centerPos.x, shipPos.y - this.centerPos.y);
        assert(!Number.isNaN(od) && !Number.isNaN(0));
        od += this.swingAmpDeg - this.deg;
        Math.normalizeDeg(od);
        this.deg += od * 0.1;
      } else {
        let od: number = this.swingFixDeg + this.swingAmpDeg - this.deg;
        Math.normalizeDeg(od);
        this.deg += od * 0.1;
      }
    }
    let d: number;
    let ad: number;
    let md: number;
    // PORT_NOTE[D2TS:multi-decl]:
    // reason: Split D multi-variable declaration into one-per-line.
    // original: float d, ad, md;
    this.calcAlignDeg(d, ad, md);
    for (let i = 0; i < this.spec.num; i++) {
      d += md;
      let bx: number = sin(d) * this.radius * this.spec.xReverse;
      let by: number = cos(d) * this.radius * (1 - this.spec.distRatio);
      let fs: number;
      let fd: number;
      // PORT_NOTE[D2TS:multi-decl]:
      // reason: Split D multi-variable declaration into one-per-line.
      // original: float fs, fd;
      if (fabs(bx) + fabs(by) < 0.1) {
        fs = this.radius;
        fd = d;
      } else {
        fs = sqrt(bx * bx + by * by);
        fd = atan2(bx, by);
        assert(!Number.isNaN(fd) && !Number.isNaN(0));
      }
      fs *= 0.06;
      this.turret[i].move(this.centerPos.x, this.centerPos.y, d, fs, fd);
    }
    this.cnt++;
  }

  private calcAlignDeg(d: number, ad: number, md: number): void {
    this.alignAmpCnt += this.spec.alignAmpVel;
    ad = this.spec.alignDeg * (1 + sin(this.alignAmpCnt) * this.spec.alignAmp);
    if (this.spec.num > 1) {
      if (this.spec.moveType == MovingTurretGroupSpec.MoveType.ROLL)
        md = ad / this.spec.num;
      else
        md = ad / (this.spec.num - 1);
    } else {
      md = 0;
    }
    d = this.deg - md - ad / 2;
  }

  public draw(): void {
    for (let i = 0; i < this.spec.num; i++)
      this.turret[i].draw();
  }

  public remove(): void {
    for (let i = 0; i < this.spec.num; i++)
      this.turret[i].remove();
  }
}

export class MovingTurretGroupSpec {
 // PORT_NOTE[D2TS:visibility-block]:
 // reason: D visibility block syntax is unsupported in TS.
 // original: public:
  static readonly MoveType = {
    ROLL: 0,
    SWING_FIX: 1,
    SWING_AIM: 2
  } as const;
  turretSpec: TurretSpec;
  num: number;
  alignDeg: number;
  alignAmp: number;
  alignAmpVel: number;
  radiusBase: number;
  radiusAmp: number;
  radiusAmpVel: number;
  moveType: number;
  rollDegVel: number;
  rollAmp: number;
  rollAmpVel: number;
  swingDegVel: number;
  swingAmpVel: number;
  distRatio: number;
  xReverse: number;

  // PORT_NOTE[D2TS:invariant]: removed D invariant block

  public constructor() {
    this.turretSpec = new TurretSpec();
    this.num = 1;
    this.initParam();
  }

  private initParam(): void {
    this.num = 1;
    this.alignDeg = PI * 2;
    this.alignAmp = this.alignAmpVel = 0;
    this.radiusBase = 1;
    this.radiusAmp = this.radiusAmpVel = 0;
    this.moveType = MoveType.SWING_FIX;
    this.rollDegVel = this.rollAmp = this.rollAmpVel = 0;
    this.swingDegVel = this.swingAmpVel = 0;
    this.distRatio = 0;
    this.xReverse = 1;
  }

  public init(): void {
    this.initParam();
  }

  public setAlignAmp(a: number, v: number): void {
    this.alignAmp = a;
    this.alignAmpVel = v;
  }

  public setRadiusAmp(a: number, v: number): void {
    this.radiusAmp = a;
    this.radiusAmpVel = v;
  }

  public setRoll(dv: number, a: number, v: number): void {
    this.moveType = MoveType.ROLL;
    this.rollDegVel = dv;
    this.rollAmp = a;
    this.rollAmpVel = v;
  }

  public setSwing(dv: number, a: number, aim: boolean = false): void {
    if (aim)
      this.moveType = MoveType.SWING_AIM;
    else
      this.moveType = MoveType.SWING_FIX;
    this.swingDegVel = dv;
    this.swingAmpVel = a;
  }

  public setXReverse(xr: number): void {
    this.xReverse = xr;
  }
}
